### ISSUE TITLE
希望添加 == === 双等号 三等号的连体字的支持

### ISSUE THREAD

**Issue by varnbu** [subframe7536/Maple-font#101]
大佬
希望添加 == === 双等号 三等号的连体字，
此前使用jetbrains mono 有这两个的支持
对于js开发来说比较常用。

**Comment by subframe7536** [comment]
在vscode的`setting.json`里加上
```json
{
  "editor.fontLigatures": "'calt','ss01'",
}
```

webstorm 暂不支持，可以等下一版自定义配置

**Comment by viocha** [comment]
> 在vscode的`setting.json`里加上
> 
> ```json
> {
>   "editor.fontLigatures": "'calt','ss01'",
> }
> ```
> 
> webstorm 暂不支持，可以等下一版自定义配置

下一版预计什么时候发布？

**Comment by subframe7536** [comment]
v7 beta 我自己已经用了快两个月了

正式发布需要我写个网页版的自定义工具
