### ISSUE TITLE
它在VsCode里不能中英2:1等宽，思源黑体 HW这款是可以做到的

### ISSUE THREAD

**Issue by CandyTek** [subframe7536/Maple-font#102]
大大加油！

**Comment by subframe7536** [comment]
我这里一切正常，麻烦发一下复现的图

**Comment by HolyshitOvO** [comment]
win10，VsCode最新版，字体大小18，字体使用：Maple Mono NF
![Code_jQADmJgBCu](https://github.com/subframe7536/Maple-font/assets/39211450/5cceeb1a-be3b-47aa-ab55-c3b38049c399)
![Code_eIamPxk3ST](https://github.com/subframe7536/Maple-font/assets/39211450/0d28bbe6-18bf-45eb-9631-aa5826321c70)
