### ISSUE TITLE
MacOS IDEA里中英文等宽不是2:1

### ISSUE THREAD

**Issue by Luxcis** [subframe7536/maple-font#104]
<img width="965" alt="image" src="https://github.com/subframe7536/Maple-font/assets/49968787/6fe0829e-000e-4f97-a05c-0bc15d12f3f7">

**Comment by subframe7536** [comment]
idea连字目前不支持自定义配置

**Comment by subframe7536** [comment]
idea连字目前不支持自定义配置

**Comment by Luxcis** [comment]
目前看下来是和Mac的兼容问题，在sublime中也无法做到2:1对齐，希望之后有条件的话修复

**Comment by subframe7536** [comment]
https://github.com/laishulu/Sarasa-Term-SC-Nerd 可以的话试一下这个，看看是否对齐

**Comment by Luxcis** [comment]
> https://github.com/laishulu/Sarasa-Term-SC-Nerd 可以的话试一下这个，看看是否对齐

我目前使用的就是这个，是对齐的

**Comment by subframe7536** [comment]
有可能是 nerd font 的问题，有空的时候修复一下

**Comment by subframe7536** [comment]
在 2023.2 中还存在这个问题吗

**Comment by Luxcis** [comment]
<img width="160" alt="image" src="https://github.com/subframe7536/maple-font/assets/49968787/043afa15-7a35-4998-a012-d96e9622e052">
可以了
