### ISSUE TITLE
Cursive font is not being applied

### ISSUE THREAD

**Issue by sayeed205** [subframe7536/Maple-font#105]
![image](https://github.com/subframe7536/Maple-font/assets/63891956/6ec93e45-74af-46fa-b522-d79282b98c12)

Here you can see cursive font is not  being applied anywhere 
tested in comments, keywords like - `this`, `class`, `import`

Winodws 11 (22H2)
VS Code - 1.78.2

**Comment by subframe7536** [comment]
I don't understand your issue very clearly. You mean ligatures don't work on italics?

**Comment by sayeed205** [comment]
> I don't understand your issue very clearly. You mean ligatures don't work on italic style?

I mean the cursive style in italic font show in screenshots for example - ![java](https://github.com/subframe7536/Maple-font/raw/main/img/code_sample/java.webp)

but it seems after changing some setting in vscode it started to working

settings I applied
```JSON
"editor.tokenColorCustomizations": {
        "textMateRules": [
            {
                "scope": [
                    "comment",
                    "keyword", //import, export, return …
                    "storage.modifier", //static keyword
                    "storage.type", //class keyword
                    "constant", // String, Number, this, super
                    "variable.other.constant.property", //JSON key strings
                    "variable.language" //arguments, new, this
                ],
                "settings": {
                    "fontStyle": "italic"
                }
            }
        ]
    },
```

before - 
![image](https://github.com/subframe7536/Maple-font/assets/63891956/c9f27d14-f29f-4f7a-9894-a88e0b7308f3)

after - 
![image](https://github.com/subframe7536/Maple-font/assets/63891956/f1b26b28-49a1-41c6-8015-6a50b20ba0b7)
