### ISSUE TITLE
Some Symbol under windows breaks

### ISSUE THREAD

**Issue by zhyzky** [subframe7536/Maple-font#106]
Here's a snap in emacs in windows.
![屏幕截图 2023-05-31 105921](https://github.com/subframe7536/Maple-font/assets/8426742/5f63377d-81c6-4e6d-ae2a-d08b30772604)
which should look like this, that is from linux
![屏幕截图 2023-05-31 110656](https://github.com/subframe7536/Maple-font/assets/8426742/b5ad5bc5-2a16-45a4-8cb3-2aebff4e7538)
Dont know if this is a windows font issue

**Comment by zhyzky** [comment]
I test some other applications like word, notepad in windows. None of them seems breaks the symbol.
Could I tell that something wrong with emacs on windows?

**Comment by subframe7536** [comment]
those symbols are added by font-patcher programmly and it should work the same across multiple platform. you can also test https://github.com/laishulu/Sarasa-Term-SC-Nerd to verify if the issue is emacs on windows

**Comment by zhyzky** [comment]
> those symbols are added by font-patcher programmly and it should work the same across multiple platform. you can also test https://github.com/laishulu/Sarasa-Term-SC-Nerd to verify if the issue is emacs on windows

Yes， SAME ISSUE HERE
And now I have changed the default org-modern-star to avoid using thease symbols.

**Comment by zhyzky** [comment]
I've digged out something related to this
https://github.com/domtronn/all-the-icons.el/issues/220

**Comment by subframe7536** [comment]
I'll read it at some time

**Comment by zhyzky** [comment]
> I'll read it at some time

Oh Sorry for not clearify my opinion. You're right it's not a font issue. 
I provide additional infomation here only if someone else got the same problerm.

It turns out to be a all-the-icon package issue, that could break some nerd font.
It's weired that only happened on windows though.
