### ISSUE TITLE
[Question] Different file formats

### ISSUE THREAD

**Issue by porterporter** [subframe7536/Maple-font#107]
What is the difference between the different download formats? Currently there are
- MapleMono-NF
- MapleMono-otf
- MapleMono-SC-NF
- MapleMono-woff2
- MapleMono-zip

**Comment by subframe7536** [comment]
- zip: minimal version, ttf format
- otf: minimal version, otf format, for better render effect on high pixel screen
- woff: minimal version, woff2 format, for small size on web pages
- NF: Nerd Font patched version, add icons for terminal
- SC-NF: full version, embed with Chinese characters

**Comment by subframe7536** [comment]
## Update for V7:

- TTF: minimal version, ttf format [Recommend!]
- OTF: minimal version, otf format
- TTF-autohint: minimal version, ttf format with hint, better for low resolution monitor
- WOFF2: minimal version, woff2 format, for small size on web pages
- NF: Nerd-Font patched version, add icons for terminal
- NF-CN: full version, embed with Chinese and Japanese characters
- Varaible: minimal version, smoothly change font weight by variable

### Differences between "hinted font" and "unhinted font":
- "hinted font" is used for low resolution screen to have better render effect. From my experience, if your screen resolution is lower or equal than 1080P, it is recommended to use "hinted font". In this case, you can choose MapleMono-TTF-AutoHint / MapleMono-NF / MapleMono-NF-CN.
- "unhinted font" is used for high resolution screen (e.g. for Mac), when using "hinted font", it will blur your text or make it looks weird. In this case, you can choose MapleMono-OTF / MapleMono-TTF. If you want to support Nerd Font, you can set MapleMono-NF (or NerdFontBase.ttf in src-font dir) as fallback font, or build your own font. 同理，如果需要支持中文字体，把MapleMono-NF-CN设置为回退字体或者自行构建即可

**Comment by subframe7536** [comment]
https://github.com/subframe7536/maple-font/tree/variable?tab=readme-ov-file#naming-faq
