### ISSUE TITLE
some feedback, e.g. cv03 a is too small

### ISSUE THREAD

**Issue by davidosomething** [subframe7536/maple-font#109]
![image](https://github.com/subframe7536/maple-font/assets/609213/eecac3ee-1165-4c39-86d9-fac607ef26c3)

Rendered in WezTerm on Wayland at 4k

- "a" is too small in cv03
- kerning is wrong in word `disabled` -> `ed` too close together, same with `ode` in `Code` - i think it is the size of `d`
- spacing of `",` is too far apart
- `_` underscore looks too short, see words like "with_fallback"

**Comment by subframe7536** [comment]
solution for some bugs #82

**Comment by davidosomething** [comment]
did not help me, those were related to type-hinting (i.e. anti-aliasing)
the issue i am seeing is kerning and sizing related
i.e. in the screenshot you can see the letter `a` has a much smaller x-height than the letter adjacent to it
and the letter `d` is too far to the left, so it is right next to `e` in `ed` and too far from `o` in `dotted`

**Comment by subframe7536** [comment]
![image](https://github.com/subframe7536/maple-font/assets/78338239/d3217331-f39f-45f1-b9cc-88d7a85355ca)

config and rendered characters on wayland but not 4K
