### ISSUE TITLE
Some font ligature not rendered properly on vscode

### ISSUE THREAD

**Issue by hi-reeve** [subframe7536/maple-font#110]
thankyou for this beautiful font, but on my vscode i did not see this change when i enable the ligature.
im using macos venture 13.4

![image](https://github.com/subframe7536/maple-font/assets/45350572/59405118-0ab3-4bbf-94c8-62bbe11c11d0)

**Comment by TheLastZombie** [comment]
Make sure to enable ligatures in VS Code's settings:

1. Click on _View > Command Palette_ or press _Ctrl+Shift+P_
2. Search for and click on _Preferences: Open User Settings (JSON)_

You can now either enable the default set of ligatures by adding:
```JSON
"editor.fontLigatures": true,
```

Or specify which ones you want by consulting [this image](https://raw.githubusercontent.com/subframe7536/maple-font/main/img/option.png). For example, if you only want to enable the alternative lowercase _i_ and _a_, you'd add:
```JSON
"editor.fontLigatures": "'cv02', 'cv03'",
```

**Comment by hi-reeve** [comment]
> Make sure to enable ligatures in VS Code's settings:
> 
> 1. Click on _View > Command Palette_ or press _Ctrl+Shift+P_
> 2. Search for and click on _Preferences: Open User Settings (JSON)_
> 
> You can now either enable the default set of ligatures by adding:
> 
> ```json
> "editor.fontLigatures": true,
> ```
> 
> Or specify which ones you want by consulting [this image](https://raw.githubusercontent.com/subframe7536/maple-font/main/img/option.png). For example, if you only want to enable the alternative lowercase _i_ and _a_, you'd add:
> 
> ```json
> "editor.fontLigatures": "'cv02', 'cv03'",
> ```

i've set this to true, here's another screenshot
the arrow is working, but the === is not working

![image](https://github.com/subframe7536/maple-font/assets/45350572/cff7cbe4-c9a8-4c83-8f4d-db6070dea04c)

**Comment by TheLastZombie** [comment]
Seems like the `===` ligature isn't enabled by default. Try using the second method instead, so that instead of this:

![image](https://github.com/subframe7536/maple-font/assets/8181990/d63405ce-49d6-4651-9676-010fa4e577a0)

You have something like this:

![image](https://github.com/subframe7536/maple-font/assets/8181990/7665dfdb-50ff-423e-a8d2-0930cf1e705c)

**Comment by subframe7536** [comment]
@hi-reeve you can see more info at pinned issue

**Comment by hi-reeve** [comment]
> @hi-reeve you can see more info at pinned issue

ah i miss that one, thankyou

> Seems like the `===` ligature isn't enabled by default. Try using the second method instead, so that instead of this:
> 
> ![image](https://user-images.githubusercontent.com/8181990/245709972-d63405ce-49d6-4651-9676-010fa4e577a0.png)
> 
> You have something like this:
> 
> ![image](https://user-images.githubusercontent.com/8181990/245710036-7665dfdb-50ff-423e-a8d2-0930cf1e705c.png)

thanks!
