### ISSUE TITLE
Nerd font 似乎支持的不是很全？

### ISSUE THREAD

**Issue by QuarkPixel** [subframe7536/maple-font#111]
我在使用 [LazyVim](https://github.com/LazyVim/LazyVim) 的时候会遇到部分的字体显示不出来
感觉蛮多icon是无法显示的，截了两个。
Maple:
![image](https://github.com/subframe7536/maple-font/assets/65812149/de9f60dd-1dba-4a41-b24f-97d042e59924) (U+DB81)
![image](https://github.com/subframe7536/maple-font/assets/65812149/4b6eff0d-7671-42a5-b81b-47d9f4c890ac)

FiraCode:
![image](https://github.com/subframe7536/maple-font/assets/65812149/cd6092ec-e6a6-4365-a177-0a4f7c67797c)
![image](https://github.com/subframe7536/maple-font/assets/65812149/3f63e742-3355-4f65-8e08-b24ad6e18b60)

在 Windows Terminal 没有 font-fallback 机制下有一款万金油字体我觉得还是蛮重要的，希望支持下awa

**Comment by subframe7536** [comment]
目前的nerd font编译参数是 -l -s --careful -c，按理说应该都能显示

**Comment by subframe7536** [comment]
那些无法显示的图标的unicode发我一下，我看看

**Comment by subframe7536** [comment]
或者试一下Maple Mono NF

**Comment by QuarkPixel** [comment]
试了Maple Mono NF，没有解决问题。无法显示的图标的unicode我目前截到了一个(U+DB81)，其他的不太好复制qwq

**Comment by LC0117** [comment]
+1，[nerd fonts](https://github.com/ryanoasis/nerd-fonts)更新到3.0.0后新加了一些icon，但是maple mono6.3似乎没有加进去

**Comment by CnsMaple** [comment]
'󰡱'
'󰅳'
'󰎠'
'󰅨'
'󰟢'
 '󰭷'
 '󰊱'
像上面这些。

**Comment by subframe7536** [comment]
已发布，新版本升级了 nerd font 的版本，应该已经修复这个issue了
