### ISSUE TITLE
如何自己build关闭连字效果

### ISSUE THREAD

**Issue by Case3y** [subframe7536/maple-font#112]
怎么build出只保留cv01和cv04的效果并且不开启的一个字体版本？尝试修改gsub文件但是没有成功。
我使用了 https://mutsuntsai.github.io/fontfreeze/ 这个网站输出了自己希望的结果，但是输出后字体信息会发生变化，所以想问一下该如何自己build
![image](https://github.com/subframe7536/maple-font/assets/71315026/7925a0db-f34e-4cb5-97b0-f8079d3d55a9)

**Comment by subframe7536** [comment]
https://kekee000.github.io/fonteditor/#

**Comment by subframe7536** [comment]
已发布，可自行构建
