### ISSUE TITLE
Glyph sizes are too small

### ISSUE THREAD

**Issue by hqkhan** [subframe7536/maple-font#113]
Hello. I am on MacOS and was looking to use this font. I'm finding that `Maple Mono NF`'s glyphs are extremely small. Is this expected?

`Maple Mono NF`:

<img width="1082" alt="image" src="https://github.com/subframe7536/maple-font/assets/22674069/d67fee4d-686c-4039-9d09-5eceb1e3e4db">

`JetBrainsMono Nerd Font`:

<img width="1194" alt="image" src="https://github.com/subframe7536/maple-font/assets/22674069/18c2d877-0666-4ae0-93c3-85618be42071">

**Comment by subframe7536** [comment]
because the font is build with half width icon instead of full width one.

in V7, you can build your own font.

more detail: #103

**Comment by hqkhan** [comment]
Got it. Since V7 is still undetermined, I will close this issue.
