### ISSUE TITLE
使字体被识别为等宽字体

### ISSUE THREAD

**Issue by oraant** [subframe7536/maple-font#114]
这个字体的这个特性是否有参考意义？
> [Sarasa-Term-SC-Nerd#特性](https://github.com/laishulu/Sarasa-Term-SC-Nerd#%E7%89%B9%E6%80%A7)
修正了OS/2表中的panose和post表中的isFixedPitch，使得字体被系统认出是等 宽字体。

**Comment by subframe7536** [comment]
刚刚检查了一下，原本的字体这些属性都是正确的，感谢建议
