### ISSUE TITLE
Win字体属性缺失：设计用于、类别

### ISSUE THREAD

**Issue by realysy** [subframe7536/maple-font#116]
首先感谢制作一款这么好的字体~

目前在Onenote 2016中使用存在不足，在`选项-常规`中设置为默认字体后，

- 在中文输入法状态下输入中英文，没问题，字体都能正确显示；
- 在英文输入法状态下输入英文，会默认Calibri字体

我想可能是由于Win-字体“设计用于”和“类别”这两个字体属性缺失造成的，如图：

![图片](https://github.com/subframe7536/maple-font/assets/55436543/1fa650ac-b5b7-493c-9f26-e9f85beb1746)

有什么办法可以添加上这两个属性吗？

**Comment by subframe7536** [comment]
“设计用于”在我本地已经修改好了，但是不清楚“类别”这个属性是属于那张表里的

**Comment by realysy** [comment]
> “设计用于”在我本地已经修改好了，但是不清楚“类别”这个属性是属于那张表里的

好的感谢~加上“设计用于”应该就可以了

**Comment by subframe7536** [comment]
已发布
