### ISSUE TITLE
MapleMono-SC-NF 6.4版中文字体在Matlab下乱码

### ISSUE THREAD

**Issue by EVANGELION-Air** [subframe7536/Maple-font#118]
![Snipaste_2023-07-30_23-04-20](https://github.com/subframe7536/maple-font/assets/58524775/344f1a8f-431f-43ad-b996-9e53c7607f2f)

如图所示，中文输入和显示不是一个内容，中文出现乱码情况，换回6.3版后问题消失

**Comment by subframe7536** [comment]
没用过matlab，请问这段代码的编码类型是gbk吗？如果可以调整的话，调整成utf8试试

**Comment by subframe7536** [comment]
可能是 https://github.com/subframe7536/maple-font/commit/8c128ef1fd1bece7a6c45e43cd1d7f7219a94b32 的原因，我重新生成了一个版本，你可以试试
[MapleMono-SC-NF-Regular.zip](https://github.com/subframe7536/maple-font/files/12209733/MapleMono-SC-NF-Regular.zip)

**Comment by subframe7536** [comment]
[MapleMono-SC-NF-Regular.zip](https://github.com/subframe7536/maple-font/files/12209760/MapleMono-SC-NF-Regular.zip)
可以的话再试试这个，不行的话我也打算先鸽了🤣
