### ISSUE TITLE
Exception while freezing Maple Mono by fontfreeze

### ISSUE THREAD

**Issue by SsparKluo** [subframe7536/maple-font#122]
Looks like as the same issue in #96

**Comment by subframe7536** [comment]
It is a known isuue.
For some unknown reasons, when freeze font features by fontfreeze will cause error, so I write the [build guide](https://github.com/subframe7536/maple-font/tree/main/source)  instead of directly recommand to use fontfreeze

**Comment by subframe7536** [comment]
In my plan of V7, all the code will be rewritten in js/ts, a new website will be provided to introduce the font features and custom build font inside the browser

**Comment by sonulohani** [comment]
You can uncheck this and generate the font. This will work
![image](https://github.com/subframe7536/maple-font/assets/2958681/87569c97-c44c-4593-a8dc-4d627a1d419a)

**Comment by SsparKluo** [comment]
> @subframe7536  @SsparKluo  You can uncheck this and generate the font. This will work
> ![image](https://github.com/subframe7536/maple-font/assets/2958681/87569c97-c44c-4593-a8dc-4d627a1d419a)
> 

Thanks for your suggestion. It does have no error, but features are not frozen too, at least for terminals without ligature support.

**Comment by subframe7536** [comment]
@SsparKluo  maybe you should check you terminal in https://github.com/tonsky/FiraCode#terminal-compatibility-list . 

AFAIK, enabling ligatures by default will use `clig` instead of `calt`, and then the cursor inside ligature will be rendered incorrectly.

**Comment by SsparKluo** [comment]
I haven't met the rendering issue in windows terminal. 

As for those terminal not support ligature, those frozen font variants, like cv01, still work.

**Comment by subframe7536** [comment]
could you please provide me some example font files?

**Comment by SsparKluo** [comment]
> could you please provide me some example font files?

Sure, there is an old version of maple mono I froze before [MapleMono-SC-NF-Regular_freeze.zip](https://github.com/subframe7536/maple-font/files/12331128/MapleMono-SC-NF-Regular_freeze.zip).

And the feature cv01 works in the vscode integrated terminal
![image](https://github.com/subframe7536/maple-font/assets/32617864/66e51264-2420-4e2d-8738-9f4c6b103dfa)

**Comment by subframe7536** [comment]
For character variants, it can correctly be freezed

[MapleMonoFreeze-ttf.zip](https://github.com/subframe7536/maple-font/files/12331315/MapleMonoFreeze-ttf.zip) is generated by the build script, which enable all character variants, you can test it

**Comment by SsparKluo** [comment]
It works, thanks
