### ISSUE TITLE
如何构建一个不使用连字功能的字体呢

### ISSUE THREAD

**Issue by youyouhdhd** [subframe7536/maple-font#124]
您好，我想问一下我想关闭连字功能（包括基础的连字），该如何操作呢

**Comment by subframe7536** [comment]
目前不支持

一般来说只要不开启连字的配置就不显示连字了

**Comment by Case3y** [comment]
我加入 `"calt": Status.DISABLE` 并且将对clat的判断注释掉后实现了生成默认关闭连字的Maple字体
![image](https://github.com/subframe7536/maple-font/assets/71315026/990b70c7-e3d8-499d-86b2-aa58616b31e9)
![image](https://github.com/subframe7536/maple-font/assets/71315026/5fc9fb0f-4a9c-40ef-88a2-bf4a833f479b)


> 目前不支持
> 
> 一般来说只要不开启连字的配置就不显示连字了

**Comment by subframe7536** [comment]
https://github.com/subframe7536/maple-font/issues/125#issuecomment-1691738404
