### ISSUE TITLE
"胶"字没有

### ISSUE THREAD

**Issue by bricle** [subframe7536/maple-font#128]
![](https://iili.io/J9kgYkx.png)

**Comment by subframe7536** [comment]
重新打一遍或者换个输入法

有些字符看起来是同一个字，但是 unicode 是不同的

**Comment by subframe7536** [comment]
中文字体只是子集化了资源圆体，可能自带的映射在处理过程中丢失了

**Comment by weicong** [comment]
https://github.com/lxgw/LxgwNeoXiHei-Screen

**Comment by subframe7536** [comment]
整合至 #156
