### ISSUE TITLE
Polish letters missing

### ISSUE THREAD

**Issue by chmielcode** [subframe7536/maple-font#129]
Would it be possible to add all polish letters with diacritics: ą, ć, ę, ł, ń, ó, ś, ź, ż, ą, ć, ę, ł, ń, ó, ś, ź, ż? "Ó/ó" is already there :)
Really nice font, thank you for your work.

**Comment by subframe7536** [comment]
now you can try v7-beta4

**Comment by chmielcode** [comment]
@subframe7536 I think now we have all missing letters in place. Nice 👍
