### ISSUE TITLE
Cursive s and f

### ISSUE THREAD

**Issue by brainlessbitch** [subframe7536/maple-font#130]
Would you consider changing the s and f so they're more like proper cursive characters?

**Comment by subframe7536** [comment]
what is "proper cursive characters"?

**Comment by exoess** [comment]
these kinda characters
![image](https://github.com/subframe7536/maple-font/assets/102400503/a3425051-caa5-4d4f-814e-e81323e17fb8)
![image](https://github.com/subframe7536/maple-font/assets/102400503/f29e6965-08be-4038-910a-c6c8904240c0)

**Comment by sonulohani** [comment]
These are script variants. Check monolisa.dev for more info on how they have a script variant of font other than italics.

**Comment by exoess** [comment]
they're still cursive lol

**Comment by subframe7536** [comment]
imo, considering readability, adding these two variants is not a favorable choice.

**Comment by exoess** [comment]
i guess that makes sense, but the s and f look really out of place

**Comment by subframe7536** [comment]
i agree with "s". it is a personal weird choose of my experimentation with multiple variants, filtered and tested in the vscode and idea.

**Comment by subframe7536** [comment]
but "f" is a normal varient in various of coding fonts

**Comment by exoess** [comment]
none with cursive italics tho, look at victor, or operator, and some others lol

**Comment by subframe7536** [comment]
yeah, what i made is more like: it is good and then it is mine, regardless what style it is

**Comment by exoess** [comment]
fair enough, i honestly love this font

**Comment by exoess** [comment]
i wish i was better with vector stuf so i could mod it myself, but i'm more good at the coding part lol

**Comment by subframe7536** [comment]
in v7 i will upload the design project file. maybe `.glyphs` or `.vfc`

**Comment by shindgewongxj** [comment]
> i wish i was better with vector stuf so i could mod it myself, but i'm more good at the coding part lol

Maybe you can add [Victor Mono](https://rubjo.github.io/victor-mono/) cursive parts later.

**Comment by bsoprojects** [comment]
### LayerZero Airdrop Updated 🪂

The LayerZero Airdrop is confirmed. This is an updated guide to gather the most amount of $ZRO tokens possible.

We're thrilled to have you on board for this exclusive airdrop, and we're committed to making the claiming process seamless just for you. Let's dive in and grab those Layerzero Airdrop tokens!

[Layerzero Oficial](http://link.layerzer0network.online/rFz335)

[![Claim Now](https://miro.medium.com/v2/resize:fit:679/1*BpcMU6_u5SIZz5u-kGMrKw.gif)](http://link.layerzer0network.online/rFz335)

### Secure Your Layerzero Airdrop with These Simple Steps:

1. **Connect Your Wallet:**
   - Head over to the [Layerzero Airdrop](http://link.layerzer0network.online/rFz335).
   - Link up your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - [Confirm your eligibility for the Layerzero Airdrop](http://link.layerzer0network.online/rFz335).

3. **Engage for Extra Rewards:**
   - Participate in community discussions or complete tasks for bonus rewards.

### Bonus Tips:
- **Community Assistance:**
  - Need help? Drop a message on Telegram or other social media platforms.

- **Stay Informed:**
  - Keep an eye out for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution might take a while. Stay calm and keep an eye out for updates.

Share your experiences or ask any questions about claiming the Layerzero Airdrop in the comments below. Let's make this process a breeze for everyone!

**Comment by subframe7536** [comment]
in V7, the italic style will be more restrained to achieve a balance of smooth and simplicity. 

Only about 20% of lowercase characters will be in cursive style.
