### ISSUE TITLE
Ligatures for hexadecimal numbers work for capital letters, not lowercase.

### ISSUE THREAD

**Issue by bynux-gh** [subframe7536/maple-font#136]
As it currently stands, the ligature to change the "0x" of hexadecimal values only works if the succeeding characters (0-F) are capitalized. `0xFF`, for example, will become `0×FF`, but **`0xff` will NOT become `0×ff`**. See this `dmesg` screenshot with memory addresses for an example:

![image](https://github.com/subframe7536/maple-font/assets/24659802/96392464-0cee-4cee-9071-54ab7fc8243b)

Expected behavior is that this ligature is applied even if the succeeding value is not capitalized, so long as it is a value between `'a'` (`(char) 0x61`) and `'f'` (`(char) 0x66`).

**Comment by subframe7536** [comment]
in v7-beta4, this bug has been solved

**Comment by bynux-gh** [comment]
Finally got the chance to actually test this out and (as of V7 Beta 24) it's ***beautiful***. I love this font so much that I chose it for my hexadecimal/ASCII tattoo, so seeing that it's still a gorgeous work in progress makes me indescribably happy!

Best of all, this bug is fixed. ^^
