### ISSUE TITLE
Mac下仅在 VsCode Editor 中字体异常，VsCode Terminal、Iterm2 正常

### ISSUE THREAD

**Issue by changrui0608** [subframe7536/maple-font#142]
均为 "Maple Mono" 14号字体，仅在 VsCode 代码编辑器中字体异常（英文数字似乎是变宽了，并且字符间距更大了，也更丑了。。）

从 VSCode Terminal 表现正常来看，也可能是 VSCode 的问题。只是我几乎保持了默认设置，并且用过的 mono 字体里，也只有 Maple 有这个问题，因此试着这里问下有没有解决方法。

![image](https://github.com/subframe7536/maple-font/assets/18552541/410066b2-8e14-4efa-81ec-efe28102a111)

![image](https://github.com/subframe7536/maple-font/assets/18552541/66fefa8c-c67c-47c8-a189-dcaf21d58264)

字体使用 HomeBrew 安装的 6.3

**Comment by subframe7536** [comment]
homebrew的版本不包含中文字符，需要中英文等宽请前往release下载 Maple Mono SC NF

**Comment by changrui0608** [comment]
@subframe7536 不是等宽问题（实际上字体在iterm2里也是等宽的），是字体在 VSCode Editor 中样式和其他地方不一样

**Comment by subframe7536** [comment]
控制台会自动调整字符宽度的，VSCode 里就是原本的宽度，所以看起来是 VSCode 里变窄了

**Comment by subframe7536** [comment]
你仔细看一下你发的图，控制台的中文间距是比编辑器里的大的，因为在编辑器里所以刚开始会觉得很宽，习惯就好了

如果你觉得不喜欢，可以用 https://github.com/laishulu/Sarasa-Term-SC-Nerd 替代
