### ISSUE TITLE
Nerd Font 字符大小不协调

### ISSUE THREAD

**Issue by doooooit** [subframe7536/maple-font#143]
<img width="466" alt="image" src="https://github.com/subframe7536/maple-font/assets/11793795/5dd4b3df-b8c9-4b8b-933d-97842b24f8c6">

如图，大小不够协调，分支符号有点过高，而 js 符号又有点小，而且视觉上看起来不够居中

**Comment by subframe7536** [comment]
非等宽的nerd font请自行构建

**Comment by mystchonky** [comment]
Would that require more than just editing/enabling options in `build.py` ?

**Comment by subframe7536** [comment]
@mystchonky noop, just set this to `Status.DISABLE` https://github.com/subframe7536/maple-font/blob/719426f8d6ef87a44bb1485cc16b9f7d8761f2a4/source/build.py#L59

**Comment by mystchonky** [comment]
awesome! Thanks alot :)
