### ISSUE TITLE
似乎一些图标还是不是很全

### ISSUE THREAD

**Issue by CnsMaple** [subframe7536/maple-font#149]
![图片](https://github.com/subframe7536/maple-font/assets/92523839/b45e6a4e-a964-4563-a573-9455591665b0)

这个是下面这个，正常来说，这个是一个叉叉:
 

**Comment by CnsMaple** [comment]
在vscode显示的是这样的：
![图片](https://github.com/subframe7536/maple-font/assets/92523839/4bb0cbb4-0122-424d-bfa4-7921183e5a86)

**Comment by subframe7536** [comment]
字体没有任何一个图标，全靠 Nerd-font ，你可以自行构建

https://github.com/subframe7536/maple-font/blob/719426f8d6ef87a44bb1485cc16b9f7d8761f2a4/source/build.py#L72
