### ISSUE TITLE
终端的git 标识文字能支持上吗，这个字体还是可以的

### ISSUE THREAD

**Issue by a1one1y** [subframe7536/Maple-font#15]
<img width="271" alt="image" src="https://user-images.githubusercontent.com/99976288/186300221-b63f9e94-412c-48d0-9ae6-becdb7a34151.png">

终端用的 iterm2
主题是 spaceship
在git仓库里，git的标识会显示不了，请问后续有考虑支持一下吗
感谢~~

**Comment by a1one1y** [comment]
这个字体就符合我审美，想在终端也用上，就是有些符号 不能显示出来

**Comment by subframe7536** [comment]
![image](https://user-images.githubusercontent.com/78338239/186300861-9ae96128-997c-4f30-998d-fb594c73ca66.png)
我这里可以显示的，可以把你那一行复制下来发我吗我看一下

**Comment by a1one1y** [comment]
stack on  f-20220818-init @subframe7536

**Comment by a1one1y** [comment]
我现在用的是  DejaVu Sans Mono for Powerline字体才能显示

**Comment by a1one1y** [comment]
具体是变这样  
<img width="270" alt="image" src="https://user-images.githubusercontent.com/99976288/186301243-0e1da20d-c7e9-48d2-9f8c-e54bc00947b9.png">

**Comment by subframe7536** [comment]
可能是你字体选错了，需要用Maple Mono SC NF，我这里没问题，字符和DejaVu Sans Mono for Powerline是一样的

**Comment by a1one1y** [comment]
确实可以，那没事了，我只下了maple mono, 没有下SC NF的版本，刚才试了一下用SC的，确实能显示了，感谢 @subframe7536
