### ISSUE TITLE
IDEA 粗体

### ISSUE THREAD

**Issue by russleung44** [subframe7536/maple-font#152]
请教一下，为啥默认是粗体的，能不能改成常规的。如果这就是常规，能改成Light吗 ？
Windows 11 23H2
IDEA 2023.3.2

![PixPin_2024-01-03_10-45-10](https://github.com/subframe7536/maple-font/assets/56534185/da820cc7-451a-49e4-bf0c-691a3f34dc69)

![PixPin_2024-01-03_10-46-01](https://github.com/subframe7536/maple-font/assets/56534185/54edddcb-6324-41c5-86d1-194ef72645cd)

**Comment by subframe7536** [comment]
字体本身偏粗

**Comment by subframe7536** [comment]
因为v7是可变字体，所以我打算实现自定义默认字重，可以关注一下

**Comment by russleung44** [comment]
之前用过感觉很好的，这次换回来不知道为啥感觉变粗了。

**Comment by subframe7536** [comment]
如果不包含中文字体是会粗一些，一直不太清楚原因
