### ISSUE TITLE
WPS For Linux Seems not support the font

### ISSUE THREAD

**Issue by zhyzky** [subframe7536/maple-font#153]
打开WPS，选择Maple Mono SC NF字体后，弹出提示，选择的字体在该设备上不可用，该字体会以默认字体代替展示。
![image](https://github.com/subframe7536/maple-font/assets/8426742/9a1b96ac-bc30-49ad-8dd2-626280134d07)

**Comment by subframe7536** [comment]
抱歉，Office / WPS 没有计划支持

**Comment by zhyzky** [comment]
> 抱歉，Office / WPS 没有计划支持

那这个问题关了吧
