### ISSUE TITLE
Add support for Vietnamese

### ISSUE THREAD

**Issue by haunt98** [subframe7536/maple-font#160]
Thanks for beautiful font! Can I add minor suggestion about supporting Vietnamese language?

You can get the idea/character from https://vietnamesetypography.com/ or https://github.com/JetBrains/JetBrainsMono/issues/14

Thank you 👍

**Comment by subframe7536** [comment]
can you test the new `V7.0-alpha3` pre-release? It maybe have already support Vietnamese.

**Comment by haunt98** [comment]
Thanks @subframe7536, I test `V7.0-alpha3` and it already has support Vietnamese lang :D

<img width="261" alt="image" src="https://github.com/subframe7536/maple-font/assets/5424272/3f9f5e36-96db-4367-9a47-7fb7a93f6bd8">
