### ISSUE TITLE
intro page and custom build tools

### ISSUE THREAD

**Issue by subframe7536** [subframe7536/maple-font#162]
New website
- custom default weight (`avar`)
- freeze font feature (`gsub`)
- glyph replace (`hmtx` & `cff `)
- (maybe) append Nerd Font and CJK font
- code/variants/ligatures examples
- main stream IDE setup guide
- FAQ

**Comment by joneavila** [comment]
Does this mean `freeze_feature_list` will return in V7 build config?

**Comment by subframe7536** [comment]
Yes, I think it's very convenient to modify fonts just in the browser and choose your options visually. Maybe I should provide the native way to freeze features?

**Comment by subframe7536** [comment]
Some test on `hmtx` table:

Seems invalid in `opentype.js`:
![image](https://github.com/user-attachments/assets/95972d5c-62c6-48d5-a73b-2df13cd6392c)

Seems also invalid in `fontkit`:
![image](https://github.com/user-attachments/assets/71fa7633-3bd4-4691-bc70-3670b76ad676)

No support in `fonteditor-core`

Maybe just reuse `fontfreeze` is the best choice?

**Comment by subframe7536** [comment]
Figure out that `hmtx` is unnecessary for the font freeze

But `opentype.js` will 3x the size of the font file 😅

**Comment by subframe7536** [comment]
For custom builds, Codespace is convenient enough. Also, configuration is available in `config.json` and also can run with docker. So I do not plan to provide a purely web-based custom build.
