### ISSUE TITLE
Erroneous address in question symbol

### ISSUE THREAD

**Issue by arkhan** [subframe7536/maple-font#166]
This occurs with the last beta
![image](https://github.com/subframe7536/maple-font/assets/3141865/93662b7a-3307-49ff-ae9b-ca05fd34cc23)

Thanks

**Comment by subframe7536** [comment]
This will be fixed in next beta release

**Comment by subframe7536** [comment]
[v7.0-beta8](https://github.com/subframe7536/maple-font/releases/tag/v7.0-beta8) should fix this issue

**Comment by arkhan** [comment]
> [v7.0-beta8](https://github.com/subframe7536/maple-font/releases/tag/v7.0-beta8) should fix this issue

Persist in the last beta
![image](https://github.com/subframe7536/maple-font/assets/3141865/91b88d78-72b5-45da-b141-4256200eda65)

**Comment by subframe7536** [comment]
I'm sorry, I forgot to update the source font files.

I have replaced the old version with the correct files.
