### ISSUE TITLE
vscode中设置：JetBrains Mono, 'MapleMono-SC-NF', monospace。结果空格占了两个字符宽度

### ISSUE THREAD

**Issue by DataiBao** [subframe7536/maple-font#168]
![1d085c199fc098c90d98640f4e80012](https://github.com/subframe7536/maple-font/assets/53416542/5554ef50-b4a7-4757-b544-6480a3e24669)
有啥解决方案么，我把MapleMono-SC-NF换成了Courier New空格宽度又变回一个字符宽了
![image](https://github.com/subframe7536/maple-font/assets/53416542/eb34824d-55ed-4501-8e62-ce8661f47801)

**Comment by DataiBao** [comment]
解决了，是配置写错了。写成这样就有效果了："editor.fontFamily": "JetBrains Mono, 'Maple Mono SC NF', monospace"
![image](https://github.com/subframe7536/maple-font/assets/53416542/0c0c4fcf-764d-4bb3-bb7b-d9df686c8997)

**Comment by subframe7536** [comment]
如果只是需要中文等宽的话可以用[这个](https://github.com/Asvel/monoback)
