### ISSUE TITLE
V7 beta 9 - not all italic weights are detected.

### ISSUE THREAD

**Issue by jastko** [subframe7536/maple-font#170]
Under Linux, all static otf/ttf italic weights( **except Regular Italic**), aren't properly detected by some KDE applications, such as Konsole - KDE terminal emulator, or Kate - KDE text editor.

https://github.com/subframe7536/maple-font/assets/134521733/66e1437e-9332-4e4e-a711-fceb2228077e

I think, that `fsSelection` and `macStyle` have wrong settings. For example, from `ttx` decompilation of `BoldItalic` style:
 `fsSelection` is set to:
```
        .....
    <achVendID value="SUBF"/>
    <fsSelection value="00000000 10100000"/>
    <usFirstCharIndex value="0"/>
        .....
```
and according to the https://learn.microsoft.com/en-us/typography/opentype/spec/os2#fsselection, it should be:

`    <fsSelection value="00000000 10100001"/>
`

`macStyle` has a value of:
```
        .....
    <yMax value="1120"/>
    <macStyle value="00000000 00000001"/>
    <lowestRecPPEM value="6"/>
        .....
```
and should have:
`    <macStyle value="00000000 00000011"/>
`

After the change, everything works.

By the way, nice font, great work.

**Comment by subframe7536** [comment]
Thanks for your detailed suggestion! This will be fixed v7-beta10

**Comment by subframe7536** [comment]
This is caused by the generation of static fonts. But the NerdFont-patched version re-fix it.

**Comment by subframe7536** [comment]
release in v7-beta10

**Comment by jastko** [comment]
fixed, thanks
