### ISSUE TITLE
[QUESTION] How did you create GIF in README?

### ISSUE THREAD

**Issue by arcc1845** [subframe7536/maple-font#171]
I'm sorry, but I couldn't find a place to ask this question.

How did you create [this GIF](https://github.com/subframe7536/maple-font/blob/main/img/ligature.gif)? It seems like carbon.now.sh doesn't offer a way to make it into a GIF. Did you do it by screen recording?

**Comment by subframe7536** [comment]
Yes, and I have already created [a new gif](https://twitter.com/subframe7536/status/1762475926322082107?t=s6g4WyfNWMGlwKTmuFBgZQ&s=19) for v7

But it does not a good way, I plan to recreate it programmly
