### ISSUE TITLE
[Request]Add Chinese to woff

### ISSUE THREAD

**Issue by Gn3po4g** [subframe7536/maple-font#172]
And any plans to add woff to CDN platforms like https://cdn.jsdelivr.net/npm for easy reference?

**Comment by subframe7536** [comment]
For every single style, `woff` format is about 9MB, `woff2` format is about 6MB

I don't think it is suitable for a website to load

**Comment by Gn3po4g** [comment]
The only most commonly used in web pages are `regular` and `bold`, or with additional `italic`.

**Comment by subframe7536** [comment]
Originally, I made CN version for use in local editor or IDE. Can you describe your usage scenarios in detail?

**Comment by Gn3po4g** [comment]
Just use Maple in html.
```html
  @font-face {
    font-family: "Maple Mono";
    font-weight: 400;
    font-style: normal;
    src: url("/MapleMono/MapleMono-NF-CN-Regular.woff2") format('woff2');
  }
```
the file is converted from `ttf` on my own.
And if you upload the fonts on CDN for example, we can just add one line to include font file:
```html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/maple-mono/style.css" />
```

**Comment by subframe7536** [comment]
decide to use https://github.com/KonghaYao/chinese-free-web-font-storage

**Comment by subframe7536** [comment]
https://github.com/KonghaYao/chinese-free-web-font-storage/pull/77

**Comment by subframe7536** [comment]
https://chinese-font.netlify.app/zh-cn/fonts/maple-mono-cn/MapleMono-CN-Regular

**Comment by Gn3po4g** [comment]
🐮
