### ISSUE TITLE
[BUG] 关于在vscode中浏览中文字符居多的文件，自动换行无法正常显示的问题

### ISSUE THREAD

**Issue by Rlxzmdd** [subframe7536/maple-font#173]
问题描述：
在vscode中浏览中文文字居多的文件会出现自动换行的问题超出窗口范围的问题。
使用其他等宽中文字体无此问题，比如更纱黑体。

字体配置：
大小: 14
样式: 'JetBrains Mono', 'Maple Mono SC NF',-apple-system, Menlo, Monaco, 'Courier New', monospace

问题截图：
markdown文件（中文居多）
![image](https://github.com/subframe7536/maple-font/assets/13695917/73291a41-810b-4cb4-8be3-741cdf0acbc1)
java文件（英文居多）
![image](https://github.com/subframe7536/maple-font/assets/13695917/8bf1cc73-3c74-4a4d-b40c-46ce1dbf92db)

**Comment by Rlxzmdd** [comment]
刚发现中文字体是内嵌了 [资源圆体](https://github.com/CyanoHao/Resource-Han-Rounded)

**Comment by subframe7536** [comment]
#44

**Comment by subframe7536** [comment]
试试修改成这个
![image](https://github.com/subframe7536/maple-font/assets/78338239/a40ed0c7-8d23-44cc-b984-75ef6c8578bd)

**Comment by Rlxzmdd** [comment]
> 试试修改成这个 ![image](https://private-user-images.githubusercontent.com/78338239/313539587-a40ed0c7-8d23-44cc-b984-75ef6c8578bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3MzMwMjksIm5iZiI6MTcxMDczMjcyOSwicGF0aCI6Ii83ODMzODIzOS8zMTM1Mzk1ODctYTQwZWQwYzctOGQyMy00NGNjLWI5ODQtNzVlZjZjODU3OGJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDAzMzIwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlNTcwMzlkOGEwYjMwMWE1MjQwNWY2YzJhNmJhYmY5OWQ3MTI1ZTFjYjkwNThhNzMxNGM2OTg1NThlMjc2MDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1rbRD5eGYhNAcHFnDVMC0-J3mqAgsiMWgJ2B7vkEd5Y)

切换该方式成功解决问题

**Comment by Mapotato-Ma** [comment]
在vscode中，这个字体的所有斜体版本都不生效，需要设置什么吗？

**Comment by subframe7536** [comment]
@Mapotato-Ma 正常的啊 

https://github.com/user-attachments/assets/a500f0b8-3379-4dd8-82ab-bb1a0fd6cac5

**Comment by xiaotianxt** [comment]
<img width="1641" alt="Image" src="https://github.com/user-attachments/assets/e025602f-d066-4e9d-9e15-72bef8ef2b13" />

```markdown
| 功能类别                    | 英文名称                            | 描述                                                                                                  | 对应功能类型 (部分)                                          |
| :-------------------------- | :---------------------------------- | :---------------------------------------------------------------------------------------------------- | :--------------------------------------------------------------------- |
| **住宅区**                  | Residential Area                    | 提供居住功能为主的区域                                                                                | 住宅小区、公寓、宿舍、城中村等                                         |
| **商业与娱乐区**            | Commercial & Entertainment Area     | 提供购物、餐饮、休闲、娱乐、金融、商务服务等的区域                                                    | 购物中心、超市、餐厅、酒店、电影院、KTV、银行、市场、各类零售店铺等    |
| **就业/办公区**             | Employment/Office Area              | 提供工作、办公、科研、政府服务的场所                                                                  | 写字楼、办公园区、科技园、政府机构、企事业单位、研发中心等             |
| **工业/物流区**             | Industrial/Logistics Area           | 从事工业生产、仓储、物流活动的区域                                                                    | 工厂、工业园区、仓储中心、物流园、货运站等                             |
| **教育区**                  | Education Area                      | 提供教育、培训、科研（偏教学）功能的场所                                                              | 大中小学、幼儿园、培训机构、科研院所（部分）等                         |
| **公园及休闲区**            | Park & Leisure Area                 | 提供户外公共休憩、游览、运动、观赏等功能的开放空间                                                    | 公园、广场、绿地、景区、体育场馆（室外为主或大型）、河滨/海滨休闲带等  |
| **交通枢纽及连接走廊/接驳** | Transport Hub & Corridor / Transfer | 主要承担交通集散、换乘或作为重要连接通道的区域。在本研究赋值中，「接驳」功能基于交通站点POI优先赋予。 | 地铁站、公交站、轻轨站等接驳站点                                       |
| **其他**                    | Other                               | 功能难以归入以上类别，或数据源中标注为“其他”的区域。在本研究赋值中，其优先级较低。                    | 复合型建筑、部分多功能地块、未明确标注的区域、地图数据中的“其他”类别等 |
: 功能标签体系说明 {#tbl-func-description}
```

我发现这个折行还是有点问题，现在打开 word wrap 之后，折行已经不会溢出了，但是出现了提前折行的问题。

请参考上传的截图和对应的 markdown 文本。我选中了所有文本，这样可以更方便观察折行的位置。例如第 1 行的「描述」二字提前折断了。

**Comment by subframe7536** [comment]
似乎多半是标点的问题，这个在字体层面没法处理，只能由 VSCode 解决了

**Comment by subframe7536** [comment]
经排查，大概率是 #719 的原因，用 v8 分支的 `--cn-wenyuan` 构建已经可以解决了
