### ISSUE TITLE
[BUG] V7 Beta 10 Font height is abnormal and star symbol (*) is not aligned to center

### ISSUE THREAD

**Issue by dragove** [subframe7536/maple-font#174]
The left side of the image is a previous version of `Maple Mono SC NF` and the right side is `Maple Mono NF CN` previewed by `intellij idea`

The new version is higher and the star character is not centered.

![image](https://github.com/subframe7536/maple-font/assets/24190403/72fc05aa-3c00-4f34-b234-ee36fda6b05f)

**Comment by subframe7536** [comment]
Disable ligature

There is a ligature `*/` for comment and currently it has higher priority than `/=`

**Comment by subframe7536** [comment]
So `/=` maybe need to be reimplemented?

**Comment by dragove** [comment]
Thanks, I don't know that `*/` is implemented in the new version.

reimplement `/=` is better for me, but I don't know if others like this one.

**Comment by subframe7536** [comment]
tbh. `*/` also exists in V6, but it has lower priority than `/=`

**Comment by subframe7536** [comment]
I think all the combinations of operator and equal like `+=` `-=` `*=` `/=` `&=` `^=` `|=`  should keep in same style.

**Comment by dragove** [comment]
I've tested `+=` `-=` `*=` `/=` `&=` `^=` `|=` with `Jetbrains Mono`.  `/=` `&=` `^=` `|=` have ligature support, but `+=` `-=` `*=` don't.

![PixPin_2024-03-18_13-34-27](https://github.com/subframe7536/maple-font/assets/24190403/5520f071-a7b3-4d61-a2ac-96a581cdc70f)

**Comment by subframe7536** [comment]
v7-beta11 will be like
![image](https://github.com/subframe7536/maple-font/assets/78338239/c74a2870-04b6-4fde-b323-8301977649e4)
`|=` and `||=` have little changes to make `|` and `=` center

**Comment by subframe7536** [comment]
release in v7-beta11
