### ISSUE TITLE
Ligature display issues with "ll" in comments when using JetBrains IntelliJ IDEA

### ISSUE THREAD

**Issue by mingliao1994** [subframe7536/maple-font#175]
I have noticed that there is a display issue when the ligature "ll" appears in comments while using JetBrains IntelliJ IDEA. The rendering of the ligature in this context is incorrect and makes the comments difficult to read.

**Steps to Reproduce**:

1. Open a project in IntelliJ IDEA
2. Create a new file or open an existing one
3. Write a comment that includes the "ll" ligature (e.g., // null)
4. Observe that the "ll" ligature is displayed incorrectly
<img width="90" alt="image" src="https://github.com/subframe7536/maple-font/assets/69199252/f5f258af-4b83-4950-8b70-6094687d7982">

**Comment by subframe7536** [comment]
Correctly rendered in Windows
![image](https://github.com/subframe7536/maple-font/assets/78338239/c8162f21-b820-4da5-8926-d30b9d129b65)

What is your env?

**Comment by mingliao1994** [comment]
Apple M2 Mac mini, MacOS 14.3.1 @subframe7536

**Comment by subframe7536** [comment]
Does this issue exists in `Maple Mono`, `Maple Mono NF` and `Maple Mono NF CN`?

I have no Mac to test it, so please try to restart your IDE/OS or reinstall the font to reduce distractions

**Comment by mingliao1994** [comment]
<img width="383" alt="image" src="https://github.com/subframe7536/maple-font/assets/69199252/c1cc0df4-e7cf-4e15-a92c-74cba0ccc45c">
<img width="414" alt="image" src="https://github.com/subframe7536/maple-font/assets/69199252/4dcf524a-a252-470f-943f-b38fc4462463">
<img width="411" alt="image" src="https://github.com/subframe7536/maple-font/assets/69199252/0bb9d252-d940-4e8b-91ff-65a75afa47dc">
I think I found the issue. When I use Maple Mono NF CN Regular / Maple Mono NF Regular, it displays correctly. However, as soon as I switch to ExtraLight / Light , the display changes to what I mentioned before.

**Comment by subframe7536** [comment]
I find out the reason. Thanks

**Comment by subframe7536** [comment]
release in v7-beta11

**Comment by mingliao1994** [comment]
The issue has been resolved. Thank you so much for your quick response and hard work in addressing this problem.
