### ISSUE TITLE
[BUG] 斜体超出字符格

### ISSUE THREAD

**Issue by patricorgi** [subframe7536/maple-font#177]
下载了V7.0 Beta11里的MapleMono-nf-cn.zip

问题出在kitty终端模拟器下，可以看到斜体字超出字符格，在右侧被截断了

<img width="1475" alt="Screenshot2024-03-30 上午9 00 19" src="https://github.com/subframe7536/maple-font/assets/15998986/eb0b17b5-b26d-43ff-b55d-d7b4961d3cd9">
<img width="1476" alt="Screenshot2024-03-30 上午9 00 28" src="https://github.com/subframe7536/maple-font/assets/15998986/c9f2c4c6-781b-44b7-9d7d-2996f5a0a714">

**Comment by subframe7536** [comment]
能否测试 Jetbrains Mono 是否正常显示？

**Comment by patricorgi** [comment]
JetBrains Mono正常
<img width="1474" alt="Screenshot2024-03-30 下午7 01 45" src="https://github.com/subframe7536/maple-font/assets/15998986/8241f823-c97f-4cfa-98e4-263ad638f768">

**Comment by subframe7536** [comment]
能否测试一下这个是否正常显示
[MapleMono-Italic.zip](https://github.com/subframe7536/maple-font/files/14813782/MapleMono-Italic.zip)

**Comment by patricorgi** [comment]
比之前好一点，仔细看可以发现N和T正常了，就W还是被截了点
<img width="1378" alt="Screenshot2024-03-30 下午10 29 16" src="https://github.com/subframe7536/maple-font/assets/15998986/c386f1bb-94c5-4b28-9672-8829114ec5f6">

**Comment by subframe7536** [comment]
[MapleMono-Italic.zip](https://github.com/subframe7536/maple-font/files/14813970/MapleMono-Italic.zip)
试试这个，加大了偏移

**Comment by patricorgi** [comment]
好像跟前一个没区别，W还是被截了

<img width="1458" alt="Screenshot2024-03-31 上午9 53 55" src="https://github.com/subframe7536/maple-
font/assets/15998986/bdcc8afe-b46d-40d3-be24-45b0cd14396e">

**Comment by subframe7536** [comment]
偏移 80：[MapleMono-Italic.zip](https://github.com/subframe7536/maple-font/files/14816177/MapleMono-Italic.zip)
beta11是0，第一个是40，第二个是50

我身边没有linux设备，只能麻烦你测试了

**Comment by patricorgi** [comment]
又好了一些，不认真看的话截断看不太出来了，但还不算完美。不同字号之间也有一些细微的区别，某一个字号下W甚至没有截断（可能我肉眼已经看不出来了）
https://github.com/subframe7536/maple-font/assets/15998986/e9e79a00-4f18-4ed8-8956-25a685533424

**Comment by subframe7536** [comment]
理论上完美解决：[MapleMono-Italic.zip](https://github.com/subframe7536/maple-font/files/14819564/MapleMono-Italic.zip)
倾斜度减小到10，偏移120

**Comment by patricorgi** [comment]
<img width="1388" alt="Screenshot2024-04-01 上午8 10 27" src="https://github.com/subframe7536/maple-font/assets/15998986/ad1da038-9485-460c-90c1-6fe8d757b1dc">
<img width="1389" alt="Screenshot2024-04-01 上午8 10 58" src="https://github.com/subframe7536/maple-font/assets/15998986/38f7b918-1f5c-4601-aa7e-05cc54a61e59">

现在是左边被截断了😂

**Comment by patricorgi** [comment]
上面的斜体字符除了T可能是好的，其他字符在左侧都有一定程度的截断，120的偏移量可能太多了。

**Comment by patricorgi** [comment]
W堪称完美了，但是N左侧还是被截…
<img width="156" alt="Screenshot2024-04-01 上午8 35 17" src="https://github.com/subframe7536/maple-font/assets/15998986/0559ffc1-33f7-4539-833e-1693883a6bbf">
<img width="155" alt="Screenshot2024-04-01 上午8 35 22" src="https://github.com/subframe7536/maple-font/assets/15998986/6449d1fa-746b-41d9-9575-61a3e4423cb9">

再附上一个全字母的截图，除了A、M、N和X左侧截断比较明显，其他都十分完美了
<img width="398" alt="Screenshot2024-04-01 上午8 37 01" src="https://github.com/subframe7536/maple-font/assets/15998986/b9bf7c81-9410-4c0c-9597-619896549a9d">

**Comment by subframe7536** [comment]
感谢反馈，我可能需要调整一下字形

能否顺便测试一下 小写字母 是否存在这种情况？

**Comment by subframe7536** [comment]
仔细看了一下，很多是无法避免的字形问题。。。

如果方便的话还有一些需要测试的点：
- kitty是否支持自动fallback到斜体，即不安装斜体也能正确显示斜体，如果可以显示的话是否正常
- [Victor Mono](https://github.com/rubjo/victor-mono) / [Inconsolata](https://github.com/googlefonts/Inconsolata) / [RobotoMono](https://github.com/googlefonts/RobotoMono) 是否正常显示

最坏的结果是不推荐使用kitty😂

**Comment by subframe7536** [comment]
可以试一下beta12，偏移量改成了80

**Comment by patricorgi** [comment]
用了两天beta12，没发现什么明显问题👍👍
