### ISSUE TITLE
cv02 and cv03 are backwards in V7 (beta 12)

### ISSUE THREAD

**Issue by matthew-e-brown** [subframe7536/maple-font#178]
`option.png` from the README shows the alternate `i` as `cv02`, and the alternate `a` as `cv03`.

![](https://github.com/subframe7536/maple-font/blob/b0b7faf5b947b8a6420e3c6767b31c324381ff26/img/option.png?raw=true)

But, in V7.0 Beta 12, I see the opposite:

![Neither cv02 nor cv03 enabled](https://github.com/subframe7536/maple-font/assets/43387454/ec67476d-5a0d-483c-b58d-abdc1c72ed97)
![cv02 enabled, alternate 'a' displayed](https://github.com/subframe7536/maple-font/assets/43387454/ca3a3ba4-9f8a-43d1-b529-8f9f158c4df8)
![cv03 enabled, alternate 'i' displayed](https://github.com/subframe7536/maple-font/assets/43387454/a1897307-299a-42aa-9bec-a359803fbe67)

Either the setting in the font is backwards, or the image is backwards. It is also possible that this was an intentional change that simply hasn't had its documentation updated in the README yet.

**Comment by subframe7536** [comment]
Font features for v7 are documented at [variable branch](https://github.com/subframe7536/maple-font/tree/variable)

**Comment by matthew-e-brown** [comment]
Ah, of course, I didn't notice the README was different there as well. Thank you.
