### ISSUE TITLE
[BUG] V7 Beta12 版本在 VSCode 中显示异常

### ISSUE THREAD

**Issue by sena-nana** [subframe7536/maple-font#179]
我从V6版本的字体升级到V7 Beta12后，发现VSCode中字体显示粗细不一，难以辨认。降级到Beta11后显示正常与V6一致。

V7 Beta12：
![image](https://github.com/subframe7536/maple-font/assets/34237511/380d0d61-29a7-4576-8f08-9efaa2a32b06)

V7 Beta11&V6：
![image](https://github.com/subframe7536/maple-font/assets/34237511/5334e65a-cf79-4136-9360-1274cbfae933)

我尝试了修改VSCode 的字重设置，但并不奏效，字体大小设置为14，字重为normal400

**Comment by subframe7536** [comment]
现在默认使用的基础字体是未hint的版本，低分辨率的屏幕请使用hint的版本

**Comment by subframe7536** [comment]
试试v7-beta13

**Comment by sena-nana** [comment]
> 试试v7-beta13

看上去有效，谢谢
