### ISSUE TITLE
支持中文吗？

### ISSUE THREAD

**Issue by Attiv** [subframe7536/Maple-font#18]
gitee 上有 `MapleMono-SC-NF` ，这里貌似没有

**Comment by subframe7536** [comment]
...gitee传的快一点

**Comment by Attiv** [comment]
这里更新比 gitee 勤点，这里会提供带中文字体的吗？
还有个问题，qq 上设置的是 常规的，显示的很粗
![CleanShot 2022-08-24 at 15 57 05@2x](https://user-images.githubusercontent.com/15698129/186363645-5257f9cf-31be-4f72-9566-f7105ae6350c.png)
![CleanShot 2022-08-24 at 15 59 35@2x](https://user-images.githubusercontent.com/15698129/186363790-e9931023-1631-49d0-bc3a-36c170703646.png)

**Comment by subframe7536** [comment]
1. 很抱歉，不打算在这里提供，我最开始的版本是传中文的，但是当时上传了好几次才成功，而且时间很慢，于是就打算这里只发布不带中文的版本了，如果带来不方便请见谅
2. SC NF里面带的中文是500字重的汉仪正圆，会粗一些，但是在我的windows的IDE里刚刚好，正常的阅读字体推荐使用Maple UI，但是由于是机械变细，可能会有一些不完美的地方

**Comment by Attiv** [comment]
好的。
![CleanShot 2022-08-24 at 16 10 28@2x](https://user-images.githubusercontent.com/15698129/186366119-f3b6d4ad-d7eb-4ee4-8a86-095f7ae2829b.png)

**Comment by subframe7536** [comment]
...mac的字重识别问题我需要研究一下
