### ISSUE TITLE
Provide a Dockerfile for builds

### ISSUE THREAD

**Issue by ravshansbox** [subframe7536/maple-font#180]
Currently it's hard to build the font. I've tried both on mac and linux without any success. Would be great to have a docker build.

**Comment by ravshansbox** [comment]
Installing it is not hard, but in bare ubuntu it is not working

**Comment by subframe7536** [comment]
Is there any error log?

**Comment by ravshansbox** [comment]
Yeap, sure. Here it is
<img width="1319" alt="image" src="https://github.com/subframe7536/maple-font/assets/1499188/319ccaff-e56a-4e24-bff5-0beea0caf32c">

**Comment by ravshansbox** [comment]
What are the exact steps to do this in a fresh ubuntu?

**Comment by subframe7536** [comment]
hmm... I recommend to create a codespace on variable branch and build the font in it

**Comment by subframe7536** [comment]
> What are the exact steps to do this in a fresh ubuntu?

In my wsl using Debian, there is no extra step

**Comment by ravshansbox** [comment]
I'm pretty sure you need to install python and pip at least

**Comment by subframe7536** [comment]
In codespace:

1. `pip install foundrytools-cli`
2. `python build.py`

That's all

**Comment by ravshansbox** [comment]
Figured out what was missing, it's the `python-is-python3` package

**Comment by ravshansbox** [comment]
So basically, these are the required apt packages `python3` `python-is-python3` `fontforge` `python3-fontforge`

**Comment by subframe7536** [comment]
Thanks. Docs updated

**Comment by ravshansbox** [comment]
Also, if one wants to use docker for this, the param `--platform=linux/x86_64` should be included, otherwise on ARM Macs `linux/arm64` is chosen and some packages won't compile on it

**Comment by Gn3po4g** [comment]
i use this:
```dockerfile
FROM python
WORKDIR /app
COPY . .
RUN apt update && apt upgrade -y && apt install fontforge -y && pip install foundrytools-cli
CMD ["python", "build.py"]
```

**Comment by sirlan-ff00ff** [comment]
after reading trough this, and some of the other documentation stuff, I still can't run the build script

I'm on arch linux, but using a debian:testing distrobox (container) to trying building it, I tried installing all the stuff required, but it still complains about missing dependencies, and yes I've checked multiple times I installed everything from apt and pip

trying to running normally it complains that I don't have the `ttfautohint` package (when I do indeed have that installed)

```
 🌿 → python build.py
Traceback (most recent call last):
  File "/home/drag0n/git/Maple-font/source/build.py", line 7, in <module>
    from ttfautohint import ttfautohint
ModuleNotFoundError: No module named 'ttfautohint'

 🍂 → sudo apt install ttfautohint
ttfautohint is already the newest version (1.8.4-2).
```

trying to use a python venv and installing `ttfautohint-py`, it seems to go past it but complains that I don't have `python3-fontforge` installed (which, again, I have), and some other errors that I don't know what's from

```
[...]
/home/drag0n/git/Maple-font/source/./FontPatcher/font-patcher:427: SyntaxWarning: invalid escape sequence '\='
  message = "   Generated {} fonts\n   \===> '{}'".format(len(sourceFonts), outfile)
/home/drag0n/git/Maple-font/source/./FontPatcher/font-patcher:443: SyntaxWarning: invalid escape sequence '\='
  message = "   {}\n   \===> '{}'".format(sourceFont.fullname, outfile)
/home/drag0n/git/Maple-font/source/./FontPatcher/font-patcher:1944: SyntaxWarning: invalid escape sequence '\.'
  if re.match("\.ttc$", args.extension, re.IGNORECASE):
Nerd Fonts: FontForge module could not be loaded. Try installing fontforge python bindings [e.g. on Linux Debian or Ubuntu: `sudo apt install fontforge python3-fontforge`]
Traceback (most recent call last):
  File "/home/drag0n/git/Maple-font/source/build.py", line 276, in <module>
    generate_nerd_font(current_family, f)
  File "/home/drag0n/git/Maple-font/source/build.py", line 147, in generate_nerd_font
    nf_font = TTFont(nf_path)
              ^^^^^^^^^^^^^^^
  File "/home/drag0n/git/Maple-font/fontVenv/lib/python3.12/site-packages/fontTools/ttLib/ttFont.py", line 156, in __init__
    file = open(file, "rb")
           ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/drag0n/git/Maple-font/output/NF/MapleMonoNerdFontMono-Bold.ttf'

 🌿 → sudo apt install fontforge python3-fontforge
fontforge is already the newest version (1:20230101~dfsg-4).
python3-fontforge is already the newest version (1:20230101~dfsg-4).
```
