### ISSUE TITLE
[request] add underline like in iosevka

### ISSUE THREAD

**Issue by kaiphat** [subframe7536/maple-font#181]
Add underline the same position as text.
Currently in maple:
<img width="206" alt="image" src="https://github.com/subframe7536/maple-font/assets/53742299/5e6f9d65-cc16-4c6f-8e0b-63f33da0069b">

Iosevka:
<img width="206" alt="image" src="https://github.com/subframe7536/maple-font/assets/53742299/83ddae5e-b1bd-4420-b1e2-44b00297a38a">

**Comment by subframe7536** [comment]
I just follow Jetbrains Mono's spacing on underline

Jetbrains Mono:
![image](https://github.com/subframe7536/maple-font/assets/78338239/2aa699d7-7356-45f7-9879-931eb95a0c29)

Also, other popular fonts sink the underline as well

Fira Code:
![image](https://github.com/subframe7536/maple-font/assets/78338239/7f3a435e-5c96-4ee6-b6c5-e552f30f1dca)

Victor Mono:
![image](https://github.com/subframe7536/maple-font/assets/78338239/a2a49bb9-3321-46c1-a77c-8a5b50206a2c)

Roboto Mono:
![image](https://github.com/subframe7536/maple-font/assets/78338239/93d2061b-7e64-42a3-a0f2-086cba1c3e8e)

**Comment by kaiphat** [comment]
Yes, i understand, thank you. But it would be great option (at least for me).

**Comment by subframe7536** [comment]
On second thought, I'm not going to implement this feature.
