### ISSUE TITLE
In Jetbrains' production, the spacing of `Regular` or `Bold` weight will decrease when the size is 14 or 15.5

### ISSUE THREAD

**Issue by vladkryv** [subframe7536/maple-font#182]
I have tried several other fonts, this behavior is not reproduced with them.

OS: Windows 11
Font version: v7.0 Beta15
IntelliJ IDEA: 2024.1

![Screenshot_2024-05-05_13-24](https://github.com/subframe7536/maple-font/assets/83036866/d451a451-5bcf-462e-bab7-2442ec267637)

**Comment by subframe7536** [comment]
![recording](https://github.com/subframe7536/maple-font/assets/78338239/4e6bc991-5ffe-446e-ab9a-a4e1e4454924)

have you ever try to restart IDEA or Windows?

**Comment by vladkryv** [comment]
@subframe7536 now I checked, this happens with 14.0 font size; with 15.0 the character height changes a bit but the width is normal, with 16.0 everything is fine as you have in the video.

**Comment by subframe7536** [comment]
True. I can reproduce it. Mostly it is caused by IDEA's rendering strategy. I have tried many other fonts, they also have some weird transform between font sizes. 

However, what confusing me is the differences bewteen font weights. It seems that some "optimization" is effect when the font weight is regular or bold. Indeed, I have no idea to solve it currently.

**Comment by subframe7536** [comment]
![recording](https://github.com/subframe7536/maple-font/assets/78338239/18787e9b-2f5b-4e77-801e-b4900b2b9f35)

Find it out. You can test this version [source.zip](https://github.com/subframe7536/maple-font/files/15213086/source.zip)

**Comment by vladkryv** [comment]
> You can test this version [source.zip](https://github.com/subframe7536/maple-font/files/15213086/source.zip)
The problem with wide inter-character indentation is gone, but in this version there are a lot of artifacts, for example some letters are clearly thinner than others and so on, here are screenshots

1. regular v7.0 beta 15
2. regular source.zip
3. light v7.0 beta 15
4. light source.zip

![изображение](https://github.com/subframe7536/maple-font/assets/83036866/aa3bd470-c51c-4337-a43f-956dc09dd5ab)
![изображение](https://github.com/subframe7536/maple-font/assets/83036866/dced06ab-6f8b-4fa5-877c-06945e702ea8)
![изображение](https://github.com/subframe7536/maple-font/assets/83036866/7f672954-7810-438e-b9f2-27d46930cc1f)
![изображение](https://github.com/subframe7536/maple-font/assets/83036866/92e766c1-2bf9-44ce-899b-3c01d0fc0ca9)

**Comment by subframe7536** [comment]
This is caused by font hint, which is enabled by default in FontLab

**Comment by subframe7536** [comment]
Fix it by correct the font name table and change `usWeightClass` in static version
- `ExtraLight`: 200 -> 275
- `Thin`: 100 -> 250

**Comment by subframe7536** [comment]
release in v7.0-beta16
