### ISSUE TITLE
希腊字母小写和英文区分度不足

### ISSUE THREAD

**Issue by atauzki** [subframe7536/maple-font#184]
版本：7.0beta16
其实是从Jetbrains mono继承过来的问题，特别是这几个
```
Eta - Η η
Nu - Ν ν
Upsilon - Υ υ
Chi - Χ χ
```
vscode 上这样显示：
![image](https://github.com/subframe7536/maple-font/assets/19769843/1f0887b9-6348-4527-acee-d6514d2f8cd4)

**Comment by subframe7536** [comment]
是的，这些是直接复用的

这方面不太了解，有没有比较好的字体？

**Comment by atauzki** [comment]
[Hack](https://github.com/source-foundry/Hack/releases)
[Inconsolata LGC](https://github.com/MihailJP/Inconsolata-LGC)

**Comment by subframe7536** [comment]
![image](https://github.com/subframe7536/maple-font/assets/78338239/c3fa2b37-3133-49f8-b5bf-bc470ed7f58f)
这样？

**Comment by atauzki** [comment]
chi的弧度可以再大点

**Comment by subframe7536** [comment]
![image](https://github.com/subframe7536/maple-font/assets/78338239/f8e64ed2-f128-4373-b1a4-cfb398aaefab)
换了一种弯曲方式

**Comment by atauzki** [comment]
实际上不是这么弯的，应该是下面这样，比较接近手写的方式
![images](https://github.com/subframe7536/maple-font/assets/19769843/8d144049-2b3e-40f5-b144-802e828ccede)

**Comment by subframe7536** [comment]
![image](https://github.com/subframe7536/maple-font/assets/78338239/70d86dd0-7b78-44cf-9a28-89afdb8af98d)
其他的也优化了一些

**Comment by subframe7536** [comment]
![image](https://github.com/subframe7536/maple-font/assets/78338239/0e04cb1e-0261-4fd6-ba57-b9848c40e3d8)

**Comment by subframe7536** [comment]
![image](https://github.com/subframe7536/maple-font/assets/78338239/2e0de2ad-6cce-4217-b13f-d043f0544722)

**Comment by atauzki** [comment]
这样就行了

**Comment by atauzki** [comment]
`ν` 的斜体还是没区别开来
![图片](https://github.com/subframe7536/maple-font/assets/19769843/6673ceea-9f03-4c99-b20a-a8d71e3c8507)

**Comment by subframe7536** [comment]
[fix-v.zip](https://github.com/subframe7536/maple-font/files/15286368/fix-v.zip)
试试这个最新的

**Comment by atauzki** [comment]
这个可以了

**Comment by subframe7536** [comment]
release in v7,0-beta17
