### ISSUE TITLE
[bug?] 斜体下字母`a`与`l`似乎应该连起来？

### ISSUE THREAD

**Issue by Miuzarte** [subframe7536/maple-font#185]
version: [V7.0 Beta16](https://github.com/subframe7536/maple-font/releases/tag/v7.0-beta16)/[MapleMono-NF-CN.zip](https://github.com/subframe7536/maple-font/releases/download/v7.0-beta16/MapleMono-NF-CN.zip)

`c`都连上了`a`却没连有点奇怪

jetbrains GoLand:
![image](https://github.com/subframe7536/maple-font/assets/66856838/51a5ebb9-a40b-42ab-acb2-8f1724a7d3cf)
![image](https://github.com/subframe7536/maple-font/assets/66856838/d8f97dcc-a8df-4953-ac69-ff7694e0aef4)
![image](https://github.com/subframe7536/maple-font/assets/66856838/3dcc8ada-be87-419e-a95a-5372770cc455)

vscode:
![image](https://github.com/subframe7536/maple-font/assets/66856838/c25aaecf-187d-4ecd-9e0a-d2b9b6fe7ab3)
![image](https://github.com/subframe7536/maple-font/assets/66856838/d069dba4-e92b-43e7-a3d7-e6a86744d742)
![image](https://github.com/subframe7536/maple-font/assets/66856838/9cdce7f0-64fc-4e32-8a54-c6752cbf73f3)

另外可以的话能不能有个单独的版本让字母不连字（只想要符号有连字），稍微有点影响可读性

**Comment by subframe7536** [comment]
关闭的话需要启用特性 ss01

另外al xl ul这些都考虑过，感觉不太行

**Comment by subframe7536** [comment]
考虑后面改成非默认的

**Comment by subframe7536** [comment]
经过考虑，目前不打算改成非默认的

1. 非默认的目前实现起来改动较大
2. l相关的连笔是和花体l绑定的，开启ss01后不会启用

**Comment by subframe7536** [comment]
release in v7.0-beta17
