### ISSUE TITLE
Fullwidth ellipsis and em dash in Chinese font

### ISSUE THREAD

**Issue by abs-c** [subframe7536/maple-font#188]
Considering that ellipsis (U+2026) and em dash (U+2014) are rarely used in programming languages or in English, but appear a lot in Chinese texts, is it possible to make them fullwidth in the Chinese versions?

考虑到省略号「…」和长横线（半破折号？）「—」在编程及英文文本中不常出现，而在中文文本中较为常见，或许可以在中文版本中将它们按照中文习惯改为一个中文字符（两个英文字符）的宽度？

（可以预见的一个问题是终端中的显示错误，更纱黑体似乎为此区分了 Mono 和 Terminal 版本。）

**Comment by subframe7536** [comment]
似乎更适合通过字体特性实现

下版本加一个 `cv98`

**Comment by subframe7536** [comment]
![recording](https://github.com/subframe7536/maple-font/assets/78338239/3a4e0850-95d2-4b52-91ce-974dcad9cd06)

**Comment by subframe7536** [comment]
release in v7.0-beta19
