### ISSUE TITLE
lower-case ss02 [debug], [error], [info]... ligatures in v7

### ISSUE THREAD

**Issue by okkdev** [subframe7536/maple-font#189]
<img width="97" alt="image" src="https://github.com/subframe7536/maple-font/assets/20144629/c354adbd-f354-4353-a46c-547454cd783e">

I would love the option back for lower-case [error], [info] and co ligatures.

**Comment by subframe7536** [comment]
It is great idea to make it as a font feature!

I will implement it like "arbitrary mode" in `ss02`. Something like `[Info]` or `[dEbUG]` will also effect

**Comment by subframe7536** [comment]
After consideration, I will implement it in `ss03`.

`ss02` will be the stylesets for splited `==`

**Comment by subframe7536** [comment]
release in v7.0-beta19
