### ISSUE TITLE
ligatures doesn't seem to work on macos

### ISSUE THREAD

**Issue by PatentLobster** [subframe7536/Maple-font#19]
Hey, it seems that the ligatures doesn't work on my machine with iterm2

**Comment by subframe7536** [comment]
well, i dont't a Mac so i can't test whether it works on iterm2 and it works in my windows terminal...maybe restart your Mac will help? if not, please attach a image

**Comment by PatentLobster** [comment]
Sorry it seems to be zsh specific, not related to the font.
https://github.com/zsh-users/zsh-syntax-highlighting/issues/750
