### ISSUE TITLE
Nerd图标大小不一致无法对齐

### ISSUE THREAD

**Issue by CarterLi** [subframe7536/maple-font#191]
![image](https://github.com/subframe7536/maple-font/assets/6134068/9bc7be0c-fc6f-418f-9a44-7e0a5adcc6f2)

有的宽有的窄，排成一竖排时感觉有些难看

对比原生

![image](https://github.com/subframe7536/maple-font/assets/6134068/006f5917-1e30-4453-9811-df12b367ab29)

**Comment by subframe7536** [comment]
https://github.com/subframe7536/maple-font/blob/54d8dc7a99bf6fe444a346fd41beca58594c0501/build.py#L31-L32

目前解决方案：自行编译，或者使用V6

后续会提供一个版本
