### ISSUE TITLE
[REQUEST] Glyphs for right-angled arrows (↰, ↱, ↲, ↳)

### ISSUE THREAD

**Issue by matthew-e-brown** [subframe7536/maple-font#193]
The `↰↱↲↳` symbols are not currently provided by this font. The fact that they aren't means that they don't display with the correct width when used in in-code diagrams (they're narrower than the rest of the font):

![Several instances of the `↳` symbol on the same line result in the cursor appearing a few pixels to the side further down the line.](https://github.com/subframe7536/maple-font/assets/43387454/58e9d2d2-28ae-4440-82f0-cdde920471c0)
(V7 Beta17 used in screenshot)

It would be nice if these glyphs were provided by the font.

(of course, it would be nice if even _more_ of the fancy arrows were supported, but that's a much bigger request. I think these four are simple enough that it _probably_ isn't too big of an ask. 🙂)

I know it was mentioned previously that the goal for supported characters is [to use the supported range of JetBrains Mono](https://github.com/subframe7536/maple-font/issues/151#issue-2055099180), and that JetBrains Mono [does not currently support these glyphs](https://github.com/JetBrains/JetBrainsMono/wiki/List-of-supported-symbols). Both could certainly benefit from these extra symbols, but this is the one I use, so this is the place I've opened the request. 😄

**Comment by matthew-e-brown** [comment]
You work quick! I just encountered another one -- what are the chances we could also see glyphs for `⇄` and `⇆`? 🙏🏻🙂

**Comment by subframe7536** [comment]
release in v7.0-beta19
