### ISSUE TITLE
[BUG] ss03 inconsistent

### ISSUE THREAD

**Issue by okkdev** [subframe7536/maple-font#194]
ss03 is not working correctly.

`todo` and `debug` seem to work as expected.
`error` is completely broken and the ligature removes `[e`.
`info` requires a capital `I`.
`warn` requires a capital `A`.
`fatal` needs both capital `A`s.
`fixme` needs a capital `I`.

I added what I typed in brackets `()` for the ligatures.
![image](https://github.com/subframe7536/maple-font/assets/20144629/4e850795-a7ce-4562-b0fa-211340f3bb49)
![image](https://github.com/subframe7536/maple-font/assets/20144629/80ee7fd1-35f7-46db-85be-d39cd1462f15)
![image](https://github.com/subframe7536/maple-font/assets/20144629/88636c00-7de9-45f7-b282-4e1ae96ca157)

I'm using Kitty terminal.

**Comment by subframe7536** [comment]
some ai-generated error in opentype feature file😰

**Comment by subframe7536** [comment]
[TTF.zip](https://github.com/subframe7536/maple-font/files/15436811/TTF.zip)
this one should properly render the tag

**Comment by okkdev** [comment]
Yes, with this one it works as expected. :)

**Comment by subframe7536** [comment]
release in v7.0-beta20
