### ISSUE TITLE
"#" 号显示不符合预期

### ISSUE THREAD

**Issue by zoze0** [subframe7536/maple-font#195]
![截图_选择区域_20240525170933](https://github.com/subframe7536/maple-font/assets/20562449/84201fa3-4073-458c-a6aa-768d7b002822)
![截图_选择区域_20240525171212](https://github.com/subframe7536/maple-font/assets/20562449/59eedaa6-473a-4d82-b749-74892677aa39)

在文本编辑器，vscode, 终端都是同样的。
版本： [V7.0 Beta19](https://github.com/subframe7536/maple-font/releases/tag/v7.0-beta19) ，[V7.0 Beta18](https://github.com/subframe7536/maple-font/releases/tag/v7.0-beta18)
其他版本未安装

**Comment by subframe7536** [comment]
是的，部分字形进行了修改

**Comment by subframe7536** [comment]
v6的`#`在低分屏下显示不太好，所以考虑在v7去除间隔

**Comment by zoze0** [comment]
还是更喜欢这样的“#” 怎么办 ， 只能v6吗
![截图_选择区域_20240525201054](https://github.com/subframe7536/maple-font/assets/20562449/b4df70ad-7927-48eb-9892-76569650e48e)

**Comment by zoze0** [comment]
> v6的`#`在低分屏下显示不太好，所以考虑在v7去除间隔

我觉得显示不太好一种可能是字形有点粗，在低分屏上坨在一起了。 regular的像其他字体的加粗，light像其他字体的regular.  我在VSCODE上就是用的Light感觉刚刚好

**Comment by subframe7536** [comment]
长度也有关系，四个角上的短线会变得更短一些，导致横/竖两条线不一样长

**Comment by falood** [comment]
抱歉挖出来 24 年的 issue，同样很喜欢 v6 版的 `#`。
麻烦问下会不会考虑把这个特性也做为一个可选项加入到后续的版本中？

**Comment by subframe7536** [comment]
> 抱歉挖出来 24 年的 issue，同样很喜欢 v6 版的 `#`。
> 麻烦问下会不会考虑把这个特性也做为一个可选项加入到后续的版本中？

抱歉回复晚了，想了想还是可以考虑一下的
