### ISSUE TITLE
[V7-Beta20] kitty help

### ISSUE THREAD

**Issue by RicardoRamirezR** [subframe7536/maple-font#198]
Hi there,

I'm using Maple on Kitty terminal on MacOS, this is the kitty.conf part of font:
```js
font_family Maple Mono NF
bold_font auto
italic_font auto
bold_italic_font auto
font_size 20
adjust_line_height 200%
font_features MapleMono-NF-ExtraLightItalic +cv01 +cv02 +cv03 +cv04 +ss01 +ss02 +ss03 +ss04 +ss05 +zero
```
I set all character variants and all stylistic sets, those are the characters:

<img width="728" alt="Maple" src="https://github.com/subframe7536/maple-font/assets/6526545/ed479ba7-7db9-463e-80d1-a8a32a9e5fe1">  

Any clues for adjustment to get it properly configured would be very appreciate

**Comment by subframe7536** [comment]
Try to use `font_features MapleMono-NF +cv01 +cv02 +cv03 +cv04 +ss01 +ss02 +ss03 +zero` instead

**Comment by RicardoRamirezR** [comment]
Thank you @subframe7536,

I did:

`font_features MapleMono-NF +cv01 +cv02 +cv03 +cv04 +ss01 +ss02 +ss03 +zero`

and got:


<img width="708" alt="Screenshot 2024-06-06 at 8 03 55 AM" src="https://github.com/subframe7536/maple-font/assets/6526545/eee35ef7-f83d-49c6-a471-986170186a3a">

**Comment by RicardoRamirezR** [comment]
😭

<img width="714" alt="Screenshot 2024-06-06 at 8 25 09 AM" src="https://github.com/subframe7536/maple-font/assets/6526545/2193286c-abcd-4fbd-b54a-6b985cefd41e">

**Comment by subframe7536** [comment]
My bad. After reading the Kitty config doc, I think the correct way is

```
font_features MapleMono-NF-Regular +cv01 +cv02 +cv03 +cv04 +ss01 +ss02 +ss03 +zero
```

**Comment by RicardoRamirezR** [comment]
@subframe7536 that's almost make the trick, ss01 is failing

<img width="805" alt="Screenshot 2024-06-06 at 9 32 47 AM" src="https://github.com/subframe7536/maple-font/assets/6526545/4403bc96-5a5d-4305-adf9-74ddb9839119">

**Comment by subframe7536** [comment]
some font features are changed. see in [V7 Doc](https://github.com/subframe7536/maple-font/tree/variable?tab=readme-ov-file#features)

**Comment by subframe7536** [comment]
Thanks for your love. I am writing a website for this font and will add some guides for font features and maybe Kitty config.

**Comment by RicardoRamirezR** [comment]
I ended up with `font_features MapleMono-NF-Regular +zero +cv03 +cv04 +ss03`
