### ISSUE TITLE
Why this character is shown in Neovim

### ISSUE THREAD

**Issue by RicardoRamirezR** [subframe7536/maple-font#199]
Hi there,

Does anyone have an idea why this 契 appears in Neovim and what it says?

![Screenshot 2024-06-05 at 10 20 01 AM](https://github.com/subframe7536/maple-font/assets/6526545/774e8104-30d7-4830-97be-9cc36b9879a3)

**Comment by subframe7536** [comment]
If you are using `Maple Mono NF`, there is no glyph on 契(`\u5951`) in the font

**Comment by subframe7536** [comment]
What the symbol in this position was supposed to be? The collapse icon?

**Comment by atauzki** [comment]
maybe your configuration is using nerd font v2，but it is  outdated and conflicts with some chinese chars，and maple uses nerd font v3

**Comment by RicardoRamirezR** [comment]
Hi @subframe7536 with JetBrainsMono Nerd Font

<img width="513" alt="JetBrainsMono Nerd Font" src="https://github.com/subframe7536/maple-font/assets/6526545/002cd43f-19e0-45fb-acf9-9b2c7e669ee7">

**Comment by RicardoRamirezR** [comment]
Hi @atauzki, i'm using ```nvim-tree/nvim-web-devicons``` which uses Nerd Font 3

**Comment by subframe7536** [comment]
> Hi @subframe7536 with JetBrainsMono Nerd Font
> 
> <img alt="JetBrainsMono Nerd Font" width="513" src="https://private-user-images.githubusercontent.com/6526545/337270913-002cd43f-19e0-45fb-acf9-9b2c7e669ee7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2ODUxODIsIm5iZiI6MTcxNzY4NDg4MiwicGF0aCI6Ii82NTI2NTQ1LzMzNzI3MDkxMy0wMDJjZDQzZi0xOWUwLTQ1ZmItYWNmOS05YjJjN2U2NjllZTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDZUMTQ0MTIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWZiMDlmYjAyOGUxMTYzOWY1OTQyY2FlNDY4MGE3NDU4Y2VmNzJjMDJhMTU4YTE2MTFhNzE1OGJhMTdmMjI5OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.nxQ2gkUedVqYiYQeDH4JjZwE92LcP7HVeHh-A_QGsvk">

What is the unicode of the icon? Is it still `\u5951` ?

**Comment by atauzki** [comment]
So there is another possibility.
https://www.compart.com/en/unicode/U+F909
![image](https://github.com/subframe7536/maple-font/assets/19769843/d9ee66c7-9880-48c3-8b48-16d624585ef7)

**Comment by subframe7536** [comment]
It seems that there is no wrong with the font, so close it.
