### ISSUE TITLE
Italic a and greek alpha undistinguishable

### ISSUE THREAD

**Issue by atauzki** [subframe7536/maple-font#201]
Just like Jetbrains Mono [#684](https://github.com/JetBrains/JetBrainsMono/issues/684)
![image](https://github.com/subframe7536/maple-font/assets/19769843/7d2ede99-c7f0-41eb-8909-25049378cc04)

**Comment by subframe7536** [comment]
v7.0-beta21
```
English
a
\alpha
α
```
![image](https://github.com/subframe7536/maple-font/assets/78338239/526a54dd-e0b6-44c3-b22e-d106ce6cd1c9)

**Comment by atauzki** [comment]
That's my wrong. I misspelled the letter on the last line.
