### ISSUE TITLE
V7版本没有SC-NF了吗

### ISSUE THREAD

**Issue by RabbitHareLu** [subframe7536/maple-font#205]
很高兴看到作者还在维护该字体, 我特别喜欢这个字体;
今天我尝试在windows11下使用了V7的beta21的NF-CN, 发现没有V6.4的SC-NF的那种圆润感, 我不知道SC-NF和NF-CN的区别是什么, 希望有好心人能解答一下, 还是说在V7正式版发布的时候会有SC-NF版本出现

**Comment by subframe7536** [comment]
v7是为了根据 Jetbrains Mono 改的，一定程度上会受到原字形的影响，但是从代码的整体观感上来说更好了，整体的风格是刚中带柔，中文部分的资源圆体也是同样的思路

**Comment by Explorer-cc** [comment]
@subframe7536 请问是否有何处说明「Maple Mono SC NF」和「Maple Mono NF CN」的区别。

在最新版本(v7.x)的 release 中，似乎已经无法下载到「Maple Mono SC NF」。

> 今天我尝试在windows11下使用了V7的beta21的NF-CN, 发现没有V6.4的SC-NF的那种圆润感

> v7是根据 Jetbrains Mono 改的

言外之意是从 v6.x 到 v7 的版本更新中， 「SC NF」已经变为「NF CN」?

**Comment by subframe7536** [comment]
> 言外之意是从 v6.x 到 v7 的版本更新中， 「SC NF」已经变为「NF CN」?

是的

**Comment by Explorer-cc** [comment]
> > 言外之意是从 v6.x 到 v7 的版本更新中， 「SC NF」已经变为「NF CN」?
> 
> 是的

谢谢。我同时还有点小好奇，为何「NF」的位置从「SC」之后变到了「CN」之前，这对我记住这个 「family name」 造成了小小的困扰（雾）。

**Comment by subframe7536** [comment]
因为约定的命名规范就是把 CN 放到最后的。。。

Maple Mono
Maple Mono NF
Maple Mono NF CN

**Comment by Explorer-cc** [comment]
> 因为约定的命名规范就是把 CN 放到最后的。。。
> 
> Maple Mono Maple Mono NF Maple Mono NF CN

感谢解释~
