### ISSUE TITLE
V6.4 在开启连字功能后的 VSCode 上缺少部分连字符

### ISSUE THREAD

**Issue by onsummer** [subframe7536/maple-font#206]
感谢作者辛勤付出，努力安利本字体中~个人也用了几年了

环境说明：

- 字体版本：MapleMono-SC-NF 6.4
- 操作系统：Windows 11
- VSCode版本：1.90
- 字体设置：`"editor.fontFamily": "'Maple Mono SC NF', 'Fira Code'"`，`"editor.fontLigatures": true`

截图如下：

![image](https://github.com/subframe7536/maple-font/assets/26168955/56d761b0-e02c-46ca-8892-706ce5a0658b)

不知道是本身就没有还是我的设置有问题，特来咨询（btw，可以开启 GitHub 的 Discussion 模块，方便讨论）

**Comment by subframe7536** [comment]
感谢你的认可

在 v6.4 中可以开启 font features：
```
"editor.fontLigatures": "'calt', 'ss01', 'ss04'"
```

在 v7.0 中，这些连字是默认开启的，你可以尝试一下，现在已基本稳定

**Comment by onsummer** [comment]
@subframe7536 感谢回复，期待 7.0
