### ISSUE TITLE
Letter Ü is wrongly mapped to Û

### ISSUE THREAD

**Issue by asciini** [subframe7536/maple-font#207]
<img width="850" alt="Bildschirmfoto 2024-07-03 um 08 24 30" src="https://github.com/subframe7536/maple-font/assets/50045986/7e5d797e-2cce-461e-9702-03fe2e3d5581">

**Comment by asciini** [comment]
Especially problematic for usage of the font with german text

**Comment by subframe7536** [comment]
This should be fixed in V7

**Comment by asciini** [comment]
Thanks! I will check out the beta, looking forward to the stable release
