### ISSUE TITLE
iTerm2 中使用 p10k powerline 显示效果与预期不同

### ISSUE THREAD

**Issue by sbilly** [subframe7536/Maple-font#21]
iTerm2 中使用使用 p10k 推荐的 MesloLGS NF 字体显示效果不同

使用 MesloLGS NF 字体时

<img width="191" alt="image" src="https://user-images.githubusercontent.com/123563/186558403-e83b5281-a24f-4cab-a753-0ae8ea114c35.png">

使用 Maple Mono SC NF 字体时

<img width="197" alt="image" src="https://user-images.githubusercontent.com/123563/186558546-85fe31cd-1892-4280-91d0-4eb3b3564920.png">

**Comment by subframe7536** [comment]
能否把这一行发过来，我看一下

**Comment by sbilly** [comment]
<img width="1283" alt="image" src="https://user-images.githubusercontent.com/123563/187036745-0d222a3f-592d-4713-b4e6-27f96dcda40e.png">

**Comment by subframe7536** [comment]
我的表达有误...我需要知道这一行的unicode是多少

**Comment by sbilly** [comment]
怎么看？？

**Comment by sbilly** [comment]
怎么看？？

**Comment by subframe7536** [comment]
那一行复制下来

**Comment by sbilly** [comment]
╭─    ~/Downloads/Source.Codes/github.com/v2ray-core    master ▓▒░                                                                    ░▒▓ ✔  22:24:33 

这样？

**Comment by subframe7536** [comment]
抱歉，字体里确实没有这些字符，下一版加上

**Comment by subframe7536** [comment]
移动到 #36
