### ISSUE TITLE
中文字间距有点大

### ISSUE THREAD

**Issue by Cesar-Chang** [subframe7536/maple-font#211]
![img_v3_02cj_614f54c7-8ba7-40da-8d48-ec260cd94bhu](https://github.com/subframe7536/maple-font/assets/17882131/11588b45-23a6-467b-9090-3c342cb0dc3b)
ide 上看中文字间距显得有点宽

**Comment by subframe7536** [comment]
这是一个权衡后的选择：

中文一个字符单位宽高都是1000，英文一个字符单位宽度600，高度730

编程作为一个英文多中文少的场景，需要优先满足英文的阅读体验。像更纱黑体这种压缩英文宽度（500）满足中文字符宽度的字体，在编码的场景阅读起来会比较费力（对我而言）

因此只能调整中文字符，但是这里又有一个权衡：放大和加大间距。放大中文字符会导致英文字体过小，加大间距会看起来比较奇怪

近两年的使用下来，最终选择了加大间距：
1. 放大会让中文字符在字符串或者注释中十分突出
2. 加大间距可以在阅读时加以区分，但又不会显得突兀，相对更能维持行高，还可以更好地提示你这是等宽字体

![image](https://github.com/user-attachments/assets/3b288830-06cf-441e-862e-49d6fdd729a3)

因此，得到了这么一个看起来比较奇怪，但是阅读效率相对高一些的字体

如果想要减小间距，可以通过[自定义构建](https://github.com/subframe7536/maple-font/blob/variable/README_CN.md#%E7%BC%A9%E5%B0%8F%E4%B8%AD%E6%96%87%E5%AD%97%E4%BD%93%E7%9A%84%E9%97%B4%E8%B7%9D)实现

**Comment by Cesar-Chang** [comment]
@subframe7536 感谢回复。懂了，那以后就尽量写英文注释了 hh

**Comment by eqfae** [comment]
> @Leroy-X 说实话，现在的中文字体细看很丑。。。因为需要 OFL + 圆体，没得选才用资源圆体的。。。[之前的一些吐槽](https://github.com/subframe7536/maple-font/releases/tag/v7.0-beta11)
> 
>     * 如果不在意2：1，可以只安装 Maple Mono NF，然后用 Fallback 字体加载中文
> 
>     * 如果在意2：1，可以用更纱黑体
> 
> 
> 补充一下丑的原因： ![](https://private-user-images.githubusercontent.com/78338239/357069659-3d2bf778-c59e-47cf-8321-7c31b1d4cb57.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwMTU4NDAsIm5iZiI6MTcyNTAxNTU0MCwicGF0aCI6Ii83ODMzODIzOS8zNTcwNjk2NTktM2QyYmY3NzgtYzU5ZS00N2NmLTgzMjEtN2MzMWIxZDRjYjU3LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDEwNTkwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0YTJjOWZhNGQ4MTUyZGEyY2QyMzM4MDE4YmYwNWMwNDBmMWQ3ZjczZWJjM2FkYTY3Y2IxYjFjZGJmZmU0ZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S2j38oXGbYGz5wuc-IiIcxH6lAZqiBjF7EAyutvKjuA) [ ![357069659-3d2bf778-c59e-47cf-8321-7c31b1d4cb57.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwMTU4NDAsIm5iZiI6MTcyNTAxNTU0MCwicGF0aCI6Ii83ODMzODIzOS8zNTcwNjk2NTktM2QyYmY3NzgtYzU5ZS00N2NmLTgzMjEtN2MzMWIxZDRjYjU3LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDEwNTkwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0YTJjOWZhNGQ4MTUyZGEyY2QyMzM4MDE4YmYwNWMwNDBmMWQ3ZjczZWJjM2FkYTY3Y2IxYjFjZGJmZmU0ZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S2j38oXGbYGz5wuc-IiIcxH6lAZqiBjF7EAyutvKjuA](https://private-user-images.githubusercontent.com/78338239/357069659-3d2bf778-c59e-47cf-8321-7c31b1d4cb57.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwMTU4NDAsIm5iZiI6MTcyNTAxNTU0MCwicGF0aCI6Ii83ODMzODIzOS8zNTcwNjk2NTktM2QyYmY3NzgtYzU5ZS00N2NmLTgzMjEtN2MzMWIxZDRjYjU3LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDEwNTkwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0YTJjOWZhNGQ4MTUyZGEyY2QyMzM4MDE4YmYwNWMwNDBmMWQ3ZjczZWJjM2FkYTY3Y2IxYjFjZGJmZmU0ZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S2j38oXGbYGz5wuc-IiIcxH6lAZqiBjF7EAyutvKjuA) ](https://private-user-images.githubusercontent.com/78338239/357069659-3d2bf778-c59e-47cf-8321-7c31b1d4cb57.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwMTU4NDAsIm5iZiI6MTcyNTAxNTU0MCwicGF0aCI6Ii83ODMzODIzOS8zNTcwNjk2NTktM2QyYmY3NzgtYzU5ZS00N2NmLTgzMjEtN2MzMWIxZDRjYjU3LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDEwNTkwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0YTJjOWZhNGQ4MTUyZGEyY2QyMzM4MDE4YmYwNWMwNDBmMWQ3ZjczZWJjM2FkYTY3Y2IxYjFjZGJmZmU0ZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S2j38oXGbYGz5wuc-IiIcxH6lAZqiBjF7EAyutvKjuA) [ ](https://private-user-images.githubusercontent.com/78338239/357069659-3d2bf778-c59e-47cf-8321-7c31b1d4cb57.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwMTU4NDAsIm5iZiI6MTcyNTAxNTU0MCwicGF0aCI6Ii83ODMzODIzOS8zNTcwNjk2NTktM2QyYmY3NzgtYzU5ZS00N2NmLTgzMjEtN2MzMWIxZDRjYjU3LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDEwNTkwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0YTJjOWZhNGQ4MTUyZGEyY2QyMzM4MDE4YmYwNWMwNDBmMWQ3ZjczZWJjM2FkYTY3Y2IxYjFjZGJmZmU0ZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S2j38oXGbYGz5wuc-IiIcxH6lAZqiBjF7EAyutvKjuA)

能发汉仪正圆的可变版本吗 手上最新的是内置在中兴手机的汉yi圆体但不是可变 我自己合并 虽然不会搞中英文2:1

**Comment by subframe7536** [comment]
> 能发汉仪正圆的可变版本吗 手上最新的是内置在中兴手机的汉yi圆体但不是可变 我自己合并 虽然不会搞中英文2:1

不能，因为有版权问题，国内字体厂商发布的所有字体的协议都不支持二改

**Comment by eqfae** [comment]
> > 能发汉仪正圆的可变版本吗 手上最新的是内置在中兴手机的汉yi圆体但不是可变 我自己合并 虽然不会搞中英文2:1
> 
> 不能，因为有版权问题，国内字体厂商发布的所有字体的协议都不支持二改
> 
> 另外，汉仪正圆的可变字体根本没有流出，没法做

嗯 我现在用中兴圆体静态的 这个中英文2:1那间距我受不了 在阅读app尝试了 本来等苹方可变字体 圆体才是真的香

**Comment by subframe7536** [comment]
> 嗯 我现在用中兴圆体静态的 这个中英文2:1那间距我受不了 在阅读app尝试了 本来等苹方可变字体 圆体才是真的香

每个字体都有适合的使用场景，比如 得意黑 只适合在标题中使用。Maple Mono NF CN 只适合在多英文、少中文的代码环境中使用，别的场景请使用其他使用

**Comment by KkemChen** [comment]
雀食！ 英文还是好看的，就是 中文间距 难蚌。

**Comment by subframe7536** [comment]
> 雀食！ 英文还是好看的，就是 中文间距 难蚌。

现在配置里多了一个narrow选项，可以减小间距，但是会破坏2：1，而且支持很不完善，详见 #249

**Comment by KkemChen** [comment]
> > 雀食！ 英文还是好看的，就是 中文间距 难蚌。
> 
> 现在配置里多了一个narrow选项，可以减小间距，但是会破坏2：1，而且支持很不完善，详见 #249

等完善了 踢我一下。我先用不带中文的，然后配合思源黑体先，感觉还行

**Comment by subframe7536** [comment]
发布了一个紧凑的版本 `MapleMono-CN.ttf`，可以测试一下
https://github.com/subframe7536/maple-font/releases/tag/v7.0-beta28.1

**Comment by subframe7536** [comment]
用 `fonttools` 的 `ttx` 工具将 `OS/2` 表的 `xAvgCharWidth` 调整为等宽字体的大小

**Comment by subframe7536** [comment]
是可以再小一些，但是这样英文就太窄了。现在的版本我用下来就觉得很窄了，之后大概率弃了

**Comment by subframe7536** [comment]
> > 但是这样英文就太窄了。
> 
> 可以只修改中文字体的间距吗，我对2:1没要求，或是只缩放中文字体

抱歉，我不打算多做一个版本

你需要的是字体合并工具

**Comment by subframe7536** [comment]
可以自行构建，`cn.narrow` 设置为 true

**Comment by subframe7536** [comment]
理论上可以在网页上实现，目前有计划在这方面尝试

**Comment by fengsuiyvmin** [comment]
> 这是一个权衡后的选择：
> 
> 中文一个字符单位宽高都是1000，英文一个字符单位宽度600，高度730
> 
> 编程作为一个英文多中文少的场景，需要优先满足英文的阅读体验。像更纱黑体这种压缩英文宽度（500）满足中文字符宽度的字体，在编码的场景阅读起来会比较费力（对我而言）
> 
> 因此只能调整中文字符，但是这里又有一个权衡：放大和加大间距。放大中文字符会导致英文字体过小，加大间距会看起来比较奇怪
> 
> 近两年的使用下来，最终选择了加大间距：
> 
> 1. 放大会让中文字符在字符串或者注释中十分突出
> 2. 加大间距可以在阅读时加以区分，但又不会显得突兀，相对更能维持行高，还可以更好地提示你这是等宽字体
> 
> ![image](https://github.com/user-attachments/assets/3b288830-06cf-441e-862e-49d6fdd729a3)
> 
> 因此，得到了这么一个看起来比较奇怪，但是阅读效率相对高一些的字体

我觉得英文的字距不用动，放大中文其实很合理。中文整体大一圈其实没啥问题。

![Image](https://github.com/user-attachments/assets/57357881-c2f8-494d-949b-572eab74d581)
这个行高差距其实可以接受的

**Comment by fengsuiyvmin** [comment]
而且本身咱都中国人，中文显眼点还看着舒坦

**Comment by subframe7536** [comment]
@Leroy-X 已支持网页构建，详见文档
@fengsuiyvmin 已支持中文字符配置 scale factor，详见文档

**Comment by WinterArch** [comment]
西文连字很好看，装机里很久了，因为汉字不匹配一直没开来用。不知道Ubuntu Mono一个英文字体怎么做到和很多字体适配等宽的，好像是调了其他字符高度，能吸纳一下这种调高度的能力吗？

**Comment by subframe7536** [comment]
> 西文连字很好看，装机里很久了，因为汉字不匹配一直没开来用。不知道Ubuntu Mono一个英文字体怎么做到和很多字体适配等宽的，好像是调了其他字符高度，能吸纳一下这种调高度的能力吗？

Ubuntu Mono 的英文宽度和间距比正常的等宽字体小，所以可以对得齐

**Comment by amitbha** [comment]
中文多的时候，中文间距大其实会唤起古早中文阅读的记忆，感觉上并不好

**Comment by yuanguoli** [comment]
我是小白想问个问题，为什么字体在vs或者pycharm中是2：1的，但是在word和记事本中尤其是记事本里就不再是了？有什么解决办法吗？

**Comment by subframe7536** [comment]
> 我是小白想问个问题，为什么字体在vs或者pycharm中是2：1的，但是在word和记事本中尤其是记事本里就不再是了？有什么解决办法吗？

记事本的字体名称里有没有包含CN? 重启之后还是这样吗? 这两个都不行的话发一下字体设置的截图和不能2：1的截图

**Comment by yuanguoli** [comment]
字体就是maple mono nf cn
我研究了一下发现非常奇怪，调整显示比例会导致出问题。好像是是记事本的问题，别的字体比如宋体也会出类似的问题。我是系统200%缩放下，显示比例320%就对不齐，显示比例330%就可以对齐

<img width="2767" height="1069" alt="Image" src="https://github.com/user-attachments/assets/d9de1267-653d-4ea9-be4d-ac74e8602924" />
<img width="1601" height="648" alt="Image" src="https://github.com/user-attachments/assets/4e6b03bb-1798-4273-90cd-f14ae7ee586a" />
<img width="1601" height="648" alt="Image" src="https://github.com/user-attachments/assets/e4b7fdab-0f97-401d-89c1-11f74696ec3d" />

**Comment by Rayfor000** [comment]
對於字體會有拼接上的問題，我認為可以參考[昭源字體](https://chiron-fonts.github.io/)，其中的 昭源環方 Chiron GoRound TC 同樣使用 OFL 1.1 授權，並且不會出現拼接痕跡

**Comment by subframe7536** [comment]
> 對於字體會有拼接上的問題，我認為可以參考[昭源字體](https://chiron-fonts.github.io/)，其中的 昭源環方 Chiron GoRound TC 同樣使用 OFL 1.1 授權，並且不會出現拼接痕跡

是的，我在discussion的置顶里已经提及到了

**Comment by heixxxa** [comment]
> 这是一个权衡后的选择：
> 
> 中文一个字符单位宽高都是1000，英文一个字符单位宽度600，高度730
> 
> 编程作为一个英文多中文少的场景，需要优先满足英文的阅读体验。像更纱黑体这种压缩英文宽度（500）满足中文字符宽度的字体，在编码的场景阅读起来会比较费力（对我而言）
> 
> 因此只能调整中文字符，但是这里又有一个权衡：放大和加大间距。放大中文字符会导致英文字体过小，加大间距会看起来比较奇怪
> 
> 近两年的使用下来，最终选择了加大间距：
> 
> 1. 放大会让中文字符在字符串或者注释中十分突出
> 2. 加大间距可以在阅读时加以区分，但又不会显得突兀，相对更能维持行高，还可以更好地提示你这是等宽字体
> 
> ![image](https://github.com/user-attachments/assets/3b288830-06cf-441e-862e-49d6fdd729a3)
> 
> 因此，得到了这么一个看起来比较奇怪，但是阅读效率相对高一些的字体
> 
> 如果想要减小间距，可以通过[自定义构建](https://github.com/subframe7536/maple-font/blob/variable/README_CN.md?rgh-link-date=2024-07-09T02%3A57%3A23.000Z#%E7%BC%A9%E5%B0%8F%E4%B8%AD%E6%96%87%E5%AD%97%E4%BD%93%E7%9A%84%E9%97%B4%E8%B7%9D)实现

你好，我想问一些关于字体的知识

Google Sans Code

<img width="1912" height="1001" alt="Image" src="https://github.com/user-attachments/assets/b4a6cbcb-9adc-4747-b4a4-5777933e2ede" />

这里显示的宽度是600，em size是1200，就是 0.6 em 吗？

Maple Mono NF CN

<img width="1912" height="1001" alt="Image" src="https://github.com/user-attachments/assets/5a66e639-322b-47f5-b1d7-a334dcb29173" />

<img width="1912" height="1001" alt="Image" src="https://github.com/user-attachments/assets/a2e5f681-6981-4601-b864-f1fc8a891a32" />

而这里英文的宽度是 600，中文的宽度是 1200，em size是1000，这里中文和英文是2:1的，但为什么前面提到的都是中文是1000，而不是1200呢？

**Comment by subframe7536** [comment]
@heixxxa 1000的em size是继承自JetBrains Mono的，影响的是字体的整体大小，渲染引擎会根据em size对字形进行缩放。上面的1000指的中文字的设计宽度，思源黑体的中文字部分全都是1000，和等宽英文部分的600无法对齐，所以加宽到了1200

**Comment by heixxxa** [comment]
> [@heixxxa](https://github.com/heixxxa) 1000的em size是继承自JetBrains Mono的，影响的是字体的整体大小，渲染引擎会根据em size对字形进行缩放。上面的1000指的中文字的设计宽度，思源黑体的中文字部分全都是1000，和等宽英文部分的600无法对齐，所以加宽到了1200

谢谢，我理解了

**Comment by subframe7536** [comment]
这个间距可以接受吗？

<img width="994" height="208" alt="Image" src="https://github.com/user-attachments/assets/bc20f30e-51c2-4be0-ae2e-4f7143c9b44f" />

**Comment by subframe7536** [comment]
加了个选项，可以试试。[文档](https://github.com/subframe7536/maple-font/blob/variable/README_CN.md#%E7%AA%84%E5%AD%97%E7%AC%A6)

**Comment by I-Want-ToBelieve** [comment]
@subframe7536 在使用 Maple 中文字体时，我发现中文字符之间的间距比系统默认字体要大一些。
这个额外的字间距会导致一些网站在 Chrome 中的布局表现异常：原本不会换行的 flex 布局或菜单项，在 Chrome 中会意外换行，而 Firefox 则正常。
这种现象似乎与 Chrome 对 flex item 的 min-content 宽度计算有关，字体的额外间距直接增加了最小宽度，从而触发了 wrap。
这个问题主要出现在使用 Zoom 或特定 flex 容器时，更改字体或缩小间距可以缓解。

<img width="1189" height="457" alt="Image" src="https://github.com/user-attachments/assets/b561c632-438c-4908-9a65-994bd23fca32" />

**Comment by subframe7536** [comment]
> @subframe7536 在使用 Maple 中文字体时，我发现中文字符之间的间距比系统默认字体要大一些。
> 这个额外的字间距会导致一些网站在 Chrome 中的布局表现异常：原本不会换行的 flex 布局或菜单项，在 Chrome 中会意外换行，而 Firefox 则正常。
> 这种现象似乎与 Chrome 对 flex item 的 min-content 宽度计算有关，字体的额外间距直接增加了最小宽度，从而触发了 wrap。
> 这个问题主要出现在使用 Zoom 或特定 flex 容器时，更改字体或缩小间距可以缓解。
> 
> <img width="1189" height="457" alt="Image" src="https://github.com/user-attachments/assets/b561c632-438c-4908-9a65-994bd23fca32" />

因为定位是编程场景特化的字体，所以优先考虑编辑器里的体验；自行构建的话支持配置间距

**Comment by wushixiann** [comment]
`"width": "slim" "cn.narrow": false,`  在vscode 显示是正常的. 同样的字体在记事本中显示比较奇怪. 而且这个K 为什么是个全角的. 

<img width="640" height="177" alt="Image" src="https://github.com/user-attachments/assets/1575f779-0f50-4ca1-9e63-053308ac4fc7" />


`"width": "slim" "cn.narrow": true,`  则都正常. 但是字体被标记为非等宽了. 按说此时中文1000, 英文500,应该是可以等宽的吧.

<img width="612" height="148" alt="Image" src="https://github.com/user-attachments/assets/c924acbb-4ca8-424a-89e0-6562cf02a881" />

(顺便吐槽,我以为cn.narrow 是和 width narrow一样呢, 应该是1100, 但是build之后发现对不齐, 原来是1000. )

**Comment by subframe7536** [comment]
> `"width": "slim" "cn.narrow": false,`  在vscode 显示是正常的. 同样的字体在记事本中显示比较奇怪. 而且这个K 为什么是个全角的. 
> 
> <img width="640" height="177" alt="Image" src="https://github.com/user-attachments/assets/1575f779-0f50-4ca1-9e63-053308ac4fc7" />
> 
> 
> `"width": "slim" "cn.narrow": true,`  则都正常. 但是字体被标记为非等宽了. 按说此时中文1000, 英文500,应该是可以等宽的吧.
> 
> <img width="612" height="148" alt="Image" src="https://github.com/user-attachments/assets/c924acbb-4ca8-424a-89e0-6562cf02a881" />
> 
> (顺便吐槽,我以为cn.narrow 是和 width narrow一样呢, 应该是1100, 但是build之后发现对不齐, 原来是1000. )
> 
> 

这两个问题应该已经修复了，cn.narrow 属于历史遗留问题了
