### ISSUE TITLE
Help: Can't get Ligatures working

### ISSUE THREAD

**Issue by Z-xus** [subframe7536/maple-font#214]
Ligatures Dont work in VsCode and Neovim for me, But it works in Firefox for some reason.. 
![image](https://github.com/user-attachments/assets/ee951eae-d0ed-4bde-9c9e-4efccba71c90)
![image](https://github.com/user-attachments/assets/fb3f9beb-732d-466a-a1ad-94884efb36f1)

This is the firefox settings:
![image](https://github.com/user-attachments/assets/58f98588-c66f-4bd5-a70d-578d6c2e4633)
And this is for neovim in alacritty:
![image](https://github.com/user-attachments/assets/ac957798-3976-4d31-bb81-ccad98eec182)

I installed the font using yay on Arch with i3. 
And wonderful work btw, I love this font!

**Comment by subframe7536** [comment]
Thanks for your love!

For VSCode, setup `"editor.fontLigatures": "'calt'"` in your `setting.json`

For Alacritty, ligatures are not supported, see [compatibility](https://github.com/tonsky/FiraCode?tab=readme-ov-file#terminal-compatibility-list)

BTW, it is recommended to try V7 at latest release!

**Comment by Z-xus** [comment]
Sure! Hope to see alacritty support soon too. Thanks a lot!
