### ISSUE TITLE
[Linux] Build succeed but without CN output

### ISSUE THREAD

**Issue by Gn3po4g** [subframe7536/maple-font#216]
Build in archlinux-wsl2 and final output:(latest variable branch)
```
=== [Release Mode] ===
archieve: OTF
archieve: NF
archieve: TTF-AutoHint
archieve: Variable
archieve: Woff2
archieve: TTF
copy woff2 to root
=== [Build Success (125.18 s)] ===
```
Only change `LINUX_FONTFORGE_PATH` to "/usr/bin/fontforge"

**Comment by subframe7536** [comment]
As is. There are no CN base fonts in the repo until the stable release.

I will prerelease them in gitee release. You should `mkdir source/cn`, put them into the `cn` dir and rerun `python build.py`

The link will be appended once I finish the upload

**Comment by subframe7536** [comment]
https://gitee.com/subframe7536/Maple/releases/tag/v7.0-prerelese-cn

**Comment by Gn3po4g** [comment]
got it.
