### ISSUE TITLE
【BUG】中文省略号渲染有问题

### ISSUE THREAD

**Issue by mano233** [subframe7536/maple-font#217]
# maple-font
![505985192b63e082bd7664c9ea9f9e2d](https://github.com/user-attachments/assets/a35b61a9-9f81-495a-bf1f-562c176aae06)
# jetbrains-mono
![image](https://github.com/user-attachments/assets/dead8859-6e19-471b-ae20-1171fb1377e7)

**Comment by subframe7536** [comment]
用的是 Maple Mono 还是 Maple Mono NF CN ?

**Comment by Gn3po4g** [comment]
btw 字符串中转义符会比正常\字符细一点，是bug还是特性？

**Comment by subframe7536** [comment]
特性，参考 Fira Code 做了一个连字规则 https://github.com/subframe7536/maple-font/blob/b8ab10e2ce43e6a56a59c8307305422019ddebb3/source/features/regular.fea#L1500-L1503

**Comment by Gn3po4g** [comment]
但是好像没有\b

**Comment by subframe7536** [comment]
是的，还有正则里的一些没有，考虑后面加上，然后支持通过开启ss04禁用

**Comment by subframe7536** [comment]
v7.0-beta23 已发布
