### ISSUE TITLE
Improve a glyph

### ISSUE THREAD

**Issue by spcbfr** [subframe7536/maple-font#219]
Hi great font, I am using V7 and I noticed that the a glyph has a different visual thickness at differents points in the glyphs. not sure if this is the case with v6 too but I just noticed it.

here is a demo
![2024-08-04_17-13](https://github.com/user-attachments/assets/14c3998b-a96b-486f-be03-ad563943a87b)
notice how the a in `change` sticks out

**Comment by subframe7536** [comment]
Maybe you should choose another hint version

Here is the explaination: https://github.com/subframe7536/maple-font/issues/107#issuecomment-2212908202

**Comment by spcbfr** [comment]
fixed by using TTF instead of variable font
