### ISSUE TITLE
为什么todo没有预期显示白底包裹的形式？

### ISSUE THREAD

**Issue by Daotin** [subframe7536/Maple-font#22]
如下图，没有显示白底包裹的形式？
![image](https://user-images.githubusercontent.com/23518990/186561472-927a4ef9-5684-465d-9d7a-785a99e03abb.png)

期望显示：
![image](https://user-images.githubusercontent.com/23518990/186561543-61f93040-f773-4c4c-9b58-1c70e6c4c36a.png)

**Comment by subframe7536** [comment]
最右边的是)

**Comment by Daotin** [comment]
哦哦，谢谢！

**Comment by Daotin** [comment]
> 最右边的是)

哦哦，谢谢！
