### ISSUE TITLE
Cyrillic letter "б" and digit "6" looks too similar in V7

### ISSUE THREAD

**Issue by userlond** [subframe7536/maple-font#223]
There are 2 samples below, captured in Windows 10, latest VS Code. Both fonts are 14px, semibold.

Maple font (MapleMono-TTF-AutoHint.zip V7.0 Beta23):
![scr_20240812_103112_059](https://github.com/user-attachments/assets/5f8850e2-227b-4d71-b9fe-c96928b35389)

Jetbrains Mono font (v 2.304):
![scr_20240812_103219_435](https://github.com/user-attachments/assets/3d25b22c-1cb8-4e51-b6b6-9a1f8172714f)

Text version:
```
б - russian letter
6 - digit
б6 - looks similar in Maple font
```

**Comment by subframe7536** [comment]
how about this one?

![image](https://github.com/user-attachments/assets/abb25b26-8449-44d1-b68a-5d85fa420b08)

**Comment by userlond** [comment]
It's perfect, thanks for your work

**Comment by subframe7536** [comment]
OK, I will release the update in next beta release this weekend

**Comment by subframe7536** [comment]
v7.0-beta24 released
