### ISSUE TITLE
Double story `g`

### ISSUE THREAD

**Issue by vinzlee97** [subframe7536/maple-font#226]
Hello there, thanks again for the great font!

Will it be possible to do double story `g`, since there is single story `a` available in `cv02` stylistic set ? Thanks in advance.

The inspiration is from Consolas or Iosevka SS03 (which is also derived from Consolas). Personally, I don't prefer Fira Code's style 😁

**Comment by subframe7536** [comment]
Sorry, one of the main reasons for making this font is that I think some of the default glyphs in `Consolas` are ugly... Including `g`...

**Comment by subframe7536** [comment]
I will implement it in v7.1 as a character variant. You can track it here: #329
