### ISSUE TITLE
Ligature of ==

### ISSUE THREAD

**Issue by Volar2324** [subframe7536/maple-font#229]
Could you please provide ss to control the ligature of == ? The ligature of == is sometimes confusing

**Comment by subframe7536** [comment]
`ss02`

See in [V7](https://github.com/subframe7536/maple-font/blob/variable/README.md#features) doc

**Comment by Volar2324** [comment]
> `ss02`
> 
> See in [V7](https://github.com/subframe7536/maple-font/blob/variable/README.md#features) doc

Maybe something like this ? 

![image](https://github.com/user-attachments/assets/de8e4be2-bc87-4708-af46-aaa1151c2150)

**Comment by subframe7536** [comment]
I used to thought about that, but many people complain about the ligature of `==` and `!=` at the same time.

I will reconsider this styleset

**Comment by subframe7536** [comment]
Currently, I follow up with Jetbrains Mono's ligature. There is another ligature `=/=`, which may conflict with `!==` if follow the Fira Code's design.

**Comment by Volar2324** [comment]
> Currently, I follow up with Jetbrains Mono's ligature. There is another ligature `=/=`, which may conflict with `!==` if follow the Fira Code's design.

你好，我的意思就是能不能单独弄一个参数来控制 `==`， 因为两个等号连起来一不注意容易看不清，

**Comment by subframe7536** [comment]
你的意思我理解

但是如果照着你说的改，对于 `=/= !==`

Fira Code (ss08) 这种存在混淆的可能

![image](https://github.com/user-attachments/assets/3c31dbaf-bf0b-4f25-ad56-3004a923bf4c)

Jetbrains Mono (ss19) 这种更能分辨一些

![image](https://github.com/user-attachments/assets/983c04ce-a5a8-41d0-8a08-b39dc4a32096)

至于新增一个 `ss05`，单独控制 `==` / `===`，对于整体风格是更不合适的

**Comment by subframe7536** [comment]
很多人都是在说 `==` 的同时也说 `!=` 的看不清，所以我的考量就是在 `ss02` 关闭所有等号连字

**Comment by Volar2324** [comment]
原来是这样，我感觉 `!=` 看起来还好，不过全部关闭也可以

我目前也想不到更好的方式
