### ISSUE TITLE
Sublime中[TODO)渲染失败

### ISSUE THREAD

**Issue by Howardzhangdqs** [subframe7536/Maple-font#23]
sublime text中[TODO)渲染失败
操作系统：windows11
sublime text Build4216，已购买许可证并注册
![image](https://user-images.githubusercontent.com/75195784/186577563-4d55e89a-053c-4691-bb14-06eecc284572.png)
setting中的配置：
```json
{
    "font_face": "Maple Mono SC NF",
}
```
其他地方如系统自带记事本渲染都正常

**Comment by subframe7536** [comment]
连字有开启吗？我这个是calt
```json
"font_options": [
    "calt"
],
```

**Comment by Howardzhangdqs** [comment]
其他类似的连字都显示正常，唯独我最想用的todo没有:cry:
![image](https://user-images.githubusercontent.com/75195784/187359444-39f67702-5895-4d76-bb98-01062a083c28.png)
具体设置：
```json
{
	"font_face": "Maple Mono SC NF",
	"font_options": ["directwrite", "calt"],
	"word_separators": "./\\()\"'-:,.;<>~!@#%^&*|+=[]{}`~?",
}
```

**Comment by subframe7536** [comment]
https://www.sublimetext.com/docs/ligatures.html 看起来是目前不支持包含字母的连字

**Comment by brucmao** [comment]
这个[TODO) 在python无法使用把，前面加#[TODO) 就打回原形了，java中 //[TODO) 倒是显示正常

**Comment by subframe7536** [comment]
> 这个[TODO) 在python(pycharm)中无法注释使用把，前面加#[TODO) 渲染失败，java中 //[TODO) 倒是显示正常
> 
> 看来只能使用多行注释 '''[TODO)''' 这样倒是可以

这个问题确实存在，因为注释里的todo作为关键字高亮了，可能和`[`分离了，导致无法匹配[TODO)
我已增加了几个feature #31 #32 #33
