### ISSUE TITLE
数字的大小不一致

### ISSUE THREAD

**Issue by lly10011** [subframe7536/maple-font#230]
V7.0 Beta24 在 vscode 中使用斜体，开启了'cv01', 'cv03', 'ss01', 'ss02', 'ss03'特性，0123456789显示时，6、9如图所示，上下未对齐（不知道是不是特意做成这样的
![1724141427158](https://github.com/user-attachments/assets/59f47ad4-20b4-4994-a60b-8fb91435b7ac)
）

**Comment by subframe7536** [comment]
挺奇怪的，我这边正常

系统是linux吗？

**Comment by lly10011** [comment]
Windows 10 20H2，VSCode 1.92.2

**Comment by subframe7536** [comment]
装v7-beta25然后重启一下试试

**Comment by lly10011** [comment]
安装25版后重启，还是同样的情况
![Snipaste_2024-08-26_08-51-55](https://github.com/user-attachments/assets/0b8bde8e-fe46-457d-825f-badd306b0a9e)

**Comment by subframe7536** [comment]
试试这个 https://fontdrop.info/ 

这里面有同样问题的话就需要再排查一下了

**Comment by lly10011** [comment]
字体大小不一致时，表现不相同。目前看来，8、14是有这种情况，其他大小时，9在视觉上，下面比其他数字要低一点
![Snipaste_2024-08-26_13-34-45](https://github.com/user-attachments/assets/fe3db734-a0e6-4662-881b-6445e71f952e)
![Snipaste_2024-08-26_13-35-08](https://github.com/user-attachments/assets/044e2f1a-bb14-479c-a015-58f641233d30)
![Snipaste_2024-08-26_13-35-28](https://github.com/user-attachments/assets/9c705c4d-2200-4554-b596-f125f0ce37af)
![Snipaste_2024-08-26_13-35-59](https://github.com/user-attachments/assets/74d83a9d-3ef6-4dba-ad90-58b5ac3537b0)

**Comment by subframe7536** [comment]
用的是 `ttf-autohint` 吗？换成 `ttf` 试试

如果是 `ttf` 就换成 `ttf-autohint` 试试

**Comment by subframe7536** [comment]
这是我电脑上的效果
![recording](https://github.com/user-attachments/assets/32274d7d-7958-45a6-a6ce-5c18738692c9)

**Comment by lly10011** [comment]
下图是 MapleMono-TTF-AutoHint(1.76MB) 格式的，应该是出现了上面的情况
https://github.com/user-attachments/assets/80b8fa76-5306-4185-a3b9-dafd85bd82b3

下图是 MapleMono-TTF(1.33MB) 格式的，我这边测试没有问题
https://github.com/user-attachments/assets/108dd694-0972-4aec-9fc8-6f0fb4b0a67d

之前楼层反馈的截图，是 MapleMono-NF-CN(146MB) 格式的

**Comment by lly10011** [comment]
下图是 MapleMono-TTF-AutoHint(1.76MB) 格式的，应该是出现了上面的情况
![01 - MapleMono-TTF-AutoHint](https://github.com/user-attachments/assets/404444e0-d683-41ef-8908-71293da00593)

下图是 MapleMono-TTF(1.33MB) 格式的，我这边测试没有问题
![02 - MapleMono-TTF](https://github.com/user-attachments/assets/9facd9a6-2fa6-4cfa-9504-315dfa504169)

上面楼层用截图反馈的，用的是 MapleMono-NF-CN(146MB) 格式的

**Comment by subframe7536** [comment]
可以看一下 #107 ，里面有详细解释

**Comment by lly10011** [comment]
将 MapleMono-NF-CN 设置为回退字体解决了上面的问题。
请问后续 MapleMono-NF-CN 会调整一下吗？

**Comment by lly10011** [comment]
将 MapleMono-NF-CN 设置为回退字体解决了上面的问题。
请问后续 MapleMono-NF-CN 会调整一下吗？这个国内用的可能会多一点

**Comment by subframe7536** [comment]
之后打算把多个配置版本都打一份包

**Comment by lly10011** [comment]
感谢

**Comment by subframe7536** [comment]
Provide in v7.0-beta31
