### ISSUE TITLE
`ss03` not working on italic except all uppercase

### ISSUE THREAD

**Issue by vinzlee97** [subframe7536/Maple-font#232]
![image](https://github.com/user-attachments/assets/b72410bc-8315-4c46-83d4-5b0a358efe93)

v7.0-beta25

**Comment by subframe7536** [comment]
Everything seems works

![recording](https://github.com/user-attachments/assets/438dbac7-05ff-4c30-8f84-70ee28fee0c0)

You can test the font with https://fontdrop.info/ or https://mutsuntsai.github.io/fontfreeze/

**Comment by subframe7536** [comment]
You should also set `"ss03": "enable"` in `feature_freeze_italic` field
