### ISSUE TITLE
`\` Ligature

### ISSUE THREAD

**Issue by Gn3po4g** [subframe7536/maple-font#234]
Windows系统下使用时，字符串中可能会包含目录分隔符`\`，会被当作转义符使用出现连字变体。
![image](https://github.com/user-attachments/assets/3833f993-feee-4fec-989e-f95547fbb730)

**Comment by subframe7536** [comment]
我自己也发现了，但是一直没想好怎么改

1. 把整个系列的连字改成单独的styleset
2. 只保留符号相关的连字
3. 默认启用符号的连字，用ss05开启字母的连字

**Comment by Gn3po4g** [comment]
感觉也是默认关闭或者干脆取消比较好。虽然`\`大部分时候作转义符使用，但还是有使用raw string的情况。

**Comment by subframe7536** [comment]
下个版本有重构连字的打算，周末在discussion里写点我的思考

**Comment by subframe7536** [comment]
在 #240

**Comment by subframe7536** [comment]
最终打算是3

**Comment by subframe7536** [comment]
目前这部分还没有上传

**Comment by subframe7536** [comment]
已更新，可以拉取一下试试

**Comment by Gn3po4g** [comment]
是不是把`\\`漏了

**Comment by subframe7536** [comment]
没有吧，我这边正常的

https://github.com/subframe7536/maple-font/blob/variable/source%2Ffeatures%2Fregular.fea#L36-L36

**Comment by Gn3po4g** [comment]
![图片](https://github.com/user-attachments/assets/2129193f-5f19-4af6-87b8-37cede62ebd0)
我这里只有字母连字宽度是正常的

**Comment by subframe7536** [comment]
> 3. 默认启用符号的连字，用ss05开启字母的连字

`\\` 是默认开启的

**Comment by Gn3po4g** [comment]
强迫症好难受💔

**Comment by subframe7536** [comment]
其实我在考虑，要不要把`ss05`改成 关闭 `\\`，因为`\n`这种默认不开启主要是因为用处不大。。。

**Comment by Gn3po4g** [comment]
感觉这种连字真的用不到，干脆默认全部关闭甚至删除...

**Comment by subframe7536** [comment]
主要是看正则的时候转义字符看的头大😇

**Comment by Gn3po4g** [comment]
而且jb家族开启连字似乎强制开启所有连字特性？

**Comment by subframe7536** [comment]
> 其实我在考虑，要不要把`ss05`改成 关闭 `\\`，因为`\n`这种默认不开启主要是因为用处不大。。。

下周发

**Comment by Nagidrop** [comment]
I was about to report this issue, but it seems there's already a thread.

The backslash is very thin and it's very noticable when you type in another backslash (1 appears bolder than the other). Here is a video showing the problem on [JupyterLite](https://jupyter.org/try-jupyter/lab/).

https://github.com/user-attachments/assets/04fb3449-583f-4daf-986c-0e8796e549b2

Some background information:
- It's reproducible on v7.0 Beta28 variable (current latest version)
- It's only reproducible on editors that support ligatures
- Some other characters cause the issue as well (it seems random, without any rules, as shown in below image -- the backslashes before a and e seems normal but other are visibly thinner)

![backslash_weight_2](https://github.com/user-attachments/assets/bcb9e28a-6e31-4341-8bdc-ef99ac555620)

**Comment by subframe7536** [comment]
Thanks for your suggestion. But that just my personal flavor, making it easier for me while reading long complex regular expressions, You can suppress this feature by turning on `ss05` in next beta version, and will no longer effect in letters.

**Comment by Nagidrop** [comment]
> Thanks for your suggestion. But that just my personal flavor, making it easier for me while reading long complex regular expressions, You can suppress this feature by turning on `ss05` in next beta version, and will no longer effect in letters.

It's great to have it when working with long regex though. I just don't know it's a feature because it isn't too obvious, no biggie :D

Btw I tried to disable/enable the `ss05` in `config.json` and use the latest `build.py` in `variable` branch, but it doesn't work. I can only disable `ss05` by disabling all ligature rules in `freeze_feature()` like:
```
# disable all ligature rules
for calt_feature in calt_features:
    calt_feature.LookupListIndex = []
```

Could the next beta version possibly fix this?

**Comment by subframe7536** [comment]
There will be another option in `config.json` to remove all the ligatures. I have already implement it in my local machine, but have not push it yet

**Comment by Nagidrop** [comment]
> There will be another option in `config.json` to remove all the ligatures. I have already implement it in my local machine, but have not push it yet. Also include the new `ss05`. Planing to release this weekend.

I'm looking forward to it. I was just making sure that it wasn't a bug. Thank you for your hard work :D

**Comment by subframe7536** [comment]
Release in v7.0-beta29
