### ISSUE TITLE
[Bug] 省略号（U+2026）在特定情况下渲染错误（MapleMono-NF-CN）

### ISSUE THREAD

**Issue by Fr4nk1inCs** [subframe7536/maple-font#239]
在终端中使用 MapleMono-NF-CN 时，如果省略号（U+2026 `…`）所在的词（不含空格的连续字符串）中有英文字母 `[a-zA-Z]`，则会被渲染为全角省略号，如下所示：
- Kitty: 
![de8bb572875c4bd0b68e894df156e370](https://github.com/user-attachments/assets/b4c9a9e0-145a-4cc1-9f36-7c00a06dcae0)
- Wezterm: 
![image](https://github.com/user-attachments/assets/21376341-d05a-4d23-aa03-3edea71bac47)
- Windows Terminal: 
![image](https://github.com/user-attachments/assets/44eec2b4-26ab-4836-b100-ff94e6f1aa0e)

**Comment by subframe7536** [comment]
粗略地看了一下，可能是cv98或者语言的问题，周末尝试修一下

**Comment by subframe7536** [comment]
试试这个 [MapleMono-NF-CN-Regular.zip](https://github.com/user-attachments/files/16827625/MapleMono-NF-CN-Regular.zip)

**Comment by Fr4nk1inCs** [comment]
Work like a charm :) 👍
![image](https://github.com/user-attachments/assets/e746f2e0-86d3-426d-834e-97b5455f3bdc)

**Comment by subframe7536** [comment]
本质大概率是不同终端对 `locl` 这个 OpenType 特性处理方式不同，现在这个是把 `locl` 删除了，所以应该不会有问题了

**Comment by Fr4nk1inCs** [comment]
在终端中设置 `locl=0` 确实就渲染正常了

**Comment by CoelacanthusHex** [comment]
按理说 U+2026 不应该被包含在 locl 的规则里才对，这东西不是根据 locale 而是根据上下文决定的。
此外终端一般期望东亚可变宽度字符是半宽，所以像是 Sarasa Gothic 这种包含 CJK 字符的字体会提供一个这些字符恒为半宽的变体，专供终端使用。[^1]

[^1]: https://github.com/be5invis/Sarasa-Gothic#what-are-the-names

**Comment by subframe7536** [comment]
是的，但是目前考虑的是直接all in one了，通过自行编译选择哪些想要的特性
