### ISSUE TITLE
在Jetbrains IDE中字体显示有毛刺

### ISSUE THREAD

**Issue by aidenmx** [subframe7536/Maple-font#24]
在 idea 中的显示效果(SubPixel):
![image](https://user-images.githubusercontent.com/48705257/186627775-09d18f7b-6794-4915-9aeb-67f04476acd0.png)

在VSCode中的显示效果:
![image](https://user-images.githubusercontent.com/48705257/186627955-2111c3f6-c56a-4f1a-888e-9b889d521e82.png)

**Comment by subframe7536** [comment]
hint的问题，晚上发的v5.5修复

**Comment by subframe7536** [comment]
[MapleMono-SC-NF-Regular.zip](https://github.com/subframe7536/Maple-font/files/9423636/MapleMono-SC-NF-Regular.zip)
能否帮忙测试一下这个是否还有毛刺？

**Comment by aidenmx** [comment]
新的字体效果已经正常了, 感谢修复
![image](https://user-images.githubusercontent.com/48705257/186643012-bdcb9858-f82d-4b85-aead-3a9cc6727b56.png)
