### ISSUE TITLE
如何能获取到  Maple Mono SC NF 字体

### ISSUE THREAD

**Issue by jinman0826** [subframe7536/maple-font#242]
win上build.sh失败，并没有产出 Maple Mono SC NF字体包

**Comment by subframe7536** [comment]
#228

**Comment by subframe7536** [comment]
v6 看中文构建文档

https://github.com/subframe7536/maple-font/blob/chinese/source%2FREADME_CN.md#1-%E5%85%8B%E9%9A%86%E4%BB%93%E5%BA%93

**Comment by jinman0826** [comment]
![image](https://github.com/user-attachments/assets/760ba8b6-115b-4f84-b0ae-9e32c2eb08f3)
执行直接报错了

**Comment by subframe7536** [comment]
看上去是没有正确生成 nerd font 字体，在 github codespace 里可以正常构建的

**Comment by subframe7536** [comment]
同时，由于精力有限，v6的构建脚本不再维护
