### ISSUE TITLE
在vs中，中文字体显示效果较差

### ISSUE THREAD

**Issue by dreamMilk** [subframe7536/maple-font#246]
![image](https://github.com/user-attachments/assets/fbfaa1ca-8ab5-4c50-8b8f-94e3dcccc3e0)
使用的字体是Maple Mono NF CN

使用Maple UI也会存在类似问题
![image](https://github.com/user-attachments/assets/0b6d1dae-561d-4174-a82a-bafbffb1a285)

是软件渲染的问题吗

**Comment by subframe7536** [comment]
中文字体部分没有hint，加了hint字体体积会增大30%

**Comment by dreamMilk** [comment]
> 中文字体部分没有hint，加了hint字体体积会增大30%

请问这个有什么解决办法吗，自行编译构建也可以

**Comment by subframe7536** [comment]
可以用 `ttfAutoHint`，或者用构建脚本在用的 `ftcli ttf autohint /path/to/font/dir`

下版本会新增一个配置选项

**Comment by dreamMilk** [comment]
好的，期待下一次更新

**Comment by subframe7536** [comment]
需要注意的是，并不是直接提供编译好的字体，需要自行配置和构建

**Comment by dreamMilk** [comment]
```ini
{
  "$schema": "./source/schema.json",
  "family_name": "Maple Mono",
  "use_hinted": true,
  "pool_size": 4,
  "feature_freeze": {
    "cv01": "ignore",
    "cv02": "ignore",
    "cv03": "ignore",
    "cv04": "ignore",
    "cv98": "ignore",
    "cv99": "ignore",
    "ss01": "ignore",
    "ss02": "ignore",
    "ss03": "ignore",
    "ss04": "ignore",
    "zero": "ignore"
  },
  "feature_freeze_italic": {
    "cv01": "ignore",
    "cv02": "ignore",
    "cv03": "ignore",
    "cv04": "ignore",
    "cv98": "ignore",
    "cv99": "ignore",
    "ss01": "ignore",
    "ss02": "ignore",
    "ss03": "ignore",
    "ss04": "ignore",
    "zero": "ignore"
  },
  "nerd_font": {
    "enable": true,
    "version": "3.2.1",
    "mono": true,
    "use_font_patcher": false,
    "glyphs": [
      "--complete"
    ],
    "extra_args": []
  },
  "cn": {
    "enable": true,
    "with_nerd_font": true,
    "fix_meta_table": true,
    "clean_cache": false,
    "narrow": false,
    "use_hinted": true
  }
}
```
使用最新的代码和上述配置文件后中文显示仍然存在问题
![image](https://github.com/user-attachments/assets/d19521c1-c4d1-4d26-9ad8-28c9867a5be4)
还有什么地方需要更改吗

**Comment by dreamMilk** [comment]
在构建过程中会生成MapleMonoCNBase-xx.tff文件，而代码中在寻找MapleMonoCN-xx.tff，需要手动重命名才能继续编译
![image](https://github.com/user-attachments/assets/e668c1d9-8bf5-4e8c-a07a-e787fb9dbd62)

**Comment by subframe7536** [comment]
抱歉忘记更新链接了：https://gitee.com/subframe7536/Maple/releases/tag/v7.0-beta23

如果还是没有效果，就先试一下重启清理字体缓存，如果还是不行就试试不要加hint，具体可以看 #107

**Comment by dreamMilk** [comment]
尝试后仍然没有效果，可能是字号较小或者软件渲染的问题，放弃挣扎了
