### ISSUE TITLE
Ligature Request |=

### ISSUE THREAD

**Issue by vikky49** [subframe7536/maple-font#247]
Can we have a ligature request for this symbol |= which is used in java 

Here is how it looks in JetBrains Mono
<img width="24" alt="portal – LicenseeUserServiceImp java 2024-09-18 09-50-42" src="https://github.com/user-attachments/assets/d6c250dd-e39d-4c0d-9b50-78bc89fd11a9">

**Comment by subframe7536** [comment]
See in #174
