### ISSUE TITLE
请问有没有CN，不带连字符号的版本？

### ISSUE THREAD

**Issue by YUANCHUYC** [subframe7536/maple-font#248]
请问有没有CN，不带连字符号的版本？  不喜欢连字 喜欢1就是1 2就是2的感觉 求求大佬！

**Comment by subframe7536** [comment]
只要编辑器不开启连字就不会有连字。。。

**Comment by KomiMoe** [comment]
可是Visual Studio没有关闭的选项

**Comment by KomiMoe** [comment]
> 只要编辑器不开启连字就不会有连字。。。


可是Visual Studio没有关闭的选项

**Comment by subframe7536** [comment]
那多加一个构建选项吧

**Comment by cai-xiaohui** [comment]
我也需要非连字符的版本，还是喜欢保持原样。不然截图给其他程序员怕产生歧义。visual studio没法关闭

**Comment by subframe7536** [comment]
所以vs上只能设置一个字体，并且没法开关连字？

**Comment by KomiMoe** [comment]
> 所以vs上只能设置一个字体，而不能切换连字？

是的，vs上只能设置字体，不能开关连字或者设置开关任何字形

**Comment by subframe7536** [comment]
已增加配置 `ligature`，构建时可以直接删除所有连字

**Comment by KomiMoe** [comment]
> 已增加配置 `ligature`，构建时可以直接删除所有连字

ligature设置为false编译后，./fonts/build-config.json没有ligature配置项，并且连字并没有删除。

**Comment by subframe7536** [comment]
这下应该修复了😇

**Comment by KomiMoe** [comment]
> 这下应该修复了😇

已确认。谢谢你的工作

**Comment by cai-xiaohui** [comment]
我们不会编译的。有没有抄作业的方法？像隔壁家的字体，有mono版，也有fixed版

**Comment by subframe7536** [comment]
下版本会提供。还会加github action

**Comment by subframe7536** [comment]
Provide in v7.0-beta31
