### ISSUE TITLE
Readme 中添加 Archlinux 的安装途径

### ISSUE THREAD

**Issue by yuandi42** [subframe7536/Maple-font#25]
我试着将 github release 的该字体打包了 [AUR 仓库](https://aur.archlinux.org/packages/ttf-maple). 希望您能在 Readme 中 Download/ / Install 一节中加上 Archlinux 的安装途径或 AUR 包的链接. 我将不胜感激.

P.S. 我注意到您的 release 没有在说明中附带 hash 码校验, 请问有打算在之后的 release 中加上吗?

**Comment by subframe7536** [comment]
已添加 Archlinux 的安装途径和sha1
MapleMono不包含Nerd Fonts不适用于Commandline，可以的话麻烦修改一下AUR中的描述
- MapleMono NF目前似乎无法被识别为等宽字体

**Comment by yuandi42** [comment]
> MapleMono不包含Nerd Fonts不适用于Commandline，可以的话麻烦修改一下AUR中的描述
> 
>     * MapleMono NF目前似乎无法被识别为等宽字体

我目前还没有把 NF 版本的字体打包. 另外请问将来 gitee 仓库会 release 不带 NF 的 Maple Mono SC 字体吗 (不需要 nerd fonts 里的 icons)?
