### ISSUE TITLE
README中部分链接失效

### ISSUE THREAD

**Issue by WvW-vOiDs** [subframe7536/maple-font#250]
Gitee 链接失效.

https://github.com/subframe7536/maple-font/blob/a45e0474248c999871e2b5b0861de75b9bb57eef/README.md?plain=1#L69

![image](https://github.com/user-attachments/assets/2fb75a69-9821-4901-b83c-739e7f53b74b)

**Comment by subframe7536** [comment]
#228

**Comment by subframe7536** [comment]
README 链接已更新

**Comment by WvW-vOiDs** [comment]
@subframe7536 README还有个typo:

https://github.com/subframe7536/maple-font/blob/217685cef79986f41fe667d6160547a957582383/README.md?plain=1#L86

多打了一遍 "font features are different in ".
