### ISSUE TITLE
NF 版本感觉在oh my posh里面emoji和字之间的间距不太对劲

### ISSUE THREAD

**Issue by KkemChen** [subframe7536/maple-font#251]
Maple Mono NF
![image](https://github.com/user-attachments/assets/ae3d5bcc-af78-4e39-a59e-abbb828c7254)

小房子的图标和 \ 之间 感觉间距太近了 不太好看

---
JetBrainsMono Nerd Font Mono
![image](https://github.com/user-attachments/assets/558ab96b-407d-4531-985b-fd2b59d58a9e)

**Comment by subframe7536** [comment]
详见 https://github.com/ryanoasis/nerd-fonts?tab=readme-ov-file#features 里的第四点

目前用的是默认的 double-width，如有其他需要可以自行构建

**Comment by KkemChen** [comment]
👌

**Comment by KkemChen** [comment]
大佬 考不考虑像 jetbrains mono nerd font mono 这样，再发一个nerd font mono的版本

**Comment by subframe7536** [comment]
正式版应该会加上
