### ISSUE TITLE
Old # in V7?

### ISSUE THREAD

**Issue by arjpar** [subframe7536/maple-font#252]
Could it be possible to get the old # in V6 for V7?

Old # in V6
<img width="29" alt="image" src="https://github.com/user-attachments/assets/1ee1e205-92d5-4c82-b0d8-774f70ea5fdc">

Current # in V7
<img width="19" alt="image" src="https://github.com/user-attachments/assets/bef309b0-0a3f-43bc-98c0-c24d0bc8f341">

**Comment by subframe7536** [comment]
#195 
In short, the `#` in V6 have more different render effect in different screens than other characters, so I remove the gaps in V7
