### ISSUE TITLE
Berkeley Mono-esque 0

### ISSUE THREAD

**Issue by arjpar** [subframe7536/maple-font#253]
Could it be possible to have a Berkeley Mono-esque 0 as default or as a character variant (`cv`) in Maple Mono V7?

Current 0
<img width="18" alt="image" src="https://github.com/user-attachments/assets/714c6c18-8c1c-410f-8c5d-26c2c6d5a6c0">

Berkeley Mono 0
<img width="20" alt="image" src="https://github.com/user-attachments/assets/aea64cda-868d-4b7f-a1c7-61040c6eaf1e">

**Comment by subframe7536** [comment]
I tested it on my monitors, and it is hard to recognize at low resolutions.
