### ISSUE TITLE
Fixed width font on Mac Os X

### ISSUE THREAD

**Issue by boolanger** [subframe7536/maple-font#259]
Currently the font (installed through homebrew) isn't recognized by the Mac OS X font book as "Fixed Width". This means that it's not available for all purposes. I discovered this when I updated the Kitty terminal emulator, which now only accepts fixed width fonts (see https://github.com/kovidgoyal/kitty/discussions/7735).

**Comment by subframe7536** [comment]
#141
Try v7-beta
