### ISSUE TITLE
v7b28 - cannot freeze cv02; Directory structure changed

### ISSUE THREAD

**Issue by chmielcode** [subframe7536/maple-font#263]
First of all - this font was, is and hopefully will be, fantastic :) Until now I've used Maple Mono with calt disabled and cv02 enabled using font freeze. Before beta28 it worked (https://mutsuntsai.github.io/fontfreeze/)
![obraz](https://github.com/user-attachments/assets/43996c22-eeeb-4308-9fbb-a329a91159ec)
With beta28 the cv02 option in not accessible with italic variant any more :(
![obraz](https://github.com/user-attachments/assets/c68187a6-139c-41d4-8407-321415bffbf7)

Another thing is that downloaded autohinted release has each file in a seperate folder
![obraz](https://github.com/user-attachments/assets/cce18dbd-1dd5-435b-a5e6-a1cf5ce172e5)
Not too important, but still an inconvenience.

**Comment by subframe7536** [comment]
Thanks for your love.

In v7.0-beta28, All the italic specific features are greater than cv31 for fine-grained ligatures.  If you want a normal `a`, just enable cv31.  You can check out the document in `source/features/README.md`

**Comment by subframe7536** [comment]
Fixed. And the release file was replaced
