### ISSUE TITLE
斜体“l”的花体样式是否可以调整为普通斜体

### ISSUE THREAD

**Issue by lly10011** [subframe7536/maple-font#265]
如提所述，在不开启连体特性的情况下，个人感觉斜体“l”的花体样式有些影响代码阅读。斜体“ijkf”都已经调整为普通样式，“l”是否也能调整一下。

**Comment by subframe7536** [comment]
开启cv35即可

**Comment by lly10011** [comment]
开启cv35是可以将斜体"l"调整为普通样式，但我的意思是不开启特性的情况下，是否可以默认斜体"l"为普通样式

**Comment by subframe7536** [comment]
你可以自行构建 https://mutsuntsai.github.io/fontfreeze/
