### ISSUE TITLE
Disabling ligatures stops freezing `cvXX` font features

### ISSUE THREAD

**Issue by Nagidrop** [subframe7536/maple-font#267]
I found that inside `handle_ligatures()`, disabling ligatures will make the function return early:
```
if not enable_ligature:
    del font["GSUB"]
    return
```
But that left out the call to `freeze_feature()` below, making all font feature config in `config.json` ineffective, not just `ssXX` ones.

I propose not to return early and instead adding a new parameter `enable_ligature` to `freeze_feature()` to disable the ligatures while reserving other font feature config:
```
def freeze_feature(font, enable_ligature, moving_rules, config):
    ...

    calt_features = [
        feature.Feature for feature in feature_record if feature.FeatureTag == "calt"
    ]

    # my noobie fix
    if not enable_ligature:
        for calt_feature in calt_features:
            calt_feature.LookupListIndex = []

    # Process features
    for tag, status in config.items():
        ...
```

How do you think about this fix? If you are ok with it, I can make a PR for this :D

**Comment by subframe7536** [comment]
This option is purposed for building the non-ligature version, just like `JetBrains Mono NL`.  Can you describe something about your use case?

**Comment by Nagidrop** [comment]
> The `ligature` option in `config.json` is purposed for building the non-ligature version, just like `JetBrains Mono NL`. Can you describe something about your use case?

I think character variants aren't considered ligatures (imo ligatures are only linked/connected characters), so by disabling ligatures I don't expect other font features (outside of `ssXX`) to not work. I suppose other people think the same way as well, because it's a little counterintuitive to not be able to change character variants after you disabled ligatures.

I simply wanted to have normal variants of `@ $ % & Q` in `cv01`, as well as no ligatures. But after changing options in `config.json` and running the script didn't work, so I decided to read the new code and found it.

**Comment by Nagidrop** [comment]
> > The `ligature` option in `config.json` is purposed for building the non-ligature version, just like `JetBrains Mono NL`. Can you describe something about your use case?
> 
> I think character variants aren't considered ligatures (imo ligatures are only linked/connected characters), so by disabling ligatures I don't expect other font features (outside of `ssXX` -- ligature section) to not work. I suppose other people think the same way as well, because it's a little counterintuitive to not be able to change character variants after you disabled ligatures.
> 
> I simply wanted to have normal variants of `@ $ % & Q` in `cv01`, as well as no ligatures. But after changing options in `config.json` and running the script didn't work, so I decided to read the new code and found it.

**Comment by subframe7536** [comment]
It does need more fine-grain configuration in your case, and I think that will be a common request. I get that, and I'm planning to fix it.

And you can just setup `"editor.fontLigatures": "'cv01'"` if you are using VSCode.

**Comment by Nagidrop** [comment]
I'm using JupyterLab with built-in ligature support, but there's no easy way to disable it aside from changing font. That's why I tried to build a new version with my config.

Thank you for implementing this :D

**Comment by subframe7536** [comment]
Oh, I have tried it in browser years ago. Run this script in your browser devtools or create a userscript using [Tampermonkey](https://www.tampermonkey.net/):
```js
document.body.insertAdjacentHTML("beforeend",`<style>*{font-feature-settings:'cv01'}</style>`)
```

If you are using desktop version, I have no experience with it

**Comment by Nagidrop** [comment]
Thank you for the suggestion :D I'd note that just in case. Though I primarily use the desktop version and there is no easy way to have a custom global CSS there. I recalled trying to customize it long ago but it was a fruitless attempt. However, thanks to your font freezing options I think I don't need to anymore :D
