### ISSUE TITLE
关键字没有斜体或者有特殊样式

### ISSUE THREAD

**Issue by skyfxxker** [subframe7536/maple-font#268]
<img width="215" alt="image" src="https://github.com/user-attachments/assets/944750db-a192-4573-8d89-b99a3c8e5a2c">
function关键词没有斜体没有特殊样式，是否是我的confi.json没有应用，这个config.json应该放在哪里

**Comment by skyfxxker** [comment]
<img width="289" alt="image" src="https://github.com/user-attachments/assets/bc0f7c76-2145-4ea8-adbb-e441962b1c66">
想要这种样式

**Comment by subframe7536** [comment]
这个和字体无关，需要你的主题支持关键字显示为斜体

**Comment by skyfxxker** [comment]
> 这个和字体无关，需要你的主题支持关键字显示为斜体

config配置改了没有应用，应该怎么设置

**Comment by subframe7536** [comment]
你的ide是啥

**Comment by subframe7536** [comment]
`config.json`是在构建字体的时候使用的，如果是直接使用，就和`config.json`无关了

**Comment by skyfxxker** [comment]
> 你的ide是啥

vscode 1.94.2

**Comment by subframe7536** [comment]
试试我的主题：https://github.com/subframe7536/vscode-theme-maple

**Comment by potato616** [comment]
> <img alt="image" width="289" src="https://private-user-images.githubusercontent.com/92381971/381632812-bc0f7c76-2145-4ea8-adbb-e441962b1c66.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0NTg4MjQsIm5iZiI6MTczMDQ1ODUyNCwicGF0aCI6Ii85MjM4MTk3MS8zODE2MzI4MTItYmMwZjdjNzYtMjE0NS00ZWE4LWFkYmItZTQ0MTk2MmIxYzY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDEwNTUyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlNTFmZGUwYjk4OTRjODA2ZGU1MDJiZDRmYmVhZTYyNTVlYzYzMjdiZjQ5ODM1NTcwNzA0ZDFhMTM5NjU1MGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xVbcF209cBOUi1Annzxko898Bg-3yOYd5dv2ewekHDg"> 想要这种样式

![image](https://github.com/user-attachments/assets/361b9385-5e00-47d1-9c9a-1de85fb767d0)
像这样吗？
你可以去VSCode设置中查找`Token color Customizations` 设置

**Comment by Evansy** [comment]
试试在当前主题添加

```json
"editor.tokenColorCustomizations": {
    "textMateRules": [
      {
        "scope": [
          //following will be in italic
          "comment",
          "function",
          "entity.name.type.class", //class names
          "constant", //String, Number, Boolean…, this, super
          "storage", //static keyword
          "keyword" //import, export, return…
        ],
        "settings": {
          "fontStyle": "italic"
        }
      }
    ]
  }
```
