### ISSUE TITLE
mobaxterm中文旋转现象

### ISSUE THREAD

**Issue by RabbitHareLu** [subframe7536/maple-font#270]
大佬你好, 我是个字体小白, 我在mobaxterm中使用maple mono nf cn beta29的版本中出现了中文字体逆时针旋转90度的情况, 之前用v6的时候也有这种情况出现, 不清楚是mobaxterm的原因还是字体的原因, 反馈这个现象给你, 麻烦你有空排查一下
![PixPin_2024-11-01_11-24-04](https://github.com/user-attachments/assets/19a46d25-235d-4ebe-9498-263359982e8a)

**Comment by subframe7536** [comment]
别的字体有试过吗？

我这边一切正常

**Comment by RabbitHareLu** [comment]
我用系统自带的字体没发现有字体旋转的问题   系统是win11 24h2 ltsc   之前在老的win11系统上用maple-font v6也出现过同样的问题

**Comment by subframe7536** [comment]
![Clip_2024-11-01_14-10-40](https://github.com/user-attachments/assets/0963ed34-74d3-4a16-af98-250e0bd1a7ce)

无法复现

**Comment by subframe7536** [comment]
中文字符本身的方向没有任何问题，很有可能是软件问题，所以我打算先关闭了。如果还是有问题，推荐使用其他字体

**Comment by atauzki** [comment]
Windows下带@开头的字体名都是经过旋转的
