### ISSUE TITLE
letter "f" looks bad

### ISSUE THREAD

**Issue by atauzki** [subframe7536/maple-font#273]
Version：7.0beta29， maple-mono-NF-CN
the letter "f" doesn't have the same height as "i" and looks bad, espacially in the bold font.

![image](https://github.com/user-attachments/assets/2d7a2058-a3ff-4488-ad3f-833ec6b69152)

![image](https://github.com/user-attachments/assets/f2495b3f-6819-4457-8f85-39264a029beb)

**Comment by subframe7536** [comment]
left is `JetBrains Mono`, right is `Maple Mono NF CN`

![mmexport1731570506056.png](https://github.com/user-attachments/assets/4ea14cfd-6efe-449d-889b-cb6d61f31ffe)

**Comment by subframe7536** [comment]
Seems optimizable... just WIP

**Comment by subframe7536** [comment]
试试这个
[MapleMono-Regular.zip](https://github.com/user-attachments/files/17790480/MapleMono-Regular.zip)

**Comment by subframe7536** [comment]
Release in v7.0-beta30

**Comment by atauzki** [comment]
7.0beta30,letter j in 9pt sticks.
![image](https://github.com/user-attachments/assets/38e09237-5e21-4ae6-8cd2-4a6c3dfc24ca)

**Comment by subframe7536** [comment]
cannot reproduct
![PixPin_2024-11-23_21-14-36](https://github.com/user-attachments/assets/2ac0281c-1688-447e-ad91-0ed2a7249d7f)

**Comment by subframe7536** [comment]
What is the resolution of your monitor?

**Comment by atauzki** [comment]
2560x1600, 165% scaling
not reproduced in TTF but find problem in NF-CN.

**Comment by subframe7536** [comment]
Let's continue the issue in you latest issue
