### ISSUE TITLE
Russian symbols are smaller

### ISSUE THREAD

**Issue by mrChest228** [subframe7536/maple-font#274]
![image](https://github.com/user-attachments/assets/8c4872b8-dd53-427d-a8c6-974f5d440a2a)
On the left are English letters, and on the right are Russian letters.
Fix it, please

**Comment by subframe7536** [comment]
I'm not familiar with these letters and just follow JetBrains Mono's glyphs. Can you provide more detailed infomations?

**Comment by mrChest228** [comment]
This is how the Cascadia Code font behaves with Russian letters:
![image](https://github.com/user-attachments/assets/e85ba296-3940-47e1-abd9-24a7895f4cad)
This is how it behaves with italics:
![image](https://github.com/user-attachments/assets/28754e64-4d99-4e07-9407-e5331dbb8707)
And this is how yours behaves:
![image](https://github.com/user-attachments/assets/14bc70fe-bd56-4327-b41d-61907e626a0b)
JetBrains Mono behaves adequately:
![image](https://github.com/user-attachments/assets/298f1cd4-a546-4eb8-ac0e-736a830f0827)
Please make them bigger and fatter.

P.S. Off topic, but I want to know: will there be ligatures ==, != in the new version? And, I asked a question about the oo (infinity) ligature in "V7: variable fonts and missing characters/ligatures" Can you answer?
If you fix all this, I'll switch from Cascadia Code to your font, it will be perfect

**Comment by subframe7536** [comment]
1. According to your image, the russian symbols of Maple Mono are fallback to default font for some reason.
2. V7 is based on JetBrains Mono, so, normal ligatures like `==` or `!=` is included.
3. Infinity ligatures' benefits weren't good enough for me to implement it, so, no.

**Comment by subframe7536** [comment]
This is what it should be
![image](https://github.com/user-attachments/assets/ecc3813e-1759-47f8-96d7-8b54964c548d)

**Comment by mrChest228** [comment]
It's sad. But neither == / != ligatures nor Russian letters work for me. I use VScode, fontSize = 13.8 (I tried 13, 14, and 15). I don't know... I hope you change your mind someday and make an infinity ligature.

**Comment by subframe7536** [comment]
Maybe you are using v6, v7 is still in beta

**Comment by mrChest228** [comment]
Yes, I'm using v6, is there any difference?

**Comment by subframe7536** [comment]
Almost everything. It is a complete refactoring. There is no russian glyphs in v6.

**Comment by mrChest228** [comment]
I downloaded v7. The problems went away, but for some reason /= stopped combining into a ligature. I set the settings cv01-cv04, ss01-ss05, and start python build.py --release Maybe I did something wrong?

**Comment by subframe7536** [comment]
https://github.com/subframe7536/maple-font/issues/174#issuecomment-2002929545

**Comment by mrChest228** [comment]
So there won't be any more ligatures /=?

**Comment by mrChest228** [comment]
(
