### ISSUE TITLE
letter j in 9pt sticks.

### ISSUE THREAD

**Issue by atauzki** [subframe7536/maple-font#276]
version: 7.0 beta30

![image](https://github.com/user-attachments/assets/fd89be3d-7fd7-4323-8447-28d86bd972a0)

**Comment by subframe7536** [comment]
Cannot reproduce:
![PixPin_2024-11-23_21-14-36](https://github.com/user-attachments/assets/2ac0281c-1688-447e-ad91-0ed2a7249d7f)


What is the resolution of your monitor?

**Comment by subframe7536** [comment]
You should use unhinted version since your monitor's resolution is larger than 1080P

**Comment by atauzki** [comment]
So the CN version is hinted. is that right?

**Comment by subframe7536** [comment]
Yes. I just run `python build.py --no-hinted` to build the font installed in my local machine. I plan to provide some prebuild fonts in next release

**Comment by atauzki** [comment]
no hinted version makes this problem solved.
