### ISSUE TITLE
V7.0-Beta30中斜体`$`和`%`的字形错误

### ISSUE THREAD

**Issue by hqc8848** [subframe7536/maple-font#277]
刚出新版就让我给发现BUG了：
![116241732367432_ pic](https://github.com/user-attachments/assets/d5d6cb6e-1c84-42a9-bad0-b93d72d948b8)
如图所示，键入`$%&`，在斜体中显示出来`%&&`，不知道是不是故意的......

**Comment by subframe7536** [comment]
确实😇

**Comment by hqc8848** [comment]
...所以是故意的？

**Comment by subframe7536** [comment]
在改了在改了

**Comment by hqc8848** [comment]
豪德

**Comment by subframe7536** [comment]
OK了，重新下载release的文件即可

**Comment by hqc8848** [comment]
屑屑awa
