### ISSUE TITLE
pure version ( no modify @ # $ % & Q )

### ISSUE THREAD

**Issue by subframe7536** [subframe7536/Maple-font#28]
no modify @ # $ % & Q
will be released in next version, maybe using stylesets(ss01...) which is similar to `firacode`'s use

**Comment by XXiaoA** [comment]
> no modify @ # $ % & Q will be released in next version, maybe using stylesets(ss01...) which is similar to `firacode`'s use

May I ask when will the new version release. I can't wait! And thanks your great work 😃

**Comment by subframe7536** [comment]
> May I ask when will the new version release. I can't wait! And thanks for your great work 😃
Mostly in 2023
~~考研要紧~~

**Comment by subframe7536** [comment]
done

**Comment by hyoban** [comment]
@subframe7536 can you make @ look normal too

**Comment by subframe7536** [comment]
> can you make @ look normal too
currently the pure version of `@` looks like `@` in `Fira Code`
