### ISSUE TITLE
v7b30 - misaligned 9

### ISSUE THREAD

**Issue by chmielcode** [subframe7536/maple-font#281]
In beta30 "9" is not aligned with other numbers:
![image](https://github.com/user-attachments/assets/819da0b4-e433-4b31-9ea6-4d7286022cd3)

In beta29 everything looks ok. I'm using static autohinted package. Please look into it, it's really distracting :) And thank you once again for a great font.

**Comment by subframe7536** [comment]
Thanks for reporting. Have you ever try unhinted version?

**Comment by subframe7536** [comment]
I have no idea why this issue exists... since the glyph is aligned in design tool

![PixPin_2024-11-28_10-34-05](https://github.com/user-attachments/assets/62188c79-f22a-4e93-a5d4-675d492983b7)

**Comment by atauzki** [comment]
must be hinting problem.
autohinted:
![image](https://github.com/user-attachments/assets/da8c516e-c5bd-4f34-9412-621a3bfa3c3e)

unhinted CN version:
![image](https://github.com/user-attachments/assets/e6ff6c66-3d99-435c-8d43-67c6d6a5e6bc)

**Comment by chmielcode** [comment]
I did try the unhinted version in the past and checked out b30 just now, but it does not look right. I use Windows with multiple apps with different font rendering issues each (native, some Java based, .NET, electron etc.). Only the hinted version look ok in most of them at the same time.

Notepad++
Hinted
![image](https://github.com/user-attachments/assets/f3473b78-4328-47d0-b0d9-6702e0fe52e2)
Unhinted
![image](https://github.com/user-attachments/assets/27e23c37-9555-4e75-8f5a-7604878184c4)

The unhinted version is taller, thinner and a mixed bag of blurry and sharp characters in my case. 

Maybe hinting issue is related to aligning "i" and "f" letters in this release? I don't know, but I can imagine that the autohinter could move things up or down using some baseline like "the line in f is at this level so lets move letter 9 to match it" or something like that.

**Comment by subframe7536** [comment]
> The unhinted version is taller, thinner and a mixed bag of blurry and sharp characters in my case.

Seems that your monitor's resolution is less or equal than 1080P, so that the hinted version is a better choice.

> Maybe hinting issue is related to aligning "i" and "f" letters in this release? I don't know, but I can imagine that the autohinter could move things up or down using some baseline like "the line in f is at this level so lets move letter 9 to match it" or something like that.

Your speculation is reasonable. I'm lack of knowledge about font hint, and indeed I increase 10 in height to provide more rooms for a rounder top stem of `f`. I will try to rollback it and provide you a new test version later.

**Comment by subframe7536** [comment]
Here is the updated ttf in regular and italic style
[TTF.zip](https://github.com/user-attachments/files/17959760/TTF.zip)

**Comment by chmielcode** [comment]
It appears unhinted so the problem does not exist for me with this updated TTF. 
I've used ttfautohint on it with default* settings:

b29 hinted
![obraz](https://github.com/user-attachments/assets/dc05e955-4907-4e1b-8fa5-d6a7af2318e3)
updated ttf with ttfautohint default settings
![obraz](https://github.com/user-attachments/assets/4e14716a-5bc7-4d9a-a5c2-24080b28dac0)
"9" looks ok now :)

*I think your settings generate slightly better hinting (taller "i"), so I'm not suggesting any change here

**Comment by subframe7536** [comment]
Oh, I just upload the wrong file... Here is the hinted one [TTF-AutoHint.zip](https://github.com/user-attachments/files/17963655/TTF-AutoHint.zip)


> I'm using 1440p WQHD monitor with 150% scaling.

Weird, the unhinted version has better rendering effect than hinted version under this resolution based on my experience.

**Comment by atauzki** [comment]
![image](https://github.com/user-attachments/assets/6cf75b28-59c7-42e8-8d56-65636c0ceaef)

**Comment by subframe7536** [comment]
@chmielcode @atauzki Cound you please also try `JetBrains Mono` to test if this issue exists? If not, I think I should rollback to follow its design.

**Comment by atauzki** [comment]
> @chmielcode @atauzki Cound you please also try `JetBrains Mono` to test if this issue exists? If not, I think I should rollback to follow its design.
jetbrains mono:
![image](https://github.com/user-attachments/assets/083645c8-26ac-4ee3-a0d0-af0d431d1b66)

**Comment by atauzki** [comment]
I think move the "-" of "f" down a bit is also okay.

**Comment by subframe7536** [comment]
[TTF-AutoHint.zip](https://github.com/user-attachments/files/17965470/TTF-AutoHint.zip)

**Comment by atauzki** [comment]
> [TTF-AutoHint.zip](https://github.com/user-attachments/files/17965470/TTF-AutoHint.zip)

![image](https://github.com/user-attachments/assets/61709852-61f9-4743-98bf-773491af14d5)

**Comment by subframe7536** [comment]
[TTF-AutoHint.zip](https://github.com/user-attachments/files/17965539/TTF-AutoHint.zip)

**Comment by atauzki** [comment]
seems no difference.
![image](https://github.com/user-attachments/assets/246d012a-4395-49d0-87ba-559785af6d7e)

**Comment by subframe7536** [comment]
[TTF-AutoHint.zip](https://github.com/user-attachments/files/17965556/TTF-AutoHint.zip)

![PixPin_2024-11-30_21-38-35](https://github.com/user-attachments/assets/438db9d6-cf51-4129-8c36-827ccd7ff35a)

**Comment by atauzki** [comment]
![image](https://github.com/user-attachments/assets/b2a6aebb-0092-4847-acf8-cf0bc4a31aac)

**Comment by subframe7536** [comment]
Have you try to uninstall them first and then reinstall them?

**Comment by atauzki** [comment]
yes, every time.

**Comment by subframe7536** [comment]
In all styles: [TTF-AutoHint.zip](https://github.com/user-attachments/files/17965645/TTF-AutoHint.zip)

**Comment by atauzki** [comment]
![image](https://github.com/user-attachments/assets/bafc1b7e-6f22-44ca-9691-424e282c1cac)

**Comment by subframe7536** [comment]
unhinted version: [TTF.zip](https://github.com/user-attachments/files/17965719/TTF.zip)

> hinted `f` in 400 and 700 weight seems are still worst-looking.

The `f` is rollback to beta29 to match the stem metric of `f` in JetBrains Mono

**Comment by atauzki** [comment]
I just built it myself without ligatures and hinting
![image](https://github.com/user-attachments/assets/f5693f25-4cdf-45ce-bd2d-15e08f12f548)

**Comment by subframe7536** [comment]
@chmielcode In order to control the variables, I have created an additional test version. Could you please have it a try to see if `9` is misaligned?
[MapleMono-Regular.zip](https://github.com/user-attachments/files/18001129/MapleMono-Regular.zip)

**Comment by atauzki** [comment]
> @chmielcode In order to control the variables, I have created an additional test version. Could you please have it a try to see if `9` is misaligned? [MapleMono-Regular.zip](https://github.com/user-attachments/files/18001129/MapleMono-Regular.zip)

![图片](https://github.com/user-attachments/assets/6faf4291-bb4b-42b8-9f53-6dd4b12d1cce)

**Comment by subframe7536** [comment]
Thanks! So the source file in the repo now is the correct version

**Comment by atauzki** [comment]
@subframe7536 a typo, should be "archive"
![image](https://github.com/user-attachments/assets/81bf57db-17d9-480c-a2ac-81e62e7dc4c9)

**Comment by chmielcode** [comment]
> > @chmielcode In order to control the variables, I have created an additional test version. Could you please have it a try to see if `9` is misaligned? [MapleMono-Regular.zip](https://github.com/user-attachments/files/18001129/MapleMono-Regular.zip)
> 
> ![图片](https://private-user-images.githubusercontent.com/19769843/392198635-6faf4291-bb4b-42b8-9f53-6dd4b12d1cce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMjc1OTYsIm5iZiI6MTczMzMyNzI5NiwicGF0aCI6Ii8xOTc2OTg0My8zOTIxOTg2MzUtNmZhZjQyOTEtYmI0Yi00MmI4LTlmNTMtNmRkNGIxMmQxY2NlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDE1NDgxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyMzJiNjU0MDg1NDc3ZDI5YjY0ZjBhOTg4YjJmMTczNWYwYWMzNTk1MmJjNzZiYzJlZTRiYjIyZTk3M2RkYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.iP4GUvOYkoe3QTCACW4SIXfFUWW535lEUhaLKcovbk0)

Thank you. I really can't tell if it's a little bit lower or not, but "9" still stands out.
b29
![obraz](https://github.com/user-attachments/assets/ee1c256e-28a3-46a6-ab31-cc90078e1ef1)
attached file
![obraz](https://github.com/user-attachments/assets/d3fa3577-705f-4d15-bf7e-e272e7efd73c)


Also the dot above "i" is different:
b29
![obraz](https://github.com/user-attachments/assets/b4dc1be1-26d4-41a4-ace4-87ce1e39caa0)
attached file
![obraz](https://github.com/user-attachments/assets/35ac2bd9-d3bb-474b-9947-262d7f996535)
Test version's dot is slightly off, but I guess I wouldn't have noticed it if I didn't switch from new to old a couple of times to specifically look for differences.

**Comment by subframe7536** [comment]
Yeah, now I can confirm that the issue on `9` is caused by the updated `f` in beta30.

And, `i` in beta30 or attached file aligns its shape in JetBrains Mono

**Comment by subframe7536** [comment]
Release in v7.0-beta31
