### ISSUE TITLE
feature request: ligature for warning

### ISSUE THREAD

**Issue by atauzki** [subframe7536/maple-font#282]
ligature for `[warn]`
![image](https://github.com/user-attachments/assets/40ea4ad1-f021-4cac-b300-c39bbd678e5b)

no ligature for `[warning]`
![image](https://github.com/user-attachments/assets/4707ce71-802d-4976-b357-bdca9f130cac)

**Comment by subframe7536** [comment]
And I have thought about this feature before, but it is not on the roadmap to v7.

I plan to create a seperate font file for testing new features, including more tags, more ligatures, and then, merge them at build time.

**Comment by atauzki** [comment]
okay. too many features is not so important.
