### ISSUE TITLE
latest commit breaks bold italic letter "g"

### ISSUE THREAD

**Issue by atauzki** [subframe7536/maple-font#283]
7.0b30 is OK, but latest commit has this problem.
![image](https://github.com/user-attachments/assets/ada3a04f-6f89-4845-9a0e-85db0ac32ca7)

**Comment by subframe7536** [comment]
Thanks for reporting! Just fix it.

**Comment by subframe7536** [comment]
[TTF-AutoHint.zip](https://github.com/user-attachments/files/17965470/TTF-AutoHint.zip)

**Comment by atauzki** [comment]
I need a bold italic version to see that.

**Comment by subframe7536** [comment]
With bold and bold italic [TTF-AutoHint.zip](https://github.com/user-attachments/files/17965556/TTF-AutoHint.zip)

**Comment by atauzki** [comment]
solved.
