### ISSUE TITLE
关于maple-UI

### ISSUE THREAD

**Issue by skyworldp** [subframe7536/maple-font#284]
在使用mactype+自定义脚本的情况下 windows自带的部分软件的字体出现乱码 例如 运行  任务管理器  
![image](https://github.com/user-attachments/assets/cf07a4cb-b6d1-4dcb-b0b7-2f9262e4dfd1)

**Comment by subframe7536** [comment]
新版 MacType 是这样的，我已经转向 MiSans 了

**Comment by skyworldp** [comment]
我其实没太懂 为什么换字体一定要配mactype 如果只换字体会有什么影响么 或者说 如果用misans就可以规避这种影响？

**Comment by subframe7536** [comment]
MacType 主要还是优化渲染效果，换字体只是顺带的，你去酷安上找那种字体替换包也可以，只是无法排除程序，同时更新后需要重新替换。

至于乱码，我也搞不太懂。。。现在处于养老阶段了，能用就行。。。
