### ISSUE TITLE
有没有下载文件名的说明？

### ISSUE THREAD

**Issue by DOSforever** [subframe7536/maple-font#285]
下载的各个字体文件名都代表什么意思？使用上有没有区别？
Maple UI 和 Maple Hand 是不是不包含在 asset 中，必须要单独下载？

**Comment by DOSforever** [comment]
多谢回复。另外这些 FAQ 最好能写在项目首页的说明上。

**Comment by subframe7536** [comment]
感谢建议，正在写landing page，会在里面详细介绍
