### ISSUE TITLE
Missing character variant for numbersign ( # ) in v7. 

### ISSUE THREAD

**Issue by mattatticus** [subframe7536/maple-font#286]
I messed around with the configs and I cannot find the character variant for numbersign `#` in v7 which is in v6.

I am building the nerd font v7 from source. 

![v6_char_variants](https://github.com/user-attachments/assets/6e310dfc-3ca5-449b-b049-a458d5066141)

**Comment by subframe7536** [comment]
`#` is no longer special in v7, just looks like other fonts.

**Comment by mattatticus** [comment]
I would like to see it again in v7 if possible. But anyways thanks for the help.

**Comment by subframe7536** [comment]
see in #252

**Comment by subframe7536** [comment]
But maybe come back as a Character Variant after v7 release

**Comment by mattatticus** [comment]
Ok then. You can close this issue. Thanks for the help.
