### ISSUE TITLE
Looks like there is a regression. CV 33 does not seem to work

### ISSUE THREAD

**Issue by vikky49** [subframe7536/maple-font#287]
This is my configuration in the preset-normal.json 

```
{
  "$schema": "./schema.json",
  "family_name": "Maple Mono Normal",
  "use_hinted": true,
  "pool_size": 4,
  "ligature": true,
  "feature_freeze": {
    "cv01": "enable",
    "cv02": "ignore",
    "cv03": "enable",
    "cv04": "ignore",
    "cv31": "ignore",
    "cv32": "ignore",
    "cv33": "ignore",
    "cv34": "enable",
    "cv35": "enable",
    "cv36": "enable",
    "cv98": "ignore",
    "cv99": "ignore",
    "ss01": "ignore",
    "ss02": "ignore",
    "ss03": "ignore",
    "ss04": "ignore",
    "ss05": "enable",
    "ss06": "enable",
    "ss07": "enable",
    "ss08": "enable",
    "zero": "ignore"
  },
```

and I Ran the build using 

` python build.py --normal
`
<img width="498" alt="Maple Mono Normal 2024-12-03 18-59-30" src="https://github.com/user-attachments/assets/b6b90c2c-5601-4c2f-9cce-568eb9f40552">

I am expecting the I like with tail and bent. It used to work like that in the past . Only changed after today update 

Once again great work

**Comment by subframe7536** [comment]
Seems work for me.
![PixPin_2024-12-04_09-34-03](https://github.com/user-attachments/assets/00980657-5e43-432d-a8b5-cc7e8f6e2701)

You can see the real config in the last line of build log or in https://fontdrop.info/
![PixPin_2024-12-04_09-32-22](https://github.com/user-attachments/assets/91538685-d1e4-4b79-91f3-079bd9317f1f)
