### ISSUE TITLE
cv31, cv33, and cv35 interaction problems

### ISSUE THREAD

**Issue by Benna96** [subframe7536/maple-font#294]
Version: V7.01 Beta31  
Build: Variable, Ligature, Italic

Was testing out the font on a [site that lets you preview a variable font](https://www.axis-praxis.org/specimens/__DEFAULT__), as I don't have font software that would let me preview it. I'm not sure if the site has an issue, or if it's the font, there's weird stuff going on with cv31, cv33 & cv35.

I'll call them A, I, and L, hard to keep track of the codes.
A = cv31, alternate a  
I = cv33, alternate i
L = cv35, alternate l

| None on | A & I 👍 | L 😕 | (A or I) + L ☹️ |
| - | - | - | - |
| ![{888257F8-BDCB-42C1-8440-8DD58D4078F8}](https://github.com/user-attachments/assets/b6e2f8dc-3798-4385-bcd7-94a0c8e11fd5) | ![{CACD8BBF-CCF7-431E-BA5B-8435CD27AB1D}](https://github.com/user-attachments/assets/91a85426-a5e3-4b8f-9567-e72124ccaa9b) | ![{2C6D8542-0F36-4B82-9E39-A8329153A1B5}](https://github.com/user-attachments/assets/b6883afc-4b55-4082-a491-e2eb8422f7f2) | ![{D92D1997-7663-4B78-8A89-DC969FE0783C}](https://github.com/user-attachments/assets/e38d9158-34bd-4465-aadd-663be52ec1af) |
| | | Changes preceding I too | A & I change following L too |

**Comment by subframe7536** [comment]
Thanks for reporting, I will fix them in next release

**Comment by subframe7536** [comment]
[MapleMono-Italic.zip](https://github.com/user-attachments/files/18121951/MapleMono-Italic.zip)

**Comment by Benna96** [comment]
Can confirm it's fixed :) I'll close the issue.
