### ISSUE TITLE
V7.0 Beta31在kitty下不被识别为字体

### ISSUE THREAD

**Issue by genskyff** [subframe7536/maple-font#295]
我在macOS上使用[kitty](https://github.com/kovidgoyal/kitty)作为终端模拟器，并配置了maple作为字体。

kitty的字体配置如下：

```
font_family      family="Maple Mono NF CN"
```

在V7.0 Beta30及之前，都是没有问题的，可以正常显示字体。
但当我更新到V7.0 Beta31版本后，就出现了显示异常，发现kitty没有识别出最新版本字体。

使用kitty自带的用于选择字体的工具，这会列出可用字体列表：

```shell
kitten choose-fonts
```

发现V7.0 Beta31并不会在可选字体列表中显示，而Beta30则可以。

不清楚这是kitty本身的问题（kitty仅会列出mono字体），还是字体的问题，但是在这期间我并没有更新过kitty

PS：
- Beta30我下载的是MapleMono-NF-CN，Beta31我下载的是MapleMono-NF-CN-unhinted
- 该问题可以在我的机器上稳定复现，且不论是删了字体重新安装还是覆盖安装都会出现

**Comment by subframe7536** [comment]
🤔

有试过 Maple Mono NF 吗？

**Comment by genskyff** [comment]
似乎从31版开始和以往的下载方式不同？（指下载的类型数量），是不是这部分修改导致了问题

**Comment by subframe7536** [comment]
如果 Maple Mono 也无法识别的话需要之后检查一下字体本身了

**Comment by subframe7536** [comment]
找到问题了，你可以先用 github action 自行构建，需要将 `config.json` 中 `"nerd_font.use_font_patcher"` 设置为 `true`

**Comment by genskyff** [comment]
感谢！这个会在下个版本修复吧

**Comment by subframe7536** [comment]
是的，预计这周末发。修复内容我已经推送了，你也可以自行构建

**Comment by genskyff** [comment]
用最新的commit构建了一下，已经可以正确识别了

**Comment by subframe7536** [comment]
Release in v7.0-beta31
