### ISSUE TITLE
摄氏度℃的符号缺失

### ISSUE THREAD

**Issue by RocSun7** [subframe7536/maple-font#296]
你好，
如题，摄氏度显示存在问题，操作系统为windows10 22H2 19045.5131，
软件为matlab 2022b，安装使用的字体是Maple Mono NF CN
![image](https://github.com/user-attachments/assets/01ff6abf-1597-4070-a568-078e4b28bdaa)
![image](https://github.com/user-attachments/assets/22ba96da-66ea-4a13-a5f8-20f9b6fbdf5d)

**Comment by subframe7536** [comment]
感谢反馈，下版本加上，宽度和英文字符一致

**Comment by subframe7536** [comment]
更新已推送，可自行构建

**Comment by RocSun7** [comment]
> 更新已推送，可自行构建

好的，谢谢

**Comment by CoelacanthusHex** [comment]
其实 Unicode 标准已经不推荐使用这两个字符了，标准推荐使用度的符号「°」和字母 C/F 组合起来，即°C和°F。当然对于字体肯定是要支持的。

**Comment by subframe7536** [comment]
Release in v7.0-beta31
