### ISSUE TITLE
Apply stylistic set cv02 to cyrilic letter

### ISSUE THREAD

**Issue by capiet** [subframe7536/maple-font#303]
Hello! Thank you for this wonderful font, and I'd like to ask you to think about applying the stylistic set cv02 for 'a' letter also for the cyrillic letter 'a'. Now it seems a bit weird, because in text there are letters 'a' in two different styles, so it's impossible to use this set for both letters.

![изображение](https://github.com/user-attachments/assets/c1a1e8ef-fe2b-4a62-89be-35de361cc7f9)

**Comment by subframe7536** [comment]
Thanks for reporting, I will fix it in next beta release.

**Comment by capiet** [comment]
> Thanks for reporting, I will fix it in next beta release.

Thank you for the reply and your help!

**Comment by subframe7536** [comment]
Fixed. If you want to get the update now, you can build it using [GitHub Action](https://github.com/subframe7536/maple-font?tab=readme-ov-file#use-github-actions)

**Comment by capiet** [comment]
Thanks but I'll wait for a next beta release!

**Comment by subframe7536** [comment]
Release in v7.0-beta33
