### ISSUE TITLE
Can I enable only part of the ligatures?

### ISSUE THREAD

**Issue by abcdvvvv** [subframe7536/maple-font#304]
Can I enable only part of the ligatures?
For example, I don't want =:, .= ligatures.

**Comment by subframe7536** [comment]
Currently, no first-class support.

You can write some python script using `fonttools.feaLib`.

**Comment by abcdvvvv** [comment]
I see. I'll just use it as it is, I don't want to write python scripts. Thank you.

**Comment by subframe7536** [comment]
Now it is supported by custom build with flag `--apply-feat-file`
