### ISSUE TITLE
中英文不是2:1吗？

### ISSUE THREAD

**Issue by winsphinx** [subframe7536/maple-font#305]
![image](https://github.com/user-attachments/assets/d2c868f9-419d-4e7b-93bc-97ded7165302)
是这样吗？

**Comment by subframe7536** [comment]
需要用 `Maple Mono CN` 或者 `Maple Mono NF CN`，你这个不包含中文字符，自动回退到默认字体了

**Comment by winsphinx** [comment]
谢谢，我下载试了这几个，中文完美了，但是好像没有连字？
![image](https://github.com/user-attachments/assets/2e2a5918-a20d-40c9-8a1c-47c1f13136e0)
![image](https://github.com/user-attachments/assets/e86e522f-ab69-41c4-b10c-f5b822c010c1)

**Comment by subframe7536** [comment]
emacs的连字有开吗

**Comment by winsphinx** [comment]
> emacs的连字有开吗

开的，之前用iosveka，能显示，就是那个字体太窄了，费眼。
