### ISSUE TITLE
网页搭配Mactype助手使用更佳

### ISSUE THREAD

**Issue by brucmao** [subframe7536/Maple-font#34]
我在用Mactype助手这个油猴脚本，看起来还不错
https://www.youxiaohou.com/tool/install-mactype.html

**Comment by subframe7536** [comment]
有过参考，但是原理就是这一行，因为是[自用](https://github.com/subframe7536/UserScript/blob/c491adf97d63f346ea7b5898e822c2c38d64a89c/userscript.js#L205)的所以就没做调节的ui
```css
*:not(pre) { -webkit-text-stroke: ${val}px !important; text-stroke: ${val}px !important }
```
