### ISSUE TITLE
The line height of “Maple Mono SC NL” is too small

### ISSUE THREAD

**Issue by pan93412** [subframe7536/Maple-font#42]
- Environment: macOS Monterey 12.5.1
- Programs:
  - Figure 1: iTerm2
  - Figure 2: VS Code, in main panel & terminal panel

The line height of “Maple Mono SC NL” v5.0 is much better to v5.5, and much similar to JetBrains Mono v2.242. Hope the line height changes can be reverted! 🙏

## Before (5.0)

<img width="620" alt="image" src="https://user-images.githubusercontent.com/28441561/189483193-217017db-5bf9-43e8-b7e0-d84d867da556.png">

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/28441561/189483324-1a1d3c4f-6688-47d5-bd15-53c06697070e.png">

## After (5.5)

<img width="708" alt="image" src="https://user-images.githubusercontent.com/28441561/189482964-e6f6a260-d3de-408f-86f3-625ff90ad953.png">

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/28441561/189483018-3b8c15bb-b305-4a98-a3b6-17b09a79088e.png">

## JB Mono

<img width="696" alt="image" src="https://user-images.githubusercontent.com/28441561/189483256-0749e715-89c2-4e7d-9867-d6c3323e3318.png">

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/28441561/189483208-4606c72b-a650-417d-a2c1-f473ce025aaa.png">

**Comment by subframe7536** [comment]
請問有嘗試過重啓嗎？#9 這個問題最後重啓解決了，我這邊暫時沒發現問題

**Comment by pan93412** [comment]
> 請問有嘗試過重啓嗎？#9 這個問題最後重啓解決了，我這邊暫時沒發現問題

我這裡重啟過了，但也沒有解決問題。是直到把 SC NL 降級到 5.0 才恢復成能看的樣子。

**Comment by subframe7536** [comment]
...可能得我之後有時間的時候試著修復了，現在比較忙，盡量在下一版修復🥲

**Comment by subframe7536** [comment]
move to #43

**Comment by subframe7536** [comment]
我大概找到原因了，可能是在merge的中文字體的原因，可以試試這個
[MapleMono-SC-NF-Regular-fix.zip](https://github.com/subframe7536/Maple-font/files/9540556/MapleMono-SC-NF-Regular-fix.zip)

**Comment by pan93412** [comment]
> MapleMono-SC-NF-Regular-fix.zip

<img width="1372" alt="image" src="https://user-images.githubusercontent.com/28441561/189488667-0cf0511d-abee-4e1e-84b1-5afe5cc67881.png">

Seems better now?

**Comment by subframe7536** [comment]
Sure, that's it. fix at next version
