### ISSUE TITLE
Mac VS Code 里使用中文时字符长度与预期不符

### ISSUE THREAD

**Issue by Eureka-0** [subframe7536/Maple-font#44]
<img width="952" alt="image" src="https://user-images.githubusercontent.com/56858288/189614654-3834e38a-12e7-4040-bf79-14add8576f4a.png">

如图，使用英文时正常在标尺处自动换行，但使用中文时会超出标尺很多才自动换行。

VS Code 中相关设置如下，

<img width="270" alt="image" src="https://user-images.githubusercontent.com/56858288/189615244-f056e1ff-0ca8-4163-918c-cd91280f3d10.png">

**Comment by subframe7536** [comment]
感谢反馈，这个我需要研究一下

**Comment by subframe7536** [comment]
转移到 #43，可以先使用 [更纱黑体 mono sc nerd](https://github.com/be5invis/Sarasa-Gothic)，这个没有问题

**Comment by subframe7536** [comment]
已定位问题，但是没有比较好的解决方法
目前的字符宽度：英文是1200，中文是2400，单位宽度em是2000，这个比例显示的间距是比较好的
这个问题可能是由于计算个数是根据字符本身宽度和em的最小值来的，导致中文字符会多一些，em改成2400就能正确换行了
![image](https://user-images.githubusercontent.com/78338239/203238469-341f0755-ccd3-4cab-bbdb-78a1b980a177.png)
但是这样以来整体的字体大小就会比正常的小，编辑器内可以改字体大小，但是其他地方就不方便调整
也试过改变字形，但是会和 更纱黑体 一样，字母和数字会偏细长，和最初的目的相违背了

**Comment by subframe7536** [comment]
解决方案：https://github.com/subframe7536/maple-font/issues/173#issuecomment-2002842572
