### ISSUE TITLE
windows的cmd或powershell支援?

### ISSUE THREAD

**Issue by Lincutt** [subframe7536/Maple-font#45]
先感謝辛勞製作這麼漂亮的字體~👍
不過沒辦法用在win10原版的cmd跟powershell上感覺有點可惜
不套Windows Terminal的情況下似乎無法選擇

另外再請問有打算做fixed版的嗎?
就是不含連字的版本

謝謝

**Comment by Lincutt** [comment]
先感謝辛勞製作這麼漂亮的字體~👍
不過沒辦法用在win10原版的cmd跟powershell上感覺有點可惜
不套Windows Terminal的情況下似乎無法選擇

另外再請問有打算做fixed版的嗎?
就是不含連字的版本

謝謝

**Comment by subframe7536** [comment]
感謝肯定♥
原版cmd確實無法使用，我會在下一個版本嘗試修復，現在可以使用[更紗黑體 mono sc nerd](https://github.com/be5invis/Sarasa-Gothic)，這個字體支持在原版cmd使用，同樣也包含nerd font

> 另外再請問有打算做fixed版的嗎? 就是不含連字的版本

連字應該可以自行選擇是否開啓，可以描述一下無法選擇是否開啓連字的情況嗎？

**Comment by Lincutt** [comment]
> 連字應該可以自行選擇是否開啓，可以描述一下無法選擇是否開啓連字的情況嗎？

可以關的嗎@@?
請問要怎麼關🤣
(使用Windows Terminal跟VScode的情況下)

**Comment by subframe7536** [comment]
想起來，原版cmd無法選擇可能是編碼的問題，可以試試[這個修復版](https://github.com/subframe7536/Maple-font/issues/42#issuecomment-1242741106)

vscode似乎只能同編輯器的連字一起控制
```
"editor.fontLigatures": "false"
```

windows terminal需要修改`setting.json`
```json
{
  "profiles": {
    "defaults": {
      "colorScheme": "One Half Dark",
      "font": {
        "face": "Maple Mono SC NF",
        "size": 12,
+       "features": { "calt": 0 }
      },
      "startingDirectory": "D:\\code\\temp",
      "useAcrylic": true
    },
  }
}
```

**Comment by Lincutt** [comment]
> 想起來，原版cmd無法選擇可能是編碼的問題，可以試試[這個修復版](https://github.com/subframe7536/Maple-font/issues/42#issuecomment-1242741106)

這個試了還是不行
有在網路上找到這些條件
給你參考看看

```
The fonts must meet the following criteria to be available in a command session window:

The font must be a fixed-pitch font.
The font cannot be an italic font.
The font cannot have a negative A or C space.
If it is a TrueType font, it must be FF_MODERN.
If it is not a TrueType font, it must be OEM_CHARSET.

Additional criteria for Asian installations:

If it is not a TrueType font, the face name must be “Terminal.”
If it is an Asian TrueType font, it must also be an Asian character set.
```

> vscode似乎只能同編輯器的連字一起控制
> 
> ```
> "editor.fontLigatures": "false"
> ```
> 
> windows terminal需要修改`setting.json`
> 
> ```json
> {
>   "profiles": {
>     "defaults": {
>       "colorScheme": "One Half Dark",
>       "font": {
>         "face": "Maple Mono SC NF",
>         "size": 12,
> +       "features": { "calt": 0 }
>       },
>       "startingDirectory": "D:\\code\\temp",
>       "useAcrylic": true
>     },
>   }
> }
> ```

感謝!
馬上來改👍
連字用不太習慣😂

**Comment by subframe7536** [comment]
> 另外有在網路上找到這些原版cmd字型的條件 給你參考看看
> 
> ```
> The fonts must meet the following criteria to be available in a command session window:
> 
> The font must be a fixed-pitch font.
> The font cannot be an italic font.
> The font cannot have a negative A or C space.
> If it is a TrueType font, it must be FF_MODERN.
> If it is not a TrueType font, it must be OEM_CHARSET.
> 
> Additional criteria for Asian installations:
> 
> If it is not a TrueType font, the face name must be “Terminal.”
> If it is an Asian TrueType font, it must also be an Asian character set.
> ```

感謝👌

轉移到 #43
