### ISSUE TITLE
提供一个`Q`的变体

### ISSUE THREAD

**Issue by Photonico** [subframe7536/Maple-font#51]
https://raw.githubusercontent.com/Photonico/Fira_Comp/master/Workspace/Q_Fira_Comp_Regular.eps

来源于我的个人字体, 我实在没有精力折腾它了, 但是又非常非常喜欢这种 Q.
希望能采纳, >w<

**Comment by subframe7536** [comment]
仔细看了一下，可能比较适合放在Italic中...

**Comment by Photonico** [comment]
> 

希望能采纳这个风格...
p.s. 话说我最近偶尔也编辑一些字体, 用 fontforge, 设计比较复杂的符号和字体的时候, 比如 `g` `@` `&` , 半天就整一个字符出来, 
想到还要给它做一套 Italic, 头都大了...

**Comment by subframe7536** [comment]
> 希望能采纳这个风格... 

说实话，这个风格和regular整体规整的风格不搭，斜体里面我可以做一个styleset放进去

> p.s. 话说我最近偶尔也编辑一些字体, 用 fontforge, 设计比较复杂的符号和字体的时候, 比如 `g` `@` `&` , 半天就整一个字符出来, 想到还要给它做一套 Italic, 头都大了...

我用的是font creator + AI，感觉还行

**Comment by Photonico** [comment]
> > 希望能采纳这个风格...
> 
> 说实话，这个风格和regular整体规整的风格不搭，italic里面我可以做一个styleset放进去
> 
> > p.s. 话说我最近偶尔也编辑一些字体, 用 fontforge, 设计比较复杂的符号和字体的时候, 比如 `g` `@` `&` , 半天就整一个字符出来, 想到还要给它做一套 Italic, 头都大了...
> 
> 我用的是font creator + AI，感觉还行

我终于还是把我个人字体折腾好了(只是能用)，感兴趣可以看一下: https://github.com/Photonico/Photonico_Code

**Comment by subframe7536** [comment]
> 我终于还是把我个人字体折腾好了(只是能用)，感兴趣可以看一下: https://github.com/Photonico/Photonico_Code

试了一下，很不错！

**Comment by Photonico** [comment]
> > 我终于还是把我个人字体折腾好了(只是能用)，感兴趣可以看一下: https://github.com/Photonico/Photonico_Code
> 
> 试了一下，很不错！

我手头只有 Linux 设备 (KDE桌面) 不知道在其他系统上体验如何。Italic 体我是弄不动了 T.T ，如果你感兴趣的话，可以一起搞或者fork 过去。

**Comment by leizton** [comment]
字符间距太大了
