### ISSUE TITLE
Maple Mono SC NF 字体显示异常

### ISSUE THREAD

**Issue by brucmao** [subframe7536/Maple-font#54]
下图为Window Terminal 字体为Maple Mono SC NF(V5.6 Pre-Release) ,系统为Ubuntu 22.04(wsl2) 
![Snipaste_2022-11-02_09-23-56](https://user-images.githubusercontent.com/6119652/199374136-964b65db-03eb-40db-ad55-e4a243f173ff.png)

Windows Terminal 字体设置为 MesloLGS NF 显示正常
![Snipaste_2022-11-02_09-23-33](https://user-images.githubusercontent.com/6119652/199374304-32add699-f728-4ae7-ada5-bb26f22becd1.png)

**Comment by subframe7536** [comment]
![image](https://user-images.githubusercontent.com/78338239/199376151-adcb8dee-da6c-4acb-b3cb-93fe5435d625.png)
与繁体冲突，生成NF的时候跳过了，可以用`Maple Mono NF`，wt里面callback的中文字体也还行
