### ISSUE TITLE
sublime 光标位置异常

### ISSUE THREAD

**Issue by brucmao** [subframe7536/Maple-font#55]
使用字体，Maple Mono SC NF，此时输入文字，会在“放”的前面输入

![image](https://user-images.githubusercontent.com/6119652/199865065-d4e0dfa5-62e7-429b-b22b-902216c37caa.png)

**Comment by subframe7536** [comment]
感谢反馈，这个问题可能和 #44 类似，我需要研究一下，可以先使用 [更纱黑体 mono sc nerd](https://github.com/be5invis/Sarasa-Gothic)，这个没有问题

**Comment by brucmao** [comment]
好的，我先换字体

**Comment by subframe7536** [comment]
v6已修复
