### ISSUE TITLE
Feature Request: Support for accents

### ISSUE THREAD

**Issue by arkhan** [subframe7536/Maple-font#56]
I really like this font, the only problem is that accents are not supported. Can you add support for accents?
![image](https://user-images.githubusercontent.com/3141865/200051723-73c4171e-e8fb-4709-89cf-1619ac22ed63.png)

Thanks

**Comment by subframe7536** [comment]
I'll take it into consider

**Comment by subframe7536** [comment]
![image](https://user-images.githubusercontent.com/78338239/210075471-f1274269-5da5-451b-8f14-26d40d17b54f.png)
sorry but I known little about accents, is it enough to use base set of accents for normal use?

**Comment by arkhan** [comment]
> ![image](https://user-images.githubusercontent.com/78338239/210075471-f1274269-5da5-451b-8f14-26d40d17b54f.png) sorry but I know little about accents, is it enough to use standard set of accents for normal usage?

Yes, thanks.

**Comment by subframe7536** [comment]
![image](https://user-images.githubusercontent.com/78338239/210081112-7d4178c8-2ce0-4efb-bd12-55316ea9e8b1.png)
ok, these will be added at next version
