### ISSUE TITLE
某些情况下显示多了点东西

### ISSUE THREAD

**Issue by darkhandz** [subframe7536/maple-font#57]
我在doom-emacs里显示有点问题, 数字的右边多了点东西, 请帮忙看看是否字体原因

![Snipaste_2022-11-08_21-47-27](https://user-images.githubusercontent.com/2143333/200620572-f7ec0e11-e3fe-4388-bffe-b0f920461bff.png)

**Comment by subframe7536** [comment]
这个真不清楚...regular也是这样吗？

**Comment by darkhandz** [comment]
代码编辑区域里似乎没出现过类似的问题

![image](https://user-images.githubusercontent.com/2143333/200876429-3271cedd-b03d-4737-ad0e-2357c2fa37ed.png)

**Comment by darkhandz** [comment]
![image](https://user-images.githubusercontent.com/2143333/200878167-cb80d02b-d213-4b18-bd42-d4b4b4ea4efd.png)

**Comment by subframe7536** [comment]
可能是行号宽度的问题

能否试一下
1. 把行号宽度加大
2. 行号字体样式使用regular而不是italic
