### ISSUE TITLE
Maple.hand

### ISSUE THREAD

**Issue by NONONO1V** [subframe7536/Maple-font#6]
可以修复一下Maple.hand的省略号吗

**Comment by subframe7536** [comment]
可以详细描述一下问题吗，最好有个截图

**Comment by NONONO1V** [comment]
[](url
![2022-08-06_09-30-16](https://user-images.githubusercontent.com/109849776/183228361-92125253-33bb-4525-8608-297b61b4b22d.jpg)
)

**Comment by subframe7536** [comment]
好的，这一版修复

**Comment by NONONO1V** [comment]
谢谢
