### ISSUE TITLE
无法显示的字符的问号占位符占用了两个字符宽度

### ISSUE THREAD

**Issue by CarterLi** [subframe7536/Maple-font#61]
Maple

<img width="651" alt="image" src="https://user-images.githubusercontent.com/6134068/203920430-b013674b-f9ec-4982-9009-ad1ed5885b84.png">

期望 (Iosevka Nerd Font Mono)

<img width="586" alt="image" src="https://user-images.githubusercontent.com/6134068/203920475-07c18064-68e6-46fe-9964-598698dab275.png">

[Sarasa-Mono-SC-Nerd](https://github.com/laishulu/Sarasa-Mono-SC-Nerd) 也有类似的问题，只不过[Sarasa-Mono-SC-Nerd](https://github.com/laishulu/Sarasa-Mono-SC-Nerd)是所有 nerd 字符都有。https://github.com/laishulu/Sarasa-Mono-SC-Nerd/issues/19

**Comment by subframe7536** [comment]
应该是无解的

这是fallback的字体，不在nerd font里面，显示宽度根据em（2000）定的，占位宽度根据字符本身宽度（1200）定的

**Comment by CarterLi** [comment]
那为什么Iosevka Nerd Font Mono是好的呢？

**Comment by subframe7536** [comment]
因为字体里没有中文字符

**Comment by CarterLi** [comment]
这就很蛋疼。。。
能把 nerd 字符改成占位两字符宽度吗？现在那么窄也不好看

**Comment by subframe7536** [comment]
最开始就是两个字宽的，太丑了所以换成一个了
