### ISSUE TITLE
字体不能被识别为等宽字体，导致Windows控制台里不能使用Maple Mono SC NF

### ISSUE THREAD

**Issue by huge-pancake** [subframe7536/Maple-font#62]
如题。
![image](https://user-images.githubusercontent.com/73375859/207280429-14be9c38-edc2-4c76-b5c2-b383ea5f2c41.png)

**Comment by subframe7536** [comment]
SC NF是最新版吗？
我在旧cmd界面上是可以的？
![image](https://user-images.githubusercontent.com/78338239/207289051-350af02c-e4d6-475a-be19-0db4743c8e67.png)

**Comment by huge-pancake** [comment]
是最新版（5.5，包含中文）。
在 CMD, Powershell, MSYS2 里都不行

CMD
![image](https://user-images.githubusercontent.com/73375859/207306013-d9e19fe4-c8f2-4789-b4a8-ba398158d2ec.png)

PWSH 7.3 (和Windows自带的效果一样)
![image](https://user-images.githubusercontent.com/73375859/207306177-bb208758-c145-4e3b-aeea-914571c59e0d.png)

MSYS2
![image](https://user-images.githubusercontent.com/73375859/207306327-d6f181fc-0962-49b2-94f2-a2a1334a9745.png)

安装情况
![image](https://user-images.githubusercontent.com/73375859/207307485-e7ac3819-b52f-4594-921f-9b90b67b747f.png)

**Comment by subframe7536** [comment]
...这个问题在最新的 v5.6 pre-release 修复了

**Comment by huge-pancake** [comment]
好的，谢谢😊

**Comment by huge-pancake** [comment]
Issue关得太草率了（什）。
我安装了从gitee下载的Maple Mono SC NF字体安装后，尝试了我能想到的所有方法刷新（包括重启电脑），但还是没这个字体。
使用旧版控制台这个选项，开了能看到更多字体，关了只有“点阵字体”和“新宋体”。

**Comment by subframe7536** [comment]
确认以下目录中没有旧字体再安装
%AppData%\\Local\\Microsoft\\Windows\\Fonts
C:\\windows\\fonts

**Comment by huge-pancake** [comment]
可以了，感谢！
