### ISSUE TITLE
字间距在特定情况下看上去像是多了个空格

### ISSUE THREAD

**Issue by QuarkPixel** [subframe7536/Maple-font#63]
<img width="549" alt="image" src="https://user-images.githubusercontent.com/65812149/209666768-8f14833c-f4b9-4fa5-8a26-56dce63e59c9.png">
<img width="26" alt="image" src="https://user-images.githubusercontent.com/65812149/209667098-e0cc6e74-e700-4547-a985-ed6b17613be9.png">
在「 ':: 」这种情况下（单引号 + 冒号）之间由于连字关系看上去像是多了一个空格 👀
不仅如此，平时双冒号在一起时都多多少少会有类似的误解，但是与单引号在一起的时候尤为明显。

**Comment by subframe7536** [comment]
这个算feature，连字关掉就ok了

后面会考虑是否加个开关

**Comment by subframe7536** [comment]
![image](https://user-images.githubusercontent.com/78338239/210127326-c4ecaa52-5eea-4001-8736-e6efaba28929.png)
调整了一下距离，你看看这样合适吗？

**Comment by QuarkPixel** [comment]
感觉上比之前好了一点👀
