### ISSUE TITLE
Nerd fonts are small

### ISSUE THREAD

**Issue by XXiaoA** [subframe7536/Maple-font#66]
I'm using `maple momo sc nf` and found that nerd fonts are small than i expected
![Screenshot_20230102_161858](https://user-images.githubusercontent.com/62557596/210207597-401ee074-3dbb-4b15-aedb-4e6ef2d2141f.png)

I wanna all fonts`s size are same and bigger like this: ( JetBrainsMono Nerd Font)
![Screenshot_20230102_161214](https://user-images.githubusercontent.com/62557596/210207606-0eba487e-40f8-4332-97ce-3460973550e6.png)

Then i'm using wezterm

**Comment by subframe7536** [comment]
> I wanna all fonts`s size are same and bigger like this: ( JetBrainsMono Nerd Font) ![Screenshot_20230102_161214](https://user-images.githubusercontent.com/62557596/210207606-0eba487e-40f8-4332-97ce-3460973550e6.png)

well, I think it's a misalignment

you can generate it yourself using font patcher in https://www.nerdfonts.com/

**Comment by exoess** [comment]
would it be possible to have glyphs but still have them centered?

**Comment by subframe7536** [comment]
noop, that will break the "mono" rule: every character should be same width

**Comment by exoess** [comment]
wouldn't even consider adding a command line argument to do it? so it's mono by default but still have the option for normal nf?

**Comment by subframe7536** [comment]
This is beyond my capability, feel free to PR if you can help.

**Comment by exoess** [comment]
i'm pretty sure i could do that, yea
