### ISSUE TITLE
是否能提供light版本

### ISSUE THREAD

**Issue by kkzi** [subframe7536/Maple-font#7]
感觉有一点粗，如图：
![image](https://user-images.githubusercontent.com/34122458/186083150-72534b4f-93ff-449d-a0d3-dd693fadb427.png)

附 Cascadia Code Light 供参考
![image](https://user-images.githubusercontent.com/34122458/186083254-bf59ff73-c576-4ee8-8246-f65a3b78af4a.png)

**Comment by subframe7536** [comment]
粗细效果主要考虑的是IDEA，太细会看得很累，v4.0 release细一些

**Comment by subframe7536** [comment]
[MapleMono-Thin.zip](https://github.com/subframe7536/Maple-font/files/9400269/MapleMono-Thin.zip)
这个粗细怎么样？

**Comment by kkzi** [comment]
> [MapleMono-Thin.zip](https://github.com/subframe7536/Maple-font/files/9400269/MapleMono-Thin.zip) 这个粗细怎么样？

v4.0 release 效果好一些
确实不同的编辑器效果都不一样
感谢您的付出

**Comment by kkzi** [comment]
> 可以试试v5.1，调整了一些间距

稍有点虚，可能再粗一点更合适，图如下：
![image](https://user-images.githubusercontent.com/34122458/186297346-324ae239-137d-4fad-9dac-25fdd72b68ba.png)

效果确实和编辑器渲染有关，这是其它地方的效果，供参考
![image](https://user-images.githubusercontent.com/34122458/186297882-5ac779e7-de29-4a69-8007-3154c5cc0133.png)
![image](https://user-images.githubusercontent.com/34122458/186298047-d4e7cb08-f50e-4add-871a-30c68871dafc.png)




另外提个小建议
light版和 regular版 Font name 应该区分开，不然选字体的时候都是 Maple Mono 区分不了
![image](https://user-images.githubusercontent.com/34122458/186297607-2afea753-88f9-41a9-97ce-32d75b3d0c37.png)

**Comment by subframe7536** [comment]
图1可能是hint的原因，我再研究一下
> light版和 regular版 Font name 应该区分开，不然选字体的时候都是 Maple Mono 区分不了
font name应该是不能写light/regular之类的字重，Fira code，jetbrains mono都是这样，字重应该是可以单独设置的

**Comment by kkzi** [comment]
> 图1可能是hint的原因，我再研究一下
> 
> > light版和 regular版 Font name 应该区分开，不然选字体的时候都是 Maple Mono 区分不了
> > font name应该是不能写light/regular之类的字重，Fira code，jetbrains mono都是这样，字重应该是可以单独设置的

这是目前我正在用的字体 [microsoft/cascadia-font](https://github.com/microsoft/cascadia-code)，供参考
![image](https://user-images.githubusercontent.com/34122458/186300954-820bd07a-71df-46b4-b901-b85081021c1c.png)

**Comment by darkhandz** [comment]
散光人士还妄想要比regular厚一点  ( *_* )

**Comment by subframe7536** [comment]
已添加Light&LightItalic
