### ISSUE TITLE
Feature request: FiraCode ligatures https://github.com/tonsky/FiraCode

### ISSUE THREAD

**Issue by cmarincia** [subframe7536/Maple-font#72]
Hey!
It would help a lot to have the ligatures that happen to be in FiraCode too.
I saw that most of them are implemented but some are missing like `!=` or `==` or `/=`.
For the `!=`(general purpose), `/=`(haskell), `~=`(lua) they could use some stylistics features for enabling them.

**Comment by subframe7536** [comment]
thanks for your advise
currently you can enable the font feature cv02 to get the ligature of `!=`
I will consider whether to add other ligatures in the next version

**Comment by subframe7536** [comment]
add in `/=` v6.2
