### ISSUE TITLE
Provide more font formats

### ISSUE THREAD

**Issue by cmarincia** [subframe7536/Maple-font#74]
Hey!
Love the font!
Is it possible to export the font to other formats like OTF, WOFF2, TTC/Super TTC? (single bundle, something that Iosevka does https://github.com/be5invis/Iosevka/blob/v17.0.2/doc/PACKAGE-LIST.md)
Thank you!

**Comment by subframe7536** [comment]
add otf & woff2 format

**Comment by shandianchengzi** [comment]
> add otf & woff2 format添加 OTF & WOFF2 格式

Love this font, too. Will there be any plans to convert it to the TTC format in the future? 💖

**Comment by subframe7536** [comment]
Can you describe your use case?

**Comment by shandianchengzi** [comment]
> Can you describe your use case?

Sorry for the late response. Initially, I was planning to disguise the font as Microsoft YaHei to replace the default Windows font. However, I’ve found that I can use TTF for font disguise, so there’s no need to use TTC.
