### ISSUE TITLE
line height seems to be wrong on macOS

### ISSUE THREAD

**Issue by CLCK0622** [subframe7536/Maple-font#75]
Hi there, I like your font very much and I also use it many times on Windows. However, when I try to use it on my iMac, there's a problem with the line height like what happens in the following pic.
<img width="851" alt="image" src="https://user-images.githubusercontent.com/36215258/211122690-141e67a5-7eb0-46e9-83ce-f045dddd0e9f.png">
However, the same problem only appears at _Regular, Italic, Light and Light Italic_.
The Bold, Bold Italic styles are very well. 
<img width="845" alt="image" src="https://user-images.githubusercontent.com/36215258/211122795-bea32d44-e29b-404d-bc4b-cfa8c86767a8.png">
I'm looking forward to your reply and if you need some test work, you can certainly publish it to preview and I'd be glad to help testing.

**Comment by subframe7536** [comment]
thanks for your love
To fix this bug, I want to know whether `maple mono` appears the same

**Comment by CLCK0622** [comment]
got it. I'm now trying this one and will give replies after further testing.

**Comment by CLCK0622** [comment]
> thanks for your love
> the reason maybe: https://www.maxkohler.com/posts/2022-02-19-fixing-vertical-metrics/
> To fix this bug, I want to know whether `maple mono` appears the same

<img width="1013" alt="image" src="https://user-images.githubusercontent.com/36215258/211156530-00c9b0b8-13c0-4d98-859e-dbbcab0f6b86.png">
u r exactly right and if there're any solutions for this problem? or `maple mono` is also acceptable for daily use?

**Comment by subframe7536** [comment]
So it may caused by NerdFont patcher.

you can download the patcher at the bottom of https://www.nerdfonts.com/ and run `font-patcher -l -s --careful -c /path/to/ttf` to get the same `Maple Mono NF`(except font's names)

if you only use `Maple Mono` only in editor, it is actually acceptable for daily use. `Maple Mono Nf` is made for command line use(mainly for icons)

**Comment by CLCK0622** [comment]
> So it may caused by NerdFont patcher.
> 
> you can download the patcher at the bottom of https://www.nerdfonts.com/ and run `font-patcher -l -s --careful -c /path/to/ttf` to get the same `Maple Mono NF`(except font's names)
> 
> if you only use `Maple Mono` only in editor, it is actually acceptable for daily use. `Maple Mono Nf` is made for command line use(mainly for icons)

alright, maybe I'll use `Maple Mono` instead
this font looks really nice
