### ISSUE TITLE
Can the ligatures of Equlity and Comparisons be turned on by default?

### ISSUE THREAD

**Issue by EdenHell** [subframe7536/Maple-font#80]
As the title：
![image](https://user-images.githubusercontent.com/5779655/212644430-bada73d2-de55-41dd-942b-93b1b02f7490.png)

**Comment by subframe7536** [comment]
sorry but won't fix
the main reason for me to make this font is, the ligatures of Equlity and Comparisons always be indistinguishable
you can use https://github.com/twardoch/fonttools-opentype-feature-freezer to turn them on by default
