### ISSUE TITLE
Why not provide mono SC version?

### ISSUE THREAD

**Issue by teteko233** [subframe7536/Maple-font#81]
I just want to use it on notepad. So I think a version without NF (like Sarasa Gothic Mono SC) is a clever idea.

**Comment by subframe7536** [comment]
this font originally just made for IDE and commandline.

with **all styles** installed, the mono sc nf version is just less than 3MB more than the mono sc version, very slight in relation to the overall size

currently you can use fonttools subset module to reduce the size

It may be made in the future release
