### ISSUE TITLE
WezTerm下字体间距显示异常

### ISSUE THREAD

**Issue by wzl20001001** [subframe7536/Maple-font#82]
下面几张图分别是在 Microsoft Terminal、Alacritty 和 WezTerm 中的显示效果。

- MicroSoft Terminal
  ![image](https://user-images.githubusercontent.com/49864068/217548400-beb028fa-8602-4b29-bbc5-06f0f6a8c587.png)
- Alacritty
  ![image](https://user-images.githubusercontent.com/49864068/217548518-91f10e2e-e514-448b-bffb-2c13ea846f5f.png)
- WezTerm
  ![image](https://user-images.githubusercontent.com/49864068/217551140-42768874-981c-4180-a8b0-0275070d07b4.png)

可以看到最后一行对于 `downlad` 这个单词的显示，WezTerm 中的 `do `和 `oa` 的显示相较于其他终端，字母间的间距异常。

> WezTerm.lua

```lua
local wezterm = require 'wezterm'

local default_shell = function()
	
end

return {
  font = wezterm.font('Maple Mono SC NF'),
}
```

调整字体大小后WezTerm的显示效果会好一些，字体大小为 `12.0` 时，字体异常现象尤为明显。

- 字体大小为 `11.0`，左边是Alacritty，右边是Wezterm。
  ![image](https://user-images.githubusercontent.com/49864068/217557667-b1271082-6609-4cfc-bd9e-8e4487313989.png)
- 字体大小为 `12.0` 。
  ![image](https://user-images.githubusercontent.com/49864068/217553953-1e09e34b-1e28-49fb-8249-135bdbad897c.png)
-  字体大小为 `13.0`。
  ![image](https://user-images.githubusercontent.com/49864068/217556959-94436143-dbf3-429f-9172-b346add033b7.png)
- 字体大小为 `14.0`
  ![image](https://user-images.githubusercontent.com/49864068/217558743-f95fa6ac-6a0f-417c-ab47-0cbec43ee38c.png)

相较于 Alacritty，WezTerm 渲染出来的字体显示效果明显有所不足。我觉得应该是 WezTerm 字体渲染的问题，但是我想问一下字体这边可以设置一些参数使其达到 MicroSoft Terminal 或者 Alacritty 的显示效果吗？

**Comment by subframe7536** [comment]
https://wezfurlong.org/wezterm/config/lua/config/freetype_load_flags.html

NO_HINTING或者NO_AUTOHINT 试一下

**Comment by wzl20001001** [comment]
完美解决，谢谢大佬。
