### ISSUE TITLE
[Feature Request]更多字形变体支持

### ISSUE THREAD

**Issue by JunkuiZhang** [subframe7536/Maple-font#83]
个人更喜欢Ubuntu Mono字体的i字形，可否参考Fira Code的cv06变体为本字体添加Ubuntu的i字形支持？
<img width="151" alt="image" src="https://user-images.githubusercontent.com/14981363/218247354-05a94da9-101b-462c-b997-c5c456cc8813.png">
当前字体的箭头内部有奇怪的空洞，可否对箭头增加如下变体支持？
<img width="172" alt="image" src="https://user-images.githubusercontent.com/14981363/218247445-74476579-d2ee-4585-a591-0f62fcd44c33.png">

**Comment by subframe7536** [comment]
1. 可以
2. 会考虑添加到CV01中

**Comment by SsparKluo** [comment]
还有 a 的字形，感觉现在的 a 和 o 有时候不是那么直观，可以考虑加一个传统印刷体的 a 的选项？

**Comment by subframe7536** [comment]
![image](https://user-images.githubusercontent.com/78338239/220623977-79eb1e21-3927-4a14-9a61-869fd6256b31.png)
这个有点丑，有啥改进意见吗

**Comment by JunkuiZhang** [comment]
> > fira code的cv06可以参考一下，辛苦了
> 
> 这个就是cv06的样子...

可能我审美比较怪？我很喜欢这种圆润的i

**Comment by subframe7536** [comment]
![image](https://user-images.githubusercontent.com/78338239/220627649-81c0eb49-afe8-42f0-bac7-44e43b502f97.png)
又改了下，最终效果

**Comment by JunkuiZhang** [comment]
很好看，非常感谢！辛苦了
