### ISSUE TITLE
Bug: Stylistic Ligature on macOS

### ISSUE THREAD

**Issue by shindgewongxj** [subframe7536/Maple-font#86]
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/59656935/219998729-242951b8-a650-4890-8d30-bc049655cec1.png">

Ligatures are able in Font Book preview but not work in Xcode or other situations.

**Comment by subframe7536** [comment]
sorry but I don't have a MacBook to test, maybe you can see [this one](https://www.reddit.com/r/swift/comments/fwtm83/ligature_issues_with_xcode/) or [this one](https://apple.stackexchange.com/questions/390494/how-to-set-xcode-font-alternative-stylistic-sets)
If the same problem comes up again, you can provide me more informations like MacOS version, XCode version and so on

**Comment by subframe7536** [comment]
https://github.com/tonsky/FiraCode/wiki/How-to-enable-stylistic-sets#some-apple-apps
