### ISSUE TITLE
能否提供一个double-width的nerdfont图标的版本

### ISSUE THREAD

**Issue by 45degree** [subframe7536/Maple-font#87]
这是从release下载出来的
![image](https://user-images.githubusercontent.com/43808585/220616698-99403abb-a855-48ae-a7ee-310743a85898.png)

这是期待的
![image](https://user-images.githubusercontent.com/43808585/220616111-231b4e07-e402-4314-8d88-db608aa40ee4.png)

**Comment by subframe7536** [comment]
很抱歉，但是我不会考虑做全宽的版本，因为最开始做的时候选的就是全宽版本，我认为不好看所以换成了半宽
你可以自行构建 https://github.com/ryanoasis/nerd-fonts#font-patcher
`font-patcher -l --careful -c 字体路径`
