### ISSUE TITLE
Feature Customization on `build.py`

### ISSUE THREAD

**Issue by shindgewongxj** [subframe7536/maple-font#89]
As some editor may not support modify character stylists, in this situation, users need build locally with fonttools to customize the features. Thank you for the creation!

**Comment by subframe7536** [comment]
currently you can use https://github.com/twardoch/fonttools-opentype-feature-freezer

**Comment by shindgewongxj** [comment]
Thanks! I was using the https://github.com/MuTsunTsai/fontfreeze 👍

**Comment by shindgewongxj** [comment]
> currently you can use https://github.com/twardoch/fonttools-opentype-feature-freezer

<img width="640" alt="Screenshot 2023-04-19 at 6 58 07 PM Large" src="https://user-images.githubusercontent.com/59656935/233055111-232559bb-c640-461e-a96c-b1c6a2aded66.png">

🤔️ Will the feature able customization settings in Xcode?

**Comment by subframe7536** [comment]
> 🤔️ Will the feature able customization settings in Xcode?

I can't afford to buy a macbook🥲, so I have no way to test that. 
I think it's supposed to be effect

**Comment by shindgewongxj** [comment]
> > 🤔️ Will the feature able customization settings in Xcode?
> 
> I can't afford to buy a macbook🥲, so I have no way to test that. I think it's supposed to be effect

For now, v6.3, the ss settings doesn't take effect or persist.
<img width="1358" alt="Screenshot 2023-04-19 at 7 18 08 PM" src="https://user-images.githubusercontent.com/59656935/233059617-48acbea8-c4be-4501-8d8b-b1e1ce55fef8.png">

**Comment by shindgewongxj** [comment]
> > For now, v6.3, the ss settings doesn't take effect or persist.
> 
> strange. it's effected in VSCode.
> 
> does `Fira Code` or `Jetbrains Mono` render properly?

I just tried Fira, not support as well…

**Comment by subframe7536** [comment]
> > > For now, v6.3, the ss settings doesn't take effect or persist.
> > 
> > 
> > strange. it's effected in VSCode.
> > does `Fira Code` or `Jetbrains Mono` render properly?
> 
> I just tried Fira, not support as well…

Will, I'm unable to offer any further assistance at this time😶‍🌫️

**Comment by shindgewongxj** [comment]
> > > > For now, v6.3, the ss settings doesn't take effect or persist.
> > > 
> > > 
> > > strange. it's effected in VSCode.
> > > does `Fira Code` or `Jetbrains Mono` render properly?
> > 
> > 
> > I just tried Fira, not support as well…
> 
> Will, I'm unable to offer any further assistance at this time😶‍🌫️

Fira Code does provide like this:
Fira Code:
<img width="306" alt="Screenshot 2023-04-22 at 9 30 19 PM" src="https://user-images.githubusercontent.com/59656935/233788023-599df0b4-b3ad-4495-a601-32c317c3302e.png">

Maple Font:
<img width="306" alt="Screenshot 2023-04-22 at 9 29 14 PM" src="https://user-images.githubusercontent.com/59656935/233788032-12a8a953-4ba9-4468-b3dc-92c61e3ed5b4.png">

**Comment by subframe7536** [comment]
v6.4 release. you can custom build your font
