### ISSUE TITLE
mac vscode 默认粗体

### ISSUE THREAD

**Issue by nick357** [subframe7536/Maple-font#9]
mac pro m1 下，系统为最新版本。
vscode配置
"editor.fontFamily": "'Maple Mono SC NF",
显示的是粗体。要按下面方式设置才能显示常规字体
"editor.fontFamily": "'Maple Mono SC NF Regular',

**Comment by subframe7536** [comment]
windows下没有出现这个问题，可能是mac上读取的是字体的全名？我没有mac的机子，没法测...

**Comment by nick357** [comment]
没测试环境是比较麻烦，先补个图吧。
Regular
![1](https://user-images.githubusercontent.com/1915776/186102325-4cdecebe-2580-4399-be1a-88615abc72f8.png)
No Regular
![2](https://user-images.githubusercontent.com/1915776/186102447-ca873406-ed45-4832-b316-0bf3da1f6ff8.png)

**Comment by nick357** [comment]
Regular 没加粗但中英文没对齐，不加Regular变粗了，中英文对齐了

**Comment by subframe7536** [comment]
...你这regular不是我的字体

**Comment by subframe7536** [comment]
我的本来就比较粗一些...

**Comment by nick357** [comment]
![image](https://user-images.githubusercontent.com/1915776/186105318-56b56970-cf82-4e9b-a705-52f709f5145d.png)
 嗯，感谢即时回复。确实比较奇怪，我只设定了一个字体。
而且vscode的命令行终端弹出说终端之支持等宽字体，似乎是未能正确识别出该字体是等宽字体。

**Comment by jinnyu** [comment]
> ![image](https://user-images.githubusercontent.com/1915776/186105318-56b56970-cf82-4e9b-a705-52f709f5145d.png) 嗯，感谢即时回复。确实比较奇怪，我只设定了一个字体。 而且vscode的命令行终端弹出说终端之支持等宽字体，似乎是未能正确识别出该字体是等宽字体。

+1 IDEA也未认出字体是等宽字体

**Comment by subframe7536** [comment]
mac的坑比较多...https://github.com/subframe7536/Maple-font/releases/download/v4.0/Maple.Mono.NF.ttf 这个试试？如果还是不行的话需要后续研究一下了...

**Comment by nick357** [comment]
![image](https://user-images.githubusercontent.com/1915776/186107591-9eb66c0c-48fb-479b-9a09-ad7f1d123ae5.png)
补充下，Menlo这个字体，我配置时后面不用加Regular也能正常。
说明正常情况下应该不用加Regular

**Comment by subframe7536** [comment]
> ![image](https://user-images.githubusercontent.com/1915776/186107591-9eb66c0c-48fb-479b-9a09-ad7f1d123ae5.png) 补充下，Menlo这个字体，我配置时后面不用加Regular也能正常。 说明正常情况下应该不用加Regular

Maple Mono也是这样吗？还是说只有Maple Mono SC NF这样？

**Comment by nick357** [comment]
测试了你刚才的4.0的Maple Mono也是一样的，vscode也识别不了是等宽字体。

**Comment by subframe7536** [comment]
> 测试了你刚才的4.0的Maple Mono NF，是能被vscode成等宽字体。但这个缺失中文部分吧。 刚才是没设对字体。

收到，大概找到原因了，现在需要确认一下，5.0的maple mono是否能和menlo一样不用输入regular，但是无法识别等宽？

**Comment by nick357** [comment]
5.0的Maple Mono 我验证了。
Maple Mono 是vscode识别是等宽，但字体比较粗，感觉匹配到了粗体。
Maple Mono Regular则不能识别是等宽，但字体细些。

**Comment by subframe7536** [comment]
> 5.0的Maple Mono 我验证了。 Maple Mono 是vscode识别是等宽，字体粗细和下面一样。 ![image](https://user-images.githubusercontent.com/1915776/186111728-31346691-1d31-4aff-a7e5-7eff32ae7f5b.png)
> 
> Maple Mono Regular则不能识别是等宽，字体粗细和上面一样。 ![image](https://user-images.githubusercontent.com/1915776/186111576-ad195ca6-e753-4928-a241-5e1a1ad4bf4d.png)

font-family引号多打了一个单引号....不知道有没有影响？

**Comment by nick357** [comment]
那个单引号应该是不小心弄掉了，加了，完全去除单引号都是一样的现象。应该是被自动处理了。
总结下就是
"editor.fontFamily": "'Maple Mono'"
等宽，字号正常
"editor.fontFamily": "'Maple Mono Regular'"
不等宽，字号正常
"editor.fontFamily": "'Maple Mono SC NF'"
等宽，字号太粗
"editor.fontFamily": "'Maple Mono SC NF Regular'"
不等宽，字号正常

**Comment by subframe7536** [comment]
> 那个单引号应该是不小心弄掉了，加了，完全去除单引号都是一样的现象。应该是被自动处理了。 总结下就是5.0版本 "editor.fontFamily": "'Maple Mono'" 等宽，字号正常 "editor.fontFamily": "'Maple Mono Regular'" 不等宽，字号正常 "editor.fontFamily": "'Maple Mono SC NF'" 等宽，字号太粗 "editor.fontFamily": "'Maple Mono SC NF Regular'" 不等宽，字号正常

感谢测试！下一版我会修复这些问题

**Comment by nick357** [comment]
重启了下机器以后已经好了，不应该加Regular和单个的'，加了这两个应该都市匹配不到字体，用的系统默认的。
英文在纯文本下黑色显得比较粗。但在代码着色的地方感觉还可以接受。
感谢提供这么棒的字体。🙏
