### ISSUE TITLE
Help enabling stylistic settings

### ISSUE THREAD

**Issue by assayire** [subframe7536/Maple-font#93]
Based on the README and the stylistic settings seen [here](https://github.com/subframe7536/Maple-font/blob/main/img/option.png), I am trying to enable ss02 in sublime text and intellij. It does not work. Not sure what I am doing wrong.

For sublime text (build 4143), I am setting this:

```
"font_face": "Maple Mono NF",
"font_options": ["ss02"],
```

Is that not enough to enable ss02?

**Comment by subframe7536** [comment]
Saddly, ligatures with letter are not supported in sublime, here is the [doc](https://www.sublimetext.com/docs/ligatures.html), and currently there is no way to enable font features in intellij
