### ISSUE TITLE
How to enable ligatures for double underline(__) ?

### ISSUE THREAD

**Issue by ippfcox** [subframe7536/Maple-font#94]
If this is not supported for now, any plans to add this feature?

thanks

**Comment by subframe7536** [comment]
ok, it will be added at v6.3

**Comment by ippfcox** [comment]
> ok, it will be added at v6.3

great, thank you for your excellent work!

**Comment by WindSoilder** [comment]
TBH, I don't like ligatures for double underline.  Can it be added to different CharactorVariant?

**Comment by subframe7536** [comment]
@WindSoilder I plan to add it to ss03

**Comment by WindSoilder** [comment]
Thank you!  Much appreciated!

**Comment by subframe7536** [comment]
done in v6.3
