### ISSUE TITLE
[Feature Request] <=和>= 连字支持

### ISSUE THREAD

**Issue by JunkuiZhang** [subframe7536/Maple-font#95]
请问能否启用以下连字：
<=和>=
<img width="122" alt="image" src="https://user-images.githubusercontent.com/14981363/224326666-e2f4c7b2-0560-44d9-bcea-7a9a4b31708d.png">

**Comment by jakaz1280** [comment]
不知道制作字体的工具能不能看别的字体里设计了多少连字，能看的画我觉得可以看看Jetbrains Mono设计了多少连字

**Comment by subframe7536** [comment]
@jakaz1280 可以的，但是有些我认为不常用的就没加进去

**Comment by arjpar** [comment]
@subframe7536 >= and <= are very commonly used

**Comment by subframe7536** [comment]
@arjpar Yes, but the reason I created this font was that I didn't like some ligatures in Fira Code, including these two

**Comment by freest233** [comment]
一人血书增加这几个连字特性

**Comment by subframe7536** [comment]
done in v6.3
