### ISSUE TITLE
OverflowError: unsigned byte integer is greater than maximum 

### ISSUE THREAD

**Issue by sonulohani** [subframe7536/maple-font#96]
I am using font MapleMono https://github.com/subframe7536/Maple-font/releases/tag/v6.2
and I see this issue in https://mutsuntsai.github.io/fontfreeze/
![image](https://user-images.githubusercontent.com/2958681/231939127-2ce11da3-ea74-4991-ba4b-ee668104c505.png)

The issue is in the font: https://github.com/MuTsunTsai/fontfreeze/issues/7

**Comment by subframe7536** [comment]
I'll fix it as soon as I can

**Comment by Finii** [comment]
>  it should be caused by nerdfont patcher

Well, it seems an ancient version of the patcher is used here: Version `2.1.0`

![image](https://github.com/subframe7536/maple-font/assets/16012374/6a17ce4f-a079-45fc-a577-af7979643c70)

Current is `3.0.2`; if you do not want to switch to the `v3` codepoints, at least `v2.3.3` should be used.

More importantly, and probably the reason for the bug, is to use a recent (i.e. Release 2023.01.01) `fontforge` together with the `font-patcher`. There have been various bugfixes in `fontforge` that could result in broken fonts like mentioned above.

**Comment by subframe7536** [comment]
@Finii thanks for your suggestion! it will be fixed in v6.3

**Comment by subframe7536** [comment]
v6.4 release. upgrade Nerd Font to v3.0.2
