### ISSUE TITLE
MacOS 下 部分liga 没有效果

### ISSUE THREAD

**Issue by zengbo** [subframe7536/Maple-font#99]
用的字体： ”Maple Mono NF“
在 MacOS 下部分liga 没有效果：
```
==
===
!=
!==
>=
<=
[info] ...
```

**Comment by subframe7536** [comment]
没有mac，已知xcode中目前无法开启styleset

**Comment by cshuaimin** [comment]
I found that you need to enable the font features to see the effects, e.g. in Kitty `font_features MapleMono-Regular +ss01 +ss02`

**Comment by zengbo** [comment]
> I found that you need to enable the font features to see the effects, e.g. in Kitty `font_features MapleMono-Regular +ss01 +ss02`

How to set in VSCode?

**Comment by cshuaimin** [comment]
@zengbo It's `"editor.fontLigatures": "'ss01', 'ss02'"` in settings.json
<img width="361" alt="Screenshot 2023-05-05 at 2 04 34 PM" src="https://user-images.githubusercontent.com/24775746/236387208-9ed39fb3-d8cb-4e70-b948-1dee3516d1f5.png">

**Comment by zengbo** [comment]
> "'ss01', 'ss02'"

Thanks.
